### PR TITLE
Expand `/echo` command with `cssClass`, `color`, `escapeHtml` and `onClick`

### PR DESCRIPTION
**Pull request by Wolfsblvt**
New arguments to the `/echo` slash command.
`toastr` has a lot of options and customizability. And for one of the most-used slash commands (I figure), it's likely a good idea to expose a lot of options.

#### 1. `cssClass` to add a CSS class to the toast div
By itself, this doesn't do anything. But it allows extensible styling of toasts to your liking, based on existing CSS classes or one you can define via Custom CSS.
Until now, toasts couldn't be specifically targeted for styling. Now you can give them groups, names, whatever. Change background color, change font. Replace the icon. Style the header bigger, whatever. The rest is just custom selector below the class.

#### 2. `color` argument to quickly change toast color
The four types of toasts (info, success, warning, error) have their respective color. You could change them via styling, but that'd apply for all. You could apply a `cssClass` now, but this is faster and in-line.
It basically just sets the provided string into the `background-color` CSS property of the toast. On the user to check for validity, but all color writing styles are supported. Even transparent and unset to make it funny.

#### 3. `escapeHtml` to allow HTML-formatted toasts
Pretty self-explanatory. ST sets this to `false` by default. We can specify true or false here manually, and you can render whatever big information or even images you deem needed.

#### 4. `onClick` allowing closure execution when you interact. This is async (unless `awaitDismissal` is set), so your script itself continues running.
You can write whatever closure you want, it receives the full scope of the place it was written. Even local variables can be accessed, and they keep their values and all. Amazing, right? Think about the possibilities!
Still a disclaimer, as this allows parallel execution and such, it's not trivial. But loops and more have the same issues, so.

I tested this with this:
```
/let key=clicked 0 |
/let key=callback {: /var key=clicked {: /add clicked 1 :}() | /echo onClick={: /var key=callback :}() YOU CLICKED ME; DEAR GOD. ALREADY {{var::clicked}} TIMES :} |
/echo onClick={{var::callback}} You wanna click me? 👉👈 ...
```

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
`escapeHtml=false` opens a **huge** security hole. 
```
/echo escapeHtml=false <script>alert(1)</script>
```
Incoming HTML should be sanitized with DOMPurify to prevent abuse.

**Comment by Wolfsblvt** [comment]
Any specific special requirements what tags are allowed, or just the default `DOMPurify.sanitize` as we use it in many other places?

**Comment by Cohee1207** [comment]
`DOMPurify.sanitize` is fine and handles most of bad HTML cases. But I think it allows <style> blocks which would pollute global page styles. You need to exclude style.

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
Still vulnerable. You also need to escape the title

**Comment by Wolfsblvt** [comment]
> Still vulnerable. You also need to escape the title

**Review by Cohee1207 — APPROVED** [review]

**Pull request merged**
