### PR TITLE
Add maxTotalChatBackups config.yaml value

### PR DESCRIPTION
**Pull request by Cohee1207**
Limit a total number of backups per user to a configurable value with `maxTotalChatBackups` by deleting the oldest.
Individual number of backups per character is still controlled by `numberOfBackups`. Disable with a negative number to restore the classic behavior (default).

Rationale: there were some complains that there's too many backups produced. And if you suddenly decide to restore from a backup, it's more likely to be something closer to the most recent.

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by cloak1505** [comment]
4000 will bring it to about 100 MB.

One of my ideas is to ~~keep 1 save per day~~ (wrong, see edit below) for each set of chats older than 2 months (set = saves for a specific card). For example, instead of
```
chat_foo_20241007-160441.jsonl
chat_foo_20241007-160430.jsonl
chat_foo_20241007-160420.jsonl
chat_bar_20241007-121001.jsonl
chat_bar_20241007-120951.jsonl
chat_bar_20241007-120929.jsonl
```

I'll get 
```
chat_foo_20241007-160441.jsonl
chat_bar_20241007-121001.jsonl
```

Similar to running OS backup software to keep 7 latest daily incrementals, except for the "squashing" part where older incrementals are either combined into a differential or a full.

___

**Edit**

In the Discord server, the majority voted Unlimited. Either they're resistant to change, saw the 500 and 1000 options and thought that's way too low and didn't feel like suggesting on Other option, or have fear and doubt on their minds and are inappropriately relying on it as a backup. The reason I say inappropriate is because it is not a suitable replacement for a real backup. There are many saves of the same file. Nobody really needs granular saves past 1000. Notice there's more votes for 500 than 1000.

My initial suggestion of 1 save per day after 2 months is flawed. Backup-wise, what we really want is the `chat_id_hash` which is tied to a "normal save".

My "past 2 months" is actually 5.8k currently.

I suggest a soft cap of 2000 granular saves, then an *unlimited* hard cap. After 2000, the latest of all unique `chat_id_hash` are kept. If someone loads an old save and chat on it, it won't overwrite the old backup until that one reaches 2001.

This way, users still have one backup of every chat hash they created, and it will only "bloat" to the number of saves they create. Nobody should say "I need that one swipe I remember I deleted a long time ago".

HOWEVER! This is flawed as is. A new `chat_id_hash` is created upon new chat. Branches are assigned the parent hash. I notice it stores the name of the parent chat in `main_chat` but not its own name. To fix this, each normal save, as in each file in `./data/default-user/chats` and `./data/default-user/group chats` needs their own hash.

**Comment by ghost** [comment]
> 4000 will bring it to about 100 MB.

Uh, could you explain? I just checked and windows filesystem nonsense should even out to 4k files = min ~16mb (NTFS cluster size and stuff). Did you assume 25kb per chat?

**Comment by cloak1505** [comment]
> Uh, could you explain? I just checked and windows filesystem nonsense should even out to 4k files = min ~16mb (NTFS cluster size and stuff). Did you assume 25kb per chat?

Backup size will vary between users, of course.

image

My backup saves are between 0 B to 360 KB (not KiB), median being 14.3 KB.

My latest settings_default-user_date-time.jsonl are 173 KB.

**Comment by Xeddius** [comment]
Consider, for the future a more complex backup option utilizing versioning/delta patching.
Probably best as a long-term goal, anything in the chat that overlaps can be condensed and compressed.

Text compresses exceptionally well, so it may be wise to have a compression scheme for the backups along with a .metadata file for a preview and the basic information.

So, restoring a backup would display the metadata, confirmation, and then decompress.

If this is already being done feel free to disregard.

I prefer not to have backups of chats as it's not needed with my current system configuration.

As for format you could call it .backupchat as it could be pretty useful.

A json file with the compressed data stored inside would suffice.

```
{
    "metadata": {
        "filename": "example.txt",
        "preview": "This is text of the most recent chat..."
        "character": "Seraphina"
        "size_original": 1024,
        "size_compressed": 256,
        "compression_method": "zlib",
        "created_at": "2024-12-14T12:00:00"
    },
    "data": "eJyrVkrLz1eyUkpKLFKyUjAyBgAwDwQJ"  //< Base64-encoded compressed data
}
```

**Pull request merged**
