### PR TITLE
Added a new button wich injects /sandas={{char_name}} command in send…

### PR DESCRIPTION
**Pull request by Saref111**
Hi everyone, I tired from entering /sendas command, so I added a new small button to automate this action. 
image
It works both with empty and filled textareas, so if you decide to send as a char after typing your message you will not lose your text.

### CODE REVIEW

**Comment by Cohee1207** [comment]
I think it kind of duplicates the functionality of quick reply buttons with {{input}} macro in command text. The only thing missing would be the ability to get a group member name by index which could be a separate command.

**Comment by Saref111** [comment]
Unfortunately, I can't find how to do this thing with quick reply. But if you think it's a redundant feature, that's fine. I can add any buttons for myself locally =)

**Comment by Cohee1207** [comment]
I guess you can make it as an extension (and submit it to the official registry if desired) if it doesn't work with STscript commands only. Please look at the following resources and let me know what you think:

https://docs.sillytavern.app/for-contributors/writing-extensions/
https://github.com/SillyTavern/SillyTavern-Content

**Comment by Cohee1207** [comment]
Just a hint: an extension could modify a group member template and read the character name from it when the click event is triggered.

**Comment by Cohee1207** [comment]
Hi @Saref111,

I implemented your idea into an extension. Please take a look.

https://github.com/Cohee1207/SillyTavern-GroupSendAs

Regards.

**Pull request closed without merging**
