### PR TITLE
Implement downloadable tokenizers

### LINKED ISSUE #2574: [FEATURE_REQUEST] Add Qwen 2 Tokenizer
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

N/A

### Describe the solution you'd like

Title is self explanatory. 

### Describe alternatives you've considered

GPT2 tokenizer is the closest one can get for models like Qwen and Magnum, but due to different pretokenization rules, it's not ideal.

### Additional context

N/A

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

### PR DESCRIPTION
**Pull request by Cohee1207**
Closes #2574, #2754

We can now distribute tokenizers without polluting the repo with huge JSON blobs. I've created a separate repository for storing tokenizer assets: <https://github.com/SillyTavern/SillyTavern-Tokenizers>

There are now two tokenizers to be downloaded:

1. Qwen2
2. Command-R (used by Cohere CC source).

The opt-out option exists in config.yaml: `enableDownloadableTokenizers`. You can also download tokenizers manually and put them into your data directory. If model is not cached and the download is disabled, a fallback tokenizer will be used for counting (llama3 in this case).

_Documentation update pending._

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Review by RossAscends — APPROVED** [review]

**Review by Wolfsblvt — APPROVED** [review]
The new `config.yaml` option is supposed to not be added to the file if I had one already, yes?

If I turn that setting off, the server console shows the error correctly, and the backend initializes the fallback tokenizer.
On the frontend, I don't see any of this though. It still says "Qwen2" and looks like it is that tokenizer running in the background.
I think that's okay, Your own fault if you disable the setting. But if it's easy to implement *some* kind of indicator for this, it wouldn't hurt.

Looks good in total.

Question is, you plan to move some of the other existing tokenizers over there too?

**Comment by Cohee1207** [comment]
> Question is, you plan to move some of the other existing tokenizers over there too?

Potentially, but only the most unpopular ones (will depend on how much Jamba will be used). But the plan is to add niche tokenizers as downloadables.

**Comment by Cohee1207** [comment]
> The new config.yaml option is supposed to not be added to the file if I had one already, yes?

Yes. It auto-adds missing values since the initial migration to YAML format.

**Comment by Wolfsblvt** [comment]
Funny. Didn't add them for me the first time I tried, not it worked. So all good.

**Comment by Cohee1207** [comment]
Docs updated. Ret-2-go.

**Comment by Cohee1207** [comment]
> Didn't add them for me the first time I tried, not it worked

You have to run `npm install` manually or with the start-up script as this is done in post-install. If you start with `npm run start` or `node server`, the script won't run.

**Comment by equal-l2** [comment]
Thank you for the addition!
FYI `c4ai-aya` family also uses the `command-r` tokenizer because they are fine-tuned models based on command-r-plus.

**Pull request merged**
