### PR TITLE
Blip extension

### PR DESCRIPTION
**Pull request by Tony-sama**
# What it does:
- animate the text of character messages with variable speed and play sound along the animation
- Can use audio file or generate the sound

# How it does it:
- Intercept the message using events -> store it and replace by blank in chat history -> wait if an animation is playing -> message get rendered empty -> (optional translation) -> animation start
- Message received are queued to allow to run generate() while animation is played (usefull when user message is animated or in group chat).
- Animation can be force to finish by clicking on usual abort request button (bottom right)

# Features:
## Global settings
- TTS extension inspired options
  - enable/disable user message blip (require user voice assigned to play)
  - only blip for quote
  - disable asterisk blip
 - Enable/disable auto scrolling down to follow text animation.
 - Global audio mixer applied to any blip sound playing (mute/volume) 
 - Settings are saved per character like for RVC extension using a voicemap
  - The voicemap text is just for debug visualization, not editable directly
  
image

- Default option is the profile that will be used for character with no settings. (if not set, no animation)
- User name appear in second in the list, can be assign a blip like any character (need checkbox enable for it to play)
- Only current chat character show in the list by defautl, clicking the checbox show all character
- Character group list updated automatically, refresh button is for special case like when user add/delete a character for global list update
image

## Text settings
- Animation settings allow to set text speed and min/max random multiplier for more dynamism. Some special delay can be applied on comma and phrase end (?,!?.) characters.

Capture d'écran 2023-09-29 205324

## Audio settings
- Audio settings, audio speed is independant of text speed except when text pause the audio when comma/phrase delay is set > 0ms. Audio volume percent can be applied for the character, will be a percent of the global sound option when played.

Capture d'écran 2023-09-29 205402

### Audio origin
- By default a generated sound. User can choose a min/max frequency a random frequency of this range will play for each blip.

image

- Audio origin, can also be a audio file from the asset folder. In this case pitch shift min/max can also be choosen for random variation (done without library for now). Also an option to force play the whole audio before starting it again, can be usefull for some effects.

image

# Remarks:
- Can skip animation using the abort request button
- Compatible with translate extension, only the translation is animated.
- Burger menu regenerate/continue click should have no effect *while animation is playing*.
- When using burger menu continue only the new part is animated.

### CODE REVIEW

**Comment by BaconIsAVeg** [comment]
This would be great if the text animation and audio bits were split into 2 different extensions.  I like the animation idea, Ren'py does that.  Could care less about the audio stuff though.

**Comment by Tony-sama** [comment]
> This would be great if the text animation and audio bits were split into 2 different extensions. I like the animation idea, Ren'py does that. Could care less about the audio stuff though.

Assign a default profile with generated blip sound and mute the blip, you get text animation without sound :)

**Comment by BaconIsAVeg** [comment]
> Assign a default profile with generated blip sound and mute the blip, you get text animation without sound :)

I think my feedback was more geared towards the conversation in Discord about what constitutes 'default' functionality vs 'this is an extra plugin'.

My general feeling is that functionality which changes text rendering is pretty useful, and makes sense to have as a 'default'.  But audio/voice stuff is a fairly small subset of users (from quick polling), and really doesn't belong as a 'default' thing that muddies up the already bulging interface/scripts.

**Comment by IkariDevGIT** [comment]
@BaconIsAVeg if people finally notice this blip stuff and use it for a bit.. it will get mainstream real quick, here is why i think so:
- completely free
- no computation cost + local
- doesnt have the synthetic feeling like TTS does
- would add up nicely to the other vn-like features(vn mode, expressions, dynamic sound)
- Is really nicely customisable like other stuff in ST + Still easy to use + Feature packed with stuff
- In contrast to something like RVC(which btw.. is built in!) it is very lightwheight(RVC makes loading time for some reason really long).

but if this extension will be external, it will go unnoticed.. and tbh.. tony-sama put a lot of work into this!
So saying "But audio/voice stuff is a fairly small subset of users" for this makes small to no sense. It makes the convo feel kinda "lively" and more immersive without breaking immersion with shitty TTS.

So.. if you want this to be an external extension, remove TTS and RVC too.. because it does mostly the same stuff while being unoptimized and sounding kinda bad.

**Comment by BaconIsAVeg** [comment]
> So.. if you want this to be an external extension, remove TTS and RVC too.. because it does mostly the same stuff while being unoptimized and sounding kinda bad.

Personally I think they should be.  It doesn't make sense for them to be in the default UI when there's so much additional work and setup requirements to use them.

Even stuff like the Stable Diffusion integration, who actually uses it? It takes so much prompt work to get a decent image out of SD, it's not magic.  Personally I think a lot of this stuff should be moved out into their own repos and like you said on Discord, you enable it via checkboxes sort of like how Stable Diffusion handles extensions.

**Comment by IkariDevGIT** [comment]
@BaconIsAVeg I agree with it of course if it will be handled like in SD webui, but the current approach is.. not really optimal

**Comment by BaconIsAVeg** [comment]
> @BaconIsAVeg I agree with it of course if it will be handled like in SD webui, but the current approach is.. not really optimal

Right, and the more default extensions that keep getting added, the further from that goal it gets.

**Comment by Tony-sama** [comment]
Blip has been made into a third party extension, peolple can get it from the asset extension menu :)

**Pull request closed without merging**
