### PR TITLE
WI scan refactoring:  Extended logging, updated code flow, changed Min Activations

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Bigger refactoring of WI scanning

### Logging Changes / Refactoring
- Improved logging, with `[WI]` prefix
- Cleaned up wrong logging messages
- Added logging messages for many missing debugging steps
- Made "lazy logging" for entries to not log at all if there is nothing interesting to log (especially when just skipping)
- Change obj format of WI entries, so world name comes early (`{ "uid": 15, "world": "World Name", [... rest of the fields ...]  }`)
- Write headers above the different sections of WI debug logging. Write current loop info.
- Non-Debug log of all activated entries at the end

### Code/Execution Changes
- Removed nested loop for primary and secondary keys.
  Now checks if any primary key is found. If not, exits out. Then checks all secondary keys to see if they satisfy the condition.
- Refactor probability check to correctly only roll probability if its really needed

### Min Activations Changes
- Min Activations now does the first sweep without recurse buffer (to see if we have new hits just from message content)
- Then follows up with the same context, but does a recursive sweep if there is an existing recurse buffer (To find WI entries that are might be triggered by the new message and existing already activated WI)
- Recurse continues same as for the normal first run until no new WI entries are found. Then it'll check min activations again, and increase scan depth another time, if needed. Until the min activations is fulfilled or the max depth is reached.
- Min Activations now **scans the full context range again**, changing back from #2010. This was breaking any secondary key conditions that would be spread over the new increased message range and older conditions. Context needs to stay, both the basic message buffer and also the recurse buffer of triggered WI.

Original PR comment below.

-------------

Don't ask me why I did this....

Logging makes much more sense now.
I  tried to split all changes into self-contained commits, so you can check them one-by-one. The first one is the easiest, as there are no coding changes. The further we go, the more we have to check the logic didn't change....

I checked thoroughly, multiple times. Ran test cases. But well. Four eyes.

## Checklist:

- [O] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
@aisu-wata0 Hey, sorry for pinging. I ran into issues with the Min Activations, while testing WI processing and doing my refactoring here, and I think this is worth a fix.
But I just noticed that you changed the behavior recently with #2010. Can you maybe take a look at this PR, especially the explanations I have made about Min Activations?
Maybe I missed something, or you have overlooked something back then with the PR, but I think it's worth looking into.

The issue I noticed is with secondary keywords. And I think many people tend to forget those. Just with primary keywords, yes it makes sense to just skip scanning old messages again. But if we see Min Activations as some kind of ***Dynamic Depth Increase*** - what I think it is -, we should not cut off possible secondary key matches that are made possible by the increased depth.

I made the following in-depth explanation about it on the Discord

> ## Messages
> 1: Jacke
> 2:
> 3:
> 4:
> 5: 
> 6: Baum
> 
> ## WI
> 1: Key: Baum => Rainy Weather
> 2: AND ALL: Jacke, Rainy Weather => Please put your jacket on, dude 
> 3: AND ALL: Jacke, Baum => You might not need your jacket if you can hide under a tree 
> 
> Normal Depth: 5
> Min Activations: 3
> Max Depth: 10
> 
> ### Initial Run
> Activates WI 1, because of keyword inside the messages 1-5 (reverse order, of course)
> 
> ### Recursion
> Because WI got activated, it checks recursion. Nothing changes, second WI can't trigger.
> End of WI checking, state NONE.
> Min activation is now "triggered"
> 
> ### Min Activations
> Advance to Depth 6.
> Messages from 1-5 are still internally in the buffer, but aren't used anymore. Only message 6. WI entry 1 that was activated is still available in the recurse buffer.
> Message 6 does not trigger anything new. current logic says on min activations state recurse buffer is not used. Resulting state: NONE, as there are no new entries, recursion will not be triggered.
> <--- **That one is wrong**
> 

I have argued (and now changed) that both WI 2 and 3 should also be triggered.

**Comment by aisu-wata0** [comment]
You're correct (i.e. Min Activations should check the whole history to be correct, to yield the same results as a normal scan to the depth it ends up in incrementally, as far as I understood).
I did https://github.com/SillyTavern/SillyTavern/pull/2010 because of performance, scanning everything every loop (as it was before the PR) quickly scales to be unusable.
(in a quick test now, on a chat with 38k token chat history and some random global Lorebooks, the difference is 2 seconds when scanning only the new msgs at each depth increase, to 10 seconds scanning everything each time)
Of course, I didn't thoroughly think about this correctness tradeoff at the time, missing the secondary keyword consideration.

However, its still true it becomes unusable (especially on mobile) when it should actually matter (big chats, otherwise just scan everything from the start and set a good budget) sadly pretty bad doing the naive correct way (startDepth always 0). When I did this change, mobile would freeze while going through the WI check code, which would be at every new msg and edit and maybe some other events, maybe this changed and its not the case anymore.

I believe a good way to fix this would be adding found keywords (of non-activated entries) to the recursion buffer (or an equivalent new buffer with an appropriate name), and forgo the need to search every message every time/loop, this way secondary keywords will work.
(If doing this fix is out of scope, its fine. If the performance consideration is still relevant (freezes mobile) I personally think its best left non-equivalent to a normal depth scan, but also don't hold strong opinions either way. It would be cool to detect when the WI checks took too long and console warn the deviant elapsed time.)

There's another thing, I see Cohee added this code to ignore/not use the recursion buffer when going through the chat while in the Min Activation state. I think this is related to your concern (behavior will be different), if we want Min Activations to behave exactly like a normal scan at increasing depth.
I don't know the underlying reason for the change, so maybe Cohee isn't considering Min Activations to behave equivalently to a normal depth scan, and just a "partial" or quick one.
```js
        // Min activations should not include the recursion buffer
        if (this.#recurseBuffer.length > 0 && scanState !== scan_state.MIN_ACTIVATIONS) {
            result += '\n' + this.#recurseBuffer.join('\n');
        }
```

**Comment by Wolfsblvt** [comment]
Remembering matched keywords to not need to parse the whole original depth again sounds like an interesting idea. It's not that easy again, though. As we should not forget that regex keys can exist now. (They didn't back then when you made the PR)
Even if you remember that a regex was matched as a key, you cannot leave out the possibility that there might be a secondary regex key that only matches over multiple messages, after the depth was already increased.
Might sound like a very rare edge case, but that would be very unexpected behavior again.

I think there is no easy solution for this trade-off of performance vs correctness with activations.

> I don't know the underlying reason for the change, so maybe Cohee isn't considering Min Activations to behave completely like a normal depth scan, and just a partial one.

No, that change is correct. Think about it like this. When you do the original first scan, your are only scanning the messages, not looking inside WIs (because there are none activated yet).
This code basically emulates the same for Min Activations. When the depth is increased, e.g. from 5 to 6, it'll first only scan the new 6 messages again, and see if there are any new matches. Pretending triggered WI don't exist. Because entries matching just the chat should always come **before** entries that are triggered via other WI.
After that first min activations sweep, there'll be another run with included recurse buffer (if there is any), to check for even more WI to match, before it'll run into the next depth increase for min activations.
See here https://github.com/SillyTavern/SillyTavern/blob/03a8b14a93882ab5c6b85eb7b920f117e2fb3204/public/scripts/world-info.js#L3868-L3872

> (If doing this fix is out of scope, its fine. If the performance consideration is still relevant (freezes mobile) I personally think its best left non-equivalent to a normal depth scan, but also don't hold strong opinions either way. It would be cool to detect when the WI checks took too long and console warn the deviant elapsed time.)

To be honest, I think "Min Activations" is not a feature you should use if you are limited on performance and execution power. Bigger scan depth and choosing a good WI budget sounds more reasonable then.  
Min Activations is inherently something that requires reprocessing of WI again and again, and that is not preventable.

This PR in its own should bring some slight performance improvements for any WI scanning though, not just considering min activations, as some unnecessary steps are skipped now.

**Comment by aisu-wata0** [comment]
Yup, makes sense, and agreed with the conclusion. Good job on the improvements.

**Comment by Cohee1207** [comment]
The performance problem should be less noticeable now as it optimizes the use of the buffer in a way it only gets constructed once per entry instead of once per key.

**Comment by Wolfsblvt** [comment]
Yeah, buffer processing was placed badly before, and it scanned keys against the buffer even when it didn't need anymore. Both are improved now.

Let's see how this plays out in reality. I would wait for some more reallife testing against some bigger WI books and some chats to see if I didn't break anything, and then we can merge this.

**Review by Cohee1207 — APPROVED** [review]
Testing is long overdue, so I'm YOLO-merging to gather feedback on staging.

**Pull request merged**
