### PR TITLE
Add support for the new TTS - XTTSv2

### PR DESCRIPTION
**Pull request by daswer123**
Hi, I was impressed with the quality of [XTTSv2](https://www.reddit.com/r/LocalLLaMA/comments/17yzr6l/coquiai_ttsv2_is_so_cool/) and decided to make an implementation for SillyTavern.

To do this, I developed a [FastAPI server](https://github.com/daswer123/xtts-api-server), which looks a lot like [silero-api-server](https://github.com/ouoertheo/silero-api-server)

To make this TTS work you need to install [xtts-api-server](https://github.com/daswer123/xtts-api-server) and put samples from 3 to 9 seconds in the speakers folder or the one you specify, more details [here](https://github.com/kanttouchthis/text_generation_webui_xtts/issues/3#issuecomment-1818040210).

Many things I emphasized from the implementation of silero and  [silero-api-server](https://github.com/ouoertheo/silero-api-server) 

Feel free to make any changes or suggestions, would be glad to improve this project )

A little demonstration (turn on sound, sorry for the mess in the video) 

https://github.com/SillyTavern/SillyTavern/assets/22278673/a235b7b3-8082-4a30-bd66-4dd2cce1e63a

### CODE REVIEW

**Comment by Cohee1207** [comment]
Tested and confirmed works, thanks.

**Comment by aziib** [comment]
combine this with rvc and boom, the quality will be even better.

**Comment by VertexMachine** [comment]
Great job @daswer123 ! I haven't test this one yet, but did some test in oobabooga. And my impression is that the voice quality is way higher in what I got there compared to what you show in the attached video. Just FYI.

**Comment by daswer123** [comment]
> Great job @daswer123 ! I haven't test this one yet, but did some test in oobabooga. And my impression is that the voice quality is way higher in what I got there compared to what you show in the attached video. Just FYI.

I think it's mostly because I didn't prepare the sample.
Also, the sample was in a different language, which I think also affected the result.

But thanks for the tip, I'll see what's there and if there are better settings I'll try to transfer them to the repo.

**Comment by daswer123** [comment]
This may be useful to someone: helpful notes from user Material1276 for improving voice cloning
[here](https://www.reddit.com/r/Oobabooga/comments/1807tsl/comment/ka5l8w9/?share_id=_5hh4KJTXrEOSP0hR0hCK&utm_content=2&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1).

**Comment by Kaiten10** [comment]
Is there a way to access the server through LAN? Like the --listen arg for ST Extras.

Awesome work btw!  IMO it works best when used as the "intonation/emotion" base sound, and top it off with a high quality RVC to get it sounding crisp and realistic. So far RVC only adds <1s to the generation on my 3060, so it's worth it. Thanks!

**Comment by daswer123** [comment]
Yes, you just need to add the `-hs 0.0.0.0` flag ( similar to -listen )

**Pull request merged**
