### PR TITLE
Chat without character selected

### PR DESCRIPTION
**Pull request by Cohee1207**
Assistant mode / AMA mode / quick chat mode, however you want to call it.

Type anything on a welcome screen to access a temporary chat space.

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Review by Wolfsblvt — CHANGES_REQUESTED** [review]
Generally like the idea. Works good enough, and is nice for a quick chat.
Especially like it that World Info is loaded, and with System Prompt you can still get a specific vibe going. You can test your settings, without any actual char present.

I am not sure if it wouldn't be a nice idea to at least *somewhat* save it. I know you don't want to hook it into the actual chat file save. But just to prevent loss on a reload, why not dump the chat history into local storage? So it can get reloaded as long as you stay in that chat?

Also, the important part.

### Small issues and feedback that should be solved.

#### 1. Strange visible HTML
Being in an active chat, and exiting out via "Close Chat" in the burger menu leads to wrong HTML formatting.
image

#### 2. More Strange visible HTML
When I did send my first message, on a now reloaded empty chat, same formatting issue appeared.
image

#### 3. Message Buttons not Working
Most of the message buttons don't work. Edit is the worst offender, that might be useful. Copy doesn't work, hide doesn't work. Brach and Checkpoint will outright throw an unhandled exception.
image

I'd suggest hide the buttons that don't make sense for this ephemeral chat (branch, checkpoint) and we should fix the others.

#### 4. Chat Saving Warning
Still tries to save chat. So it'll always log the warning in console. Might be small, but warnings for expected behavior is a bit weird.
Maybe prevent the save here if we are in this type of chat, but without any logging.
image

**Comment by Cohee1207** [comment]
@Wolfsblvt 

1, 2 - done, was HTML tags encoding issue. I also renamed it to SillyTavern Assistant not to break tags encoding for every character named Assistant.
3 - done, buttons should now be functional or toast if not.
4 - done.

**Comment by Cohee1207** [comment]
~~It also makes the chat a little bit more "flavored" on default prompts. But this is to be expected.~~

image

**Comment by Cohee1207** [comment]
Reverted. It's back to plain Assistant.

**Review by Wolfsblvt — APPROVED** [review]
Nice. I can even preview/maximize the ST default avatar. So useful.

The PR is good, I think that works well. Couldn't find anything else.
Even Close Chat and New Chat from the burger menu works well, like you'd expect.

Last thing would be thinking if there is any chance to save the chat history, at least as long as you don't switch to a character. But I'd say we can think about that after this, if even. The PR itself is good.

**Pull request merged**
