### PR TITLE
Implement failsafe for world creation with same name

### LINKED ISSUE #2297: [BUG] World/Lorebook will be overwritten if user creates a new lorebook with identical name
### Environment

🪟 Windows

### System

N/A

### Version

1.12.0 'staging' (863e0c36)

### Desktop Information

_No response_

### Describe the problem

Lorebook will be overwritten if user creates a new lorebook with identical name.

Steps to reproduce:

1. Copy the name of lorebook to be overwritten, In this case, "Kisna-WI"
image

2. Create a new World Info with that name.
image

3. All entries were overwritten with blank.
image

### Additional info

_No response_

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Wolfsblvt**
- Fixes #2297
- Added another utils function for string comparison

The button for new world uses an interactive dialog where you can overwrite the world if you want to. All other calls (like slash command world creation) will just show a warning and cancel.

### CODE REVIEW

**Comment by LenAnderson** [comment]
Does this apply to importing WI as well? Because IIRC the import process also silently overwrites what's already there.

**Comment by Wolfsblvt** [comment]
No. That one uses a different function and a different API endpoint.  
But it makes sense. I'll see that I can utilize the same checks inside there.

**Comment by Wolfsblvt** [comment]
Implemented the same check for WI imports.

Also note that both checks utilize the "similar names "functionality" where it strips accents and ignores casing. Even if they *might* resolve to different filenames in the system, I think it makes sense to do this.

Worlds named `Touché` and `touche` can be treated as *same name*.
I think this would also make sense for character creation, tbh...

**Comment by Wolfsblvt** [comment]
Okay fuck it, let me do the same with characters. I feel like it makes sense to have the same logic applied there.
For cases where you want to *update* the existing characters with the same name, you can still click "Yes" on the dialog.

Lemme draft this until I finish implementing it.

**Pull request merged**
