### PR TITLE
join chatlog with `\x01`

### PR DESCRIPTION
**Pull request by steve02081504**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

See the chat history on discord, this will provide convenience for matching only one message.
Now we can use `\x01{{user}}:[^\x01]*key` to match content

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
I have to check if that's all places and check some edge cases. But I have no objections, generally. Neat idea that doesn't hurt much and can help regex matching.

**Comment by Cohee1207** [comment]
This (at the very least) should be documented.

**Comment by steve02081504** [comment]
> This (at the very least) should be documented.

ready to do this but leme know which proj and file I should add it to?

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern-Docs

**Comment by steve02081504** [comment]
> [SillyTavern/SillyTavern-Docs](https://github.com/SillyTavern/SillyTavern-Docs)

done in https://github.com/SillyTavern/SillyTavern-Docs/pull/99

**Pull request merged**
