### PR TITLE
Throttle chat backups

### LINKED ISSUE #2861: [FEATURE_REQUEST] Mechanism for saveChat to not trigger chat backup in some cases
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

The backups folder gets spammed with a lot of, in my opinion, unnecessary backups.

Swipes in particular. I don't believe chat swipes should cause a backup – all the data is still there except the swipe ID is just different.

Auto-save Message Edits is a case where there is data loss, but the frequency is even greater than changing swipes. I'm thinking maybe it should trigger backups but maybe should have a far longer debounce?

I took a look at `saveChatDebounced` and there is code for making sure the chat ID hasn't changed before triggering a save. If changing chats does trigger a save, then I feel this timer can be made much longer in addition to making swipes no longer cause backups.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

### PR DESCRIPTION
**Pull request by Cohee1207**
Closes #2861

Don't call backup saves more than once per 10 seconds (number debatable) for every user. Exiting the process would write all pending backups.

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Review by Wolfsblvt — COMMENTED** [review]
> once per 10 seconds (number debatable) 

I know you likely don't wanna overcrowd it, but why not just make this a yaml parameter that you can set, in addition to enabling backups?

Generally think the idea is good. No bother trying to decide what backups are *right* and which are *wrong.

**Comment by Cohee1207** [comment]
> I know you likely don't wanna overcrowd it, but why not just make this a yaml parameter that you can set, in addition to enabling backups?

I can't see anyone purposefully changing it. A sane default that would work for 99% is enough.

**Comment by Succubyss** [comment]
> > I know you likely don't wanna overcrowd it, but why not just make this a yaml parameter that you can set, in addition to enabling backups?
> 
> I can't see anyone purposefully changing it. A sane default that would work for 99% is enough.

i would like to echo @Wolfsblvt's suggestion.  I turn on compression for the backups directory and the write operation for it can be pretty expensive in terms of disk activity. I would personally want to set it to 60 seconds or so.

**Comment by Cohee1207** [comment]
>  I would personally want to set it to 60 seconds or so.

**Pull request merged**
