### PR TITLE
Dreamgen help link

### PR DESCRIPTION
**Pull request by DreamGenX**

### CODE REVIEW

**Comment by Cohee1207** [comment]
Why a weird redirect page if you can just do a direct link?
https://docs.sillytavern.app/usage/api-connections/dreamgen/

**Comment by DreamGenX** [comment]
Just wanted flexibility to change the link if needed. If you strongly prefer to link directly to the guide, that's also fine, I can update it.

**Comment by Cohee1207** [comment]
I'd take an ST docs link

**Comment by DreamGenX** [comment]
Done! You are the boss :D

**Pull request merged**
