### PR TITLE
Fix syntax highlight editor

### LINKED ISSUE #2285: [BUG] Full screen STscript editor is unusable (Quick Reply)
### Environment

🐧 Linux

### System

Various browsers, Manjaro current.

### Version

SillyTavern1.12.0 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Various
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

When I try to edit scripts, I got these problems in the full screen script editor (after button with vertical ... ).

In Firefox: I can't edit scripts body at all - text area field with them is disabled to RO state. Don't allow to put cursor in it.

In Vivaldi, Chromium: Cursor don't represent actual place where next typed letter will be put. It always like several letters back from cursor - if cursor and actual font has different widths for the every letter and maybe spaces changed for tabulations for cursor. Mouse become useless completely (can't be guessed where will be next letter for the cursor position), with keyboard arrows still possible to make blind entering position change by counting letters on pressing arrows.

I guessing it's strongly related to the interactive syntax help pop-ups, as they also make cursor jump around the string when they appears.

### Additional info

No error logs, on screenshot it's not exactly visible. Maybe I can make some videos later (don't has any video screencap software right now.)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by LenAnderson**
Looks like fonts for the textarea and pre/code were not explicitly assigned, causing font-misalignment only in some browsers.

- Add Noto Sans Mono as default monospace font across all of ST.
- Explicitly assign font family for the textarea and the pre/code doing the highlighted display.
- Fix ::selection style of the textarea to prevent weird colors and textarea text bleeding through.

(possibly more to come, like a setting to disable syntax highlight)

### CODE REVIEW

**Comment by Cohee1207** [comment]
Maybe it's just me, but I feel just the latin typeface for this font might not be enough to cover all supported languages

**Comment by LenAnderson** [comment]
Yes, I'm probably going to have to add the rest of them as well.

**Comment by Cohee1207** [comment]
@LenAnderson how close is this to ready?

**Comment by LenAnderson** [comment]
Still some more Firefox weirdness to address. But I don't think I'll have time for that this week.


________________________________

**Comment by LenAnderson** [comment]
I think that should make it work for a **current** Firefox. No guarantees for old versions (that should not be used anyways).

**Comment by Cohee1207** [comment]
Squashed to prevent old font files from dangling in the git index.

**Pull request merged**
