### PR TITLE
add missing session handling to SileroTTS

### PR DESCRIPTION
**Pull request by smirgol**
I had the issue that for me and the recent version of SileroTTS I would receive the following error when trying to generate a TTS:
```
"POST /tts/generate HTTP/1.1" 422 Unprocessable Entity
```
This was due to a missing `session` parameter in the request. Not sure when this was added, but without, the request won't work. 

I've monkey-wrenched some code to the `silerotts.js` that will establish a session with the name of `sillytavern` and send that along with each `generate` request, which solves the issue for me.

I've added a check against a `404` in the request to establish a session, so users that might run on older versions of SileroTTS, where this session thing might not exist, won't be affected when throwing an Exception.

### CODE REVIEW

**Comment by Cohee1207** [comment]
I haven't found any mentions of "tts/init_session" endpoint in either extras or silero API server. 
The endpoint "tts/session" exists in API server package, but I'm not aware of it being the requirement. What's the version of Silero that forces you to use that?
https://github.com/ouoertheo/silero-api-server/blob/master/silero_api_server/server.py#L88

**Comment by smirgol** [comment]
Actually a good question. I spent a lot of hours yesterday to make all the stuff work and actually can't remember any more what I precisely did when and where. But it looks like I have at least two differing installations of SileroTTS, one cloned from master and one installed with probably conda or pip something like that.

What they both have in common, though, is that they refuse to generate output without initializing the session path and sending that along with the generate request. But the endpoint differs, for one its `/tts/session` for the other one `/tts/init_session`.

Not sure if this patch is of any help then, but it's been an issue for me and I thought I might share my fix.

**Comment by Cohee1207** [comment]
Could you link a git repo you cloned SileroTTS from?

**Comment by smirgol** [comment]
It's the one linked on the SillyTavern Extras page: https://github.com/ouoertheo/silero-api-server.git

But I think I've got completely lost between conda, pip and the cloned installation. Sometimes python confuses the heck out of me with all these venvs and different versions. :|

What I'm actually running is version 0.3.0 from my conda (module `silero-api-server`), and looking at the code inside, I have no idea where in the code this issue is triggered for me and why. It all looks like the parameter session is purely optional, but nonetheless I get that error when I omit it. This is the full response, it that helps:
```
{
  "detail": [
    {
      "type": "missing",
      "loc": [
        "body",
        "session"
      ],
      "msg": "Field required",
      "input": {
        "speaker": "string",
        "text": "string"
      },
      "url": "https://errors.pydantic.dev/2.4/v/missing"
    }
  ]
}
```

Feel free to close this PR, I probably mixed up something badly on my side, otherwise other people would already have complained, don't now. :)

**Comment by Cohee1207** [comment]
I'll leave it open for now and will look into it closer if I get more reports. Thanks for your time.

**Comment by Hashnoob** [comment]
Having the same issue after a fresh install of everything today.

https://github.com/ouoertheo/silero-api-server

Checked: Enabled, Auto Generation
URL: http://localhost:8001/tts

Regardless of settings and voice selection:
"POST /tts/generate HTTP/1.1" 422 Unprocessable Entity

INFO     | silero_api_server.tts:__init__:33 - TTS Service loaded successfully
INFO     | silero_api_server.tts:list_languages:147 - Loading cached language index
INFO:     Started server process [44136]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:58046 - "POST /tts/generate HTTP/1.1" 422 Unprocessable Entity

**Comment by Cohee1207** [comment]
@Hashnoob @smirgol 
Merged to staging (with a little workaround for using Silero with Extras). Please check now

**Comment by smirgol** [comment]
Seems to work for me, thank you :)

**Pull request merged**
