### PR TITLE
Add a token counting endpoint for vLLM

### PR DESCRIPTION
**Pull request by sasha0552**
Related: vllm-project/vllm#5054

### CODE REVIEW

**Comment by Cohee1207** [comment]
Looks good, but let's wait for inclusion of this into vLLM's official release before merging, since this would cause tokenization errors for those who don't use a trunk version of vLLM (I think it's a majority). Please ping me when the vLLM release is happening.

**Comment by sasha0552** [comment]
The vLLM release is in two or three days (vllm-project/vllm#5806). I wonder if this can be merged before the SillyTavern release, because I'm assuming the SillyTavern release is coming soon too.

**Comment by Cohee1207** [comment]
@sasha0552 I plan to release shortly. Ofc this can be merged, but the point is that those who update would have to experience tokenizer errors if they have the "Best match" option selected while using vLLM backend.

**Comment by sasha0552** [comment]
@Cohee1207 vLLM 0.5.1 has been released.
https://github.com/vllm-project/vllm/releases/tag/v0.5.1

**Review by Cohee1207 — APPROVED** [review]
Thanks. Tested with the latest version of vLLM and confirmed working.

**Pull request merged**
