### PR TITLE
Optimized zh-cn translation

### PR DESCRIPTION
**Pull request by Tosd0**
## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

# Overview
- Optimized and localized zh-cn translation for better understanding.
- Supplemented translation using the i18n tool and sorted keys

### CODE REVIEW

**Comment by Tosd0** [comment]
Additionally, I noticed some translations are not included in the .json file. How should I translate these? 
Should I simply add lines like
`“Original text”: “Translated text”`?

**Comment by RivelleDays** [comment]
> Additionally, I noticed some translations are not included in the .json file. How should I translate these?
Should I simply add lines like `“Original text”: “Translated text”`?

你可以查看 SillyTavern 官方文檔網站中，針對翻譯的說明：[Internationalization (i18n)](https://docs.sillytavern.app/for-contributors/i18n/)。

基本上，就是在本地安裝 [SillyTavern-i18n](https://github.com/SillyTavern/SillyTavern-i18n) 工具並更新翻譯文件。我強烈你進行人工校對，不要直接使用 google 翻譯（簡中版目前有些地方照上下文來看很奇怪），可以使用 LLM 進行輔助並進行本地測試。我最近針對 zh-tw 進行了更新，你可以進行參考，有缺失還可以直接貼過去（但請選擇 staging 分支的版本，穩定版本暫時還未更新）。有的時候使用 i18n 也會遺漏一些東西⋯這是正常的。

- - -

You can refer to the SillyTavern official documentation website for translation guidelines under "Internationalization (i18n)."

Essentially, it involves installing the SillyTavern-i18n tool locally and updating the translation files. I strongly recommend manually proofreading the translations instead of relying solely on Google Translate (some parts of the Simplified Chinese version seem odd in context). You can use LLMs to assist and conduct local testing.

I recently updated the zh-tw version, which you can reference. If you find any missing entries, feel free to copy them over—but make sure to use the zh-tw file from the staging branch, as the stable version hasn’t been synced yet.

Sometimes, i18n might miss a few things, which is perfectly normal.

**Comment by Tosd0** [comment]
> 基本上，就是在本地安裝 [SillyTavern-i18n](https://github.com/SillyTavern/SillyTavern-i18n) 工具並更新翻譯文件。我強烈你進行人工校對，不要直接使用 google 翻譯（簡中版目前有些地方照上下文來看很奇怪），可以使用 LLM 進行輔助並進行本地測試。

明白了！之前没看到文档里 i18n 相关的说明，是参考了你的 PR 里的文件修改历史记录，以为直接改 json 文件就可以。（笑）
等我回家会用i18n工具重新过一遍的。谢谢提醒！
~~其实我还蛮好奇简体中文机翻的地方这么多竟然没人改~~

---

Got it! I didn’t notice the i18n-related instructions in the documentation earlier. I referred to the file modification history in your PR and assumed that directly editing the JSON files would suffice. XD

I’ll go through it again using the i18n tool once I’m back home. Thanks for the reminder!

~~Btw, I’m quite curious why no one has fixed so many of the machine-translated parts in Simplified Chinese.~~

**Comment by Tosd0** [comment]
Sorry but I think some revision is needed for a better translation. Would you mind reopening it and review some pending changes above? Thanks :) @Cohee1207

**Comment by Cohee1207** [comment]
These changes are already merged.

**Comment by Tosd0** [comment]
> These changes are already merged.

Then should I reopen another pull request about determining the controversial translation? You can go through the review above and discuss about it.

**Comment by Cohee1207** [comment]
> Then should I reopen another pull request about determining the controversial translation?

Yes.

> You can go through the review above and discuss about it.

There's a limited number of things I can do since I can't read in Chinese. Just lmk when it's ready.

**Comment by Tosd0** [comment]
> There's a limited number of things I can do since I can't read in Chinese. Just lmk when it's ready.

There’s no need to read the translation, since all reviews above stem from the lack of context. I’ll list them below.
1. Single-row message input area. Mobile only, no effect on PC
I tested this setting on my end, but the description doesn’t seem to match its actual functionality.
I would like to double check the meaning of this setting for an accurate translation.
Does this setting mean that, when using a mobile device, the input area should be limited to a maximum of one line?
However, after enabling this option, I noticed that the input area can still expand to two or more lines.

2. Ephemerality
I don’t quite understand what this(Ephemerality) means in this context, as I don’t use macros often. An explanation on this term is appreciated.

3. Filter to Characters or Tags
I don’t fully understand the function of this option either. I referred to the original translation, but it translated the word filter into 应用, which means apply in English. I used 应用 as well. Is this okay? What does this option really means?

Thank you for your information. I’ll open another PR when the above translation is clear.

**Comment by RivelleDays** [comment]
> 1.	Single-row message input area. Mobile only, no effect on PC

它實際上是讓手機和移動端的聊天訊息輸入欄位的元素（圖示等）預設單行顯示。
It actually sets the chat message input field on mobile devices to display as a single row by default.

> 3.	Filter to Characters or Tags

這個部分實際上出現在「世界資訊」編輯條目的下方，他是用來篩選特定角色或是標籤的。我想使用中文的「排除」或「過濾」都會很怪，因為該功能實際上也包括讓特定角色看到該條目。在中文語境下使用「篩選」可能比較合理。

This section appears below the “World Info” edit entries and is used to filter specific characters or tags. I think using “排除” or “過濾” in Chinese would feel awkward since the functionality also includes allowing specific characters to view the entry. Using “篩選” might be more appropriate in the Chinese context.

- - -

如果你對你的翻譯不滿意但PR已經合併，重新提交即可。目前多數人常用的穩定版尚未更新，你永遠都有時間處理！
If you’re not satisfied with your translation but the PR has already been merged, you can always submit a new one. The stable version most people use hasn’t been updated yet, so there’s always time to make adjustments!

**Comment by Cohee1207** [comment]
> I don’t quite understand what this(Ephemerality) means in this context, as I don’t use macros often. An explanation on this term is appreciated.

Ephemeral is a funky way of saying about something that is not lasting permanently. Ephemeral in regex context means they only reflect on display or prompt, without actually affecting the saved data. You can use a word equivalent to "temporary changes".

**Pull request merged**
