### PR TITLE
Add `debugging` field for WIs to log only few entries if needed.

### PR DESCRIPTION
**Pull request by steve02081504**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

_____

My WI book has nearly 220 entries & 7300 keys. This was extremely difficult when I was debugging it.
I hope to add this function so that when writing complex WIbooks, only the required entries can be selected and entered into the log, thereby reducing the reading burden when reading the log for debugging needs.
图片
图片

### CODE REVIEW

**Comment by Cohee1207** [comment]
This should not be a part of the entry. Only functional fields should be added to entry template.

**Comment by steve02081504** [comment]
> This should not be a part of the entry. Only functional fields should be added to entry template.

I can't think of a better place to put these infos....

**Comment by Cohee1207** [comment]
Do it in an extension. This is not an issue that concerns 99.9% of the users and not warrants a new fields.

**Comment by Wolfsblvt** [comment]
I mean, if you don't want the logging, don't enable verbose logging in your dev tools?
Logging is always optional.

**Comment by steve02081504** [comment]
> I mean, if you don't want the logging, don't enable verbose logging in your dev tools? Logging is always optional.

I just want to focus on whether a few specific entries are activated (and why). Then other items will be a trouble.

**Pull request closed without merging**
