### PR TITLE
Update world-info.js to allow use note marco as key

### PR DESCRIPTION
**Pull request by steve02081504**
This will allow for some pretty cool chicanery...

### CODE REVIEW

**Comment by Cohee1207** [comment]
What exactly is this for? Any usage examples?

**Comment by steve02081504** [comment]
> What exactly is this for? Any usage examples?

In this way you can create "logical nodes" and combine conditions by recursive to create WIs with more complex conditions, or reuse lists of keywords, without affecting the output.
Let's say we create a WI that is triggered only when `a` is matched and there is no `b`, and the content is `{{//node a}}`
Then let's create another WI that only triggers on a match to `{{//node a}}` with any `c`.
The second WI now then combines multiple conditions.

e.g. https://github.com/steve02081504/GentianAphrodite/commit/22ef7c633da766e8d5ee8b88ef7adf070d12efac

**Comment by Cohee1207** [comment]
Let's consult with subject matter experts. 
@Wolfsblvt thoughts?

**Comment by Wolfsblvt** [comment]
Hmmmh. Why would you have a fallback for a `substituteParams` call? That call will always replace macros, and if there are no macros, does nothing. If it replaces all macros and resolves to an empty string, that is **expected**, and it doesn't really make sense to return the raw macro then.
Either a content field resolves macros or it doesn't at all, I would say.

I can see use-cases for chaining WI after each other, but I am not very happy with doing it this way. That is kinda against what macros stand for.  
A macro comment like `{{//node a}}` is just meant to be a node inside a test block for you to read, it shouldn't really be used to match anything.

If you don't want to utilize hidden strings like HMTL comments (`<!-- YOUR_TRIGGER -->`) because you don't want the model to see the trigger words, then maybe we should find another way to allow this.  
Let me think a bit on that.

**Comment by steve02081504** [comment]
1. this little trick hardly affects any backward compatibility issues, which is why it must **only** work when the content is all note marco.
2. i know this isn't what note marco itself was designed to do, but i think this is the fastest way to implement it.
Ideally I'd like to be able to customise the js code myself, embed it in a png and have it run in a js sandbox to generate the prompt or process the generated results before displaying them, but that would require a lot of extra development and discussion.
This approach is super simple and effective way to help us use world infos better and requires only a little bit of code changes and almost no backward compatibility issues.

**Comment by LenAnderson** [comment]
`{{//...}}` is supposed to be replaced with nothing and have no effects on anything. It suddenly triggering WI is going to cause problems. Even if this only takes effect on otherwise empty entries, I guarantee there's going to be users out there that have a bunch of entries with nothing but a note in their content. Whether to trigger QRs, do some inclusion group stuff, or whatever else they can come up with.

`{{//...}}` isn't the only macro that gets replaced with nothing. `{{setvar}}` is another one. That would now also trigger WI. Using WI to update vars seems like something people would do.

**Comment by Wolfsblvt** [comment]
Yup, this has too many side effects that will be risky and don't make much sense.

We are already brainstorming different alternatives on how this could be achievable. As I feel like the basic feature request behind this does make sense and we should find a way to do it.  
Just not with this code.

**Comment by steve02081504** [comment]
How about only falling back if the triggered entry is less than 32 in length and starts with `{{//`?

**Comment by Wolfsblvt** [comment]
That's so freaking hacky. Make it an extension then, or just for your own local code.

If not, let us cook. As I said, we are already discussing possible options for this.

**Comment by steve02081504** [comment]
ok then..

**Pull request closed without merging**
