### PR TITLE
Objective: currentTask fix in MESSAGE_RECEIVED, ignore swipes

### PR DESCRIPTION
**Pull request by ouoertheo**
What's in the PR?
* Ignore swiped messages for Objective task check
* Fix for task check logic for currentTask in MESSAGE_RECEIVED

### CODE REVIEW

**Comment by Cohee1207** [comment]
Maybe it makes sense to reset `lastMessageWasSwipe` to `false` on switching chats?

**Comment by ouoertheo** [comment]
Sure, easy enough. Did you have a specific case you were thinking of that this might fail? Like if something broke between swipe and message receive?

**Comment by Cohee1207** [comment]
Just to make sure that the state is properly refreshed to initial when switching.

**Comment by ouoertheo** [comment]
Ok, added it to the resetState() function which is called on chat change. Thanks for the recommendation

**Pull request merged**
