### PR TITLE
`/if` and `/while` now allow "right" and "rule" to be optional

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Main reason for this PR was that writing an if-statement in STscript is always really verbose.
You always need a comparison rule, and most of the time it's gonna be "eq" anyway, so it makes sense to set this as the new default now.

### Changes
- Leave out `rule=` if the rule is supposed to be "equals" anyway
- **Shorthand truthy check** - if no right operand was provided
  - It'll check whether the left operand is truthy (both checking `isTrueBoolen`/`isFalseBoolean` and then doing the JS truthy check.
  - Allowed rules are no specified rule, or `not`, which will negate it. All other rules throw an error.
- No right operand provided now correctly throws for all other rules besides the two explained above
- Don't treat empty string values as number `0` anymore
- If rule is `in` or `nin`, providing two strings that could be numbers now correctly falls through to string comparison. (12345 includes 45, right?)
- Restructured the code to be more streamlined with the different accepted rules, for the different provided operands, and throw appropriate errors
- Updated slash command documentation to reflect all changes

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

**Comment by Cohee1207** [comment]
> Don't treat empty string values as number 0 anymore

That bit makes me uncomfortable.

**Comment by Wolfsblvt** [comment]
Why? I think the behavior felt quite wrong, that empty string resolves to numerical and then actually has content.

I have to make tests, but that could lead to false results when doing something like "in" checks with or against empty strings.

**Comment by Cohee1207** [comment]
There is a non-zero chance of someone using this unintended bug as a feature.

**Comment by Wolfsblvt** [comment]
Is that a good reason to not fix this then?
Unintended features are one thing, obvious bugs are a different thing, in my eyes.

**Comment by Cohee1207** [comment]
Please prepare a test set with before/after results. In any case this appears as a breaking change that would need to be properly communicated. Also let's see if any docs require updating.

**Comment by Succubyss** [comment]
> There is a non-zero chance of someone using this unintended bug as a feature.

I was worried this would break my use of turning non-numbers into 0 with `/abs` but that's still intact.

Though I have to ask why make the "resolve to 0" thing part of this PR.

It should probably be a separate PR because this would otherwise be an easy merge.

**Comment by Wolfsblvt** [comment]
> Though I have to ask why make the "resolve to 0" thing part of this PR.

Because it was a bug (even if unintended and might be (ab)used), and without this change, I am not able to make this PR. an undefined right value cannot be passed into the eval function as an empty string, or I have no way of checking that it was actually undefined, and not explicitly set or resolved to empty.

@Cohee1207 I'll work on the test suite.

**Comment by Succubyss** [comment]
I wrote a script to test a ton of different left+right combos and didn't have any issues. Assuming Wolf is done with his left OR right testing, this should be ready to merge.

**Review by Cohee1207 — APPROVED** [review]
I trust you both that this is well tested. YOLO

**Comment by Wolfsblvt** [comment]
All test cases @Succubyss and I could think of are green. We tested some weird quirks from before.
I updated the docs so it's much clearer now what you can do and how it works.

So yeah :D

**Pull request merged**
