### PR TITLE
Content editable Advanced Formatting panel

### PR DESCRIPTION
**Pull request by Cohee1207**
## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Review by Wolfsblvt — COMMENTED** [review]
Feedback

### 1. Header/Category with Buttons
I am currently debating whether I like the new choice how to place those buttons. It works. But also looks weird on a wide screen, where the dropdown is soooo wide.
Still, would be okay, but I'd say we should be somewhat consistent through the app then. CC has different style. Theme in Settings also uses the old one. And likely a few more. You want to switch all of them over?
image 
image

### 2. Toggles Inside Header
Big fan of those new toggle placements. We need more of that.
image

### 3. Activation Regex Placement
Was it a conscious choice to place activation regex below the system prompt?
The system prompt can potentially be veeery long. I agree with placing all the others below and moving them out of view, that's okay. But this one could be bothersome. As it's directly tied to the preset selected in the dropdown above. And it's more like a global/activation setting anyway, than part of what combines to the content of the instruct preset. I'd move it above again.
image

### 4. Distinction of Categories
I personally know that the Tokenizer settings and the Custom Stopping Strings aren't part of the context and instruct preset, respective.
I can see the small separation line - but with the new layout I can see many people being confused and expecting this to be part of the Context and Instruct.
Maybe it's time to make a more visual separation and make sure to show this is a new category.
Should be possible to just mark them as a `standoutHeader`, so they visually look like a completely new category. That's what I'd do.
image

### 5. Instruct Sequences Relation
I can see the idea behind having the instruct sequences moved to their own column. Makes the layout much more evenly, so it's good. But now it's a bit harder to visually grasp that they still belong to the Instruct Template, and get changed and saved based on that dropdown.
Suggestion is pretty easy, add the same small remark to the header that Context Formatting already has.
I think it's okay to keep it as a `standoutHeader`, just the same formatted remark inside.
image
image

### 6. Moving Auto-Continue
Me likey. Long overdue, makes complete sense.

### 7. `contenteditable` Textboxes
Haven't encountered any issues with them so far. Still have a slight bad gut feeling about mobile users, but oh well....
They work consistently well and better than the textareas we had before. Performance feels better. So I can get behind that.

### 8. 🐛 🔴 BUG: Weirdly sized empty input area
image
Steps to reproduce:
- Select an instruct template that has disabled contenteditable fields.
  Like Mistral, which has "System same as User".
  The fields need to be empty too.
- Let the settings save, then reload page. Now the input boxes are tiny, as they have no content, and likely no min height.
- Now switch to a preset that has those boxes enabled. If it also had the input empty, the box, even if now enabled, will stay that tiny size.

### 9. Overall New Layout
Generally big fan of the new layout. That's improvements to the overfilled drawers I wanna see. Yay.

**Comment by RossAscends** [comment]
1. Not sure what the suggestion is. Super wide selectors is a problem we have app-wide. the AF panel being 3 columns should prevent them from being as large as, say, anything on the API selection panel. Moving the icons to their own line prevents the selector from being too small, even on mobile screens. 

2. Just need to clean it up and make them toggle-able divs, not checkbox labels. Should do this before merging it properly.

3. Noted. Fixed. 

4. Yes those two items are not part of either templates, but they exist on the panel because they...don't really have a better home. I can see the tokenizer selector living inside the API panel (might be some work to make it display intelligently when it's applicable), but custom stop strings really can't go anywhere else imo. 

5. Fixed. it's a tight fit, but no more tight than the "Context Formatting" header. Also, the sequences being saved in the template is visually hinted at by the sequences changing when you switch templates. The new layout makes sequences always visible, so it's more obvious than before. 

8. Oof good catch. Not sure what would cause that. Will investigate.

**Comment by Wolfsblvt** [comment]
> Not sure what the suggestion is.

Suggestion is if this is the new design we want to go for presets with dropdown and several buttons, we should change the other places soon too.
I don't like it if you have three different places that do the same functionally, but all look different in layout.

> Yes those two items are not part of either templates, but they exist on the panel because they...don't really have a better home. I can see the tokenizer selector living inside the API panel (might be some work to make it display intelligently when it's applicable), but custom stop strings really can't go anywhere else imo.

The placement is okay, I wouldn't move them. You are right, there is no other place where they would fit.
I am just suggesting both blocks having a `standoutHeader` format too, so it visually looks like this is a new, different block. And not just some sub settings of the context or instruct column.

**Comment by RossAscends** [comment]
ok.
- styled the tokenizer/stop sequences headers
- turned the checkbox labels into buttons

I'm happy with how it is now. @Cohee1207 please give final review.

**Comment by Cohee1207** [comment]
LGTM. Any more issues could be fixed post-merge.

**Pull request merged**
