### PR TITLE
Built-in variables

### PR DESCRIPTION
**Pull request by IkariDevGIT**
i know this is already an extension, but the extension is kinda.. limited. I did add some things, and i wanna add a bunch of new things, and thats only possible with directly modifing script.js(as far as i know). Im probably gonna add some commands that are related to this btw(a command that has output = goes directly into a new variable). WIP btw

TODO
- [ ] Convert to extension
- [ ] Change how | command chaining works(one after another, maybe it already works like this.. need to investigate)
- [ ] Add something like {{create-var:...}}}

### CODE REVIEW

**Comment by IkariDevGIT** [comment]
Also, if its about maintaining it easy, i can convert it into a built in extension(some script.js modifications will be necessary tho) if you want(i really think this should be built in, you can do so many cool things with it). Just let me know if you do! And if you wanna ask why not just use the extension you made, because of the reasons i already listed, and your design is kinda flawed/unoptimal.

**Comment by Cohee1207** [comment]
> i can convert it into a built in extension

That would be nice.

> and your design is kinda flawed/unoptimal.

I take "Design" into triple quotes because the plugin was meant to be an example for handlebars usage, not a real useful thing.

**Comment by IkariDevGIT** [comment]
> > i can convert it into a built in extension
> 
> That would be nice.

Ok nice, im gonna change some stuff and then try to change as much into an extension!

> > and your design is kinda flawed/unoptimal.
> 
> I take "Design" into triple quotes because the plugin was meant to be an example for handlebars usage, not a real useful thing.

I think if implemented nicely this feature could be really nice.

So one question, do you think this deserves being merged(not now, i mean as a feature itself)(first time really contributing to a project btw)?

**Comment by Cohee1207** [comment]
Risu has this in place for quite some time, so why not

https://github.com/kwaroran/RisuAI/wiki/Curly-Brased-Syntaxes#variables

**Comment by IkariDevGIT** [comment]
@Cohee1207 im sorry for asking for help on this, but how is command batching handled(this /sendas kek kek|/continue)?
Are they all executed right after another, or is there some sort of "wait for the first command to finish"?

**Comment by Cohee1207** [comment]
No wait, just executing one by one

**Comment by IkariDevGIT** [comment]
> No wait, just executing one by one

hmm okay, i think it would really benefit this sort of "scripting" inside of ST if they were executed with a wait.

**Comment by Cohee1207** [comment]
Well, it waits if the operation is sync, but async are not awaited

**Comment by IkariDevGIT** [comment]
well thats weird then, it should wait until done generating(ill push an update in like 10 minutes where i made it into an extension(kinda) and added a raw_generate command), thing is.. its not async(i think, please correct if im wrong)

**Comment by IkariDevGIT** [comment]
> Well, it waits if the operation is sync, but async are not awaited

ok so thing is updated, please let me know what im doing wrong 😄

**Pull request closed without merging**
