### PR TITLE
Protect eyes from being blinded when loading pages

### PR DESCRIPTION
**Pull request by steve02081504**
When I use Firefox with SillyTavern, it always loads a white background page first, causing serious damage to my eyes.
This PR fixes that.

### CODE REVIEW

**Comment by Cohee1207** [comment]
I added a preload for style. Does it solve your problem?
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

**Comment by steve02081504** [comment]
> I added a preload for style. Does it solve your problem? 

Thank you for your kind help!
But in my tests the page still all white for a short period of time before it finishes loading.

**Comment by Cohee1207** [comment]
My Firefox does not do that in repeated testing. And I'm against the body style attribute since it overwrites the stylesheet color.

**Comment by steve02081504** [comment]
> My Firefox does not do that in repeated testing. And I'm against the body style attribute since it overwrites the stylesheet color.

works now, ty!
Maybe the diff between us is that Im using Firefox Dev edition. Anyway, thank you for solving this problem.

**Pull request closed without merging**
