### PR TITLE
The popular mirostat "Gold/Silver/Bronze" community settings

### PR DESCRIPTION
**Pull request by majick**
These settings have been popular in the community and are good candidates for defaults.

They represent the rough lower and upper bounds of a "goldilocks zone" of excellent results with many of the popular models.  Most users don't really know how to approach mirostat beyond what's been whispered by word of mouth.  A few of the well-liked presets that are getting passed around already should give users a nice starting place to experiment with it.

### CODE REVIEW

**Comment by Cohee1207** [comment]
Looks good, I'd just remove 
```
   "genamt": 512,
    "max_length": 8192
```
from them.

**Comment by majick** [comment]
My bad on the hardcoding!  Thanks for catching that.

**Comment by Cohee1207** [comment]
All fixed and merged. Thanks a lot.

**Comment by CamiloMM** [comment]
Can you tell me what the gold/silver/bronze represent? I've seen some comments saying Tau should be ~5 for 13b models and ~4 for 70b so I assume now that's entirely incorrect? Since these have Tau at 9+.

**Pull request merged**
