### PR TITLE
allow char scpoed regex

### PR DESCRIPTION
**Pull request by steve02081504**
no ui because i'm not good at it, but works.

### CODE REVIEW

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
I discussed this elsewhere, but this should be an opt-in to allow using character regex embeds. Because using regex by default with no ability to disable them opens a wide range of potential abuse. Basically I envision this similarly to lorebook embeds: have a window to confirm that you want to use embedded regex.

Also, how is this gonna work in groups? Especially the display ones...

**Comment by steve02081504** [comment]
I'm not familiar with UI-like, but I think that's probably it?
I think we're still missing an update query when the existing WIbook/regex_script differs from what's in the character cards, but that should be an afterthought

**Comment by Cohee1207** [comment]
I reworked the UI. Check it out and tell me what you think @steve02081504

**Comment by steve02081504** [comment]
> I reworked the UI. Check it out and tell me what you think @steve02081504

Thank you for your expert help! this looks much better than what I done🥰
hard work!

**Comment by steve02081504** [comment]
One thing I'd like to ask is, can I just drag the global regex into the character scpoed column?
This might be slightly more intuitive to common operations.

**Comment by steve02081504** [comment]
Oh, sorry, I didn't see that button.
~~It would be nice if the presets could also be embedded with regex~~

**Comment by Cohee1207** [comment]
> It would be nice if the presets could also be embedded with regex

What presets? There are like 12 kinds of them in ST

**Comment by steve02081504** [comment]
> What presets?

Since some authors like to include thinking questions in their presets to get the model to first think about things like the goals and relationships of the characters in the current dialog, sometimes the preset needs a companion regular to remove the relevant information from the display.
However, each preset author uses a different format for the rules.
图片
图片

> There are like 12 kinds of them in ST

It's all the same for users, they just see a different selection of models.

**Comment by Cohee1207** [comment]
Shared prompts could easily be parts of embedded lorebooks. Your example would vendor lock a character to a specific model from a specific provider, which is not good.

**Pull request merged**
