### PR TITLE
Update zh-cn.json

### PR DESCRIPTION
**Pull request by Touch-Night**

### CODE REVIEW

**Comment by Cohee1207** [comment]
@steve02081504 well, the conflict is still there
https://github.com/SillyTavern/SillyTavern/pull/2382#issuecomment-2171410600

**Comment by steve02081504** [comment]
> @steve02081504 well, the conflict is still there
> https://github.com/SillyTavern/SillyTavern/pull/2382#issuecomment-2171410600

You can merge the conflicts and then just choose the existing version, the whole content of this pr is already included in #2382👍

**Comment by Cohee1207** [comment]
> You can merge the conflicts and then just choose the existing version, the whole content of this pr is already included in https://github.com/SillyTavern/SillyTavern/pull/2382👍

Huh. Okay

**Comment by Cohee1207** [comment]
Well, it makes no sense to merge now as the diff is empty.

**Comment by Touch-Night** [comment]
So what should I do?

**Comment by Cohee1207** [comment]
Nothing, it's merged externally.

**Pull request closed without merging**
