### PR TITLE
DO NOT MERGE: Generate: Change prompt building mechanisms

### PR DESCRIPTION
**Pull request by kingbri1**
The current mechanisms are dated and can be a bit inefficient. The new method of array-based prompt building is the foundation for modularizing parts of a prompt rather than using string addition and various operations.

### CODE REVIEW

**Comment by kingbri1** [comment]
Have only tested this on textgen webui. Not sure how openAI will play around with this since everything's completely different in that land.

**Comment by IkariDevGIT** [comment]
hey, nice idea but i would like to still be able to use this mode as the array think is kinda a downgrade for me, is that possible? (you could call it manual mode or smth)

**Comment by Cohee1207** [comment]
@IkariDevGIT you seem to misunderstand the purpose of this PR. It is only a reorganization of prompt-building internals to get rid of unnecessary string concatenations. Nothing changes from the user's perspective.

**Comment by IkariDevGIT** [comment]
oh ok, sorry for the unnecessary message then.

**Pull request merged**
