### PR TITLE
World Info inclusion group prio toggle

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Added a toggle to WI inclusion group to give it prioritization.

This way its possible to decide you don't want WI entries to be **rolled**, but actually define which one will be triggered above another in an inclusion group, if multiple are triggered.

Small tooltip to explain it is added.  
Docs changes will come after PR.

image

### CODE REVIEW

**Comment by underscorex86** [comment]
sweet, thenk.

**Comment by Wolfsblvt** [comment]
Fixed a few things and renamed the WI property. Should be done, unless Cohee finds something.

**Review by Cohee1207 — APPROVED** [review]
Should be fine by now. I tested it working, but can't think of a use case. Well, I hope the docs will clear this up 🗒️

**Comment by Wolfsblvt** [comment]
The use-case is, bluntly said, that there are people who don't like having anything "random" about the WIs they plan.

You could do everything else with keeping trigger% at 100, using NOT key filters, and more.  
There was no way of preventing another WI to trigger if one was triggered. This is what this allows.

I'll try to make the docs clear on that. Working on that today.

**Pull request merged**
