### PR TITLE
Tag Folders Enhancements : folder sorting, folder types, navigation, inline display

### PR DESCRIPTION
**Pull request by Wolfsblvt**
I reworked the "**Tags as Folders**" feature that already existed.  
It was a bit of a pain to use, tbh, and if you had many tags for your characters, it hurt more than it helped. I tried to keep the original intention of the system alive, but using tags, and not implementing *real* folder sorting, as that would've been a whole other can of worms.  

I have mode quite a few design decisions, from all tags being "no folder" by default to the way tags get sorted and in which order filters are applied. I hope those are okay.

Please let me know what you think of the changes, if there are any remarks/requests about the implementation or the code style. Thank you!  
(I am no frontend dev, this is actually very painful, aaaaaaah.)

Below a list of all things (almost exhaustive, I hope..), and a few screenshots at the end to display better what has changed.

### Current features / changes
- [x] Each tag can individually be enabled as folder
- [x] Different Folder states (Open, Closed/Hidden, No Folder)
- [x] Make tags sortable per drag&drop
- [x] "Clear all filters" functionality
- [x] Sync tag filter and folder drilldown list
- [x] Tag filter button with indicator (if any filter is applied), and collapsed state saved
- [x] Make Folder drilldown "visible" as a drilldown list
- [x] Enhance information about characters inside a folder (inline avatars, count)
- [x] Enhance information about groups (list of names in that group, count)
- [x] Hidden items counter (on folders, and total)
- [x] Improve grid view display (with folder and group information
- [x] Downsize "back" bar in list view
- [x] Hotswap/favorites Rework (Tooltip, respect chosen avatar style, etc, using the same method to draw than the group sub list now)

### Smaller changes / fixes during dev
- [x] Sort tags in all the places where they are displayed and used (except tag insert dropdown, which is alphabetically)
- [x] Auto-resort/redraw if sorting is changed
- [x] Fix redraw of tags/entity list on tag changes
- [x] Fix all folder vanishing if a tag filter was applied (because folders don't have tags)
- [x] Character/characters singular wording fix

### Rejected
- [x] Tag dropdown sorted too => Alphabetically makes more sense for a searchable dropdown

### Planned after this PR
- Customizable folder icon => Well, you can customize colors, that's halfway. And icon is needed for closed/hidden folders for now. Maybe I'll implement that some time later, when I find a neat way for a searchable dropdown of fa icons.
- Saving of all filters => Makes sense. Optional feature though, saved for later
- Drag characters into folders => I am planning to expand the "bulk edit" functionality. Adding/removing tags from all, draggable characters (to folders), and maybe some more ideas.

#### Remarks

- Okay, I am not sure why the "excluded" filter for the tag list gets saved and persisted, but all other filters are not? A bit confusing.  
I would expect either all filters to be persisted, or none (idea for filter presets? hehe). Kept the current design for now.
- Filters do not get deleted when the entity list is redrawn. Refreshing the site does that (besides `excluded`, which is persisted...)
- Both of those are "as they were before", and I think they'll be a non-issue in the future when I implement saving of all filter states. With the "Clear all filters" button I think it's a better design and more convenient to actually save the filter state persistently, like sort order is too for example.

### Some screenshots
image
image 
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Okay, new PR is up. Still draft. Should be finished soon though. I am not fucking up with merging/rebase again...

**Comment by Wolfsblvt** [comment]
Okay, done with the implementation now. Bring it on, I am ready for harsh judgment.

**Comment by Spacellary** [comment]
Feel/visually it looks good ;'3

**Comment by Cohee1207** [comment]
It's a good idea but requires more polishing before rolling it out. I fixed some things I've found.

**Comment by Wolfsblvt** [comment]
Hey @Cohee1207. I'll take a look at your fixes once I am home. Thanks!

Will likely learn a bit more. Did expect a few things would be bugged with how many changes I made.

Anything else that requires polishing or that I should/could do?

**Comment by Cohee1207** [comment]
I don't think it's complete as the fix only includes what I've found right away, I didn't thoroughly test the folders themselves, only regression stuff.

**Comment by Cohee1207** [comment]
Okay, should be fine to merge now. I didn't find anymore (obvious) issues.

**Review by Cohee1207 — APPROVED** [review]

**Pull request merged**
