### PR TITLE
Lazy init & Cache of WorldEntryUI

### PR DESCRIPTION
**Pull request by steve02081504**
the WIbook display is too slow, this PR can delay part of the UI init until the user clicks on it to speed up the WIbook display slightly

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by steve02081504** [comment]
ready for review
tested displaying 170 WI Entry on one page, tooks about 3 seconds
The second time with caching tooks 1 second

**Comment by steve02081504** [comment]
wait, I might be able to optimize it a bit more...

**Comment by steve02081504** [comment]
better now

**Review by Wolfsblvt — COMMENTED** [review]
Like I already shared on Discord, this changed the time to expand all entries in a book I have, with page size 25, from ~2.0s to ~5.0s, over doubling that time.

I do see a need for improving performance on WI wherever possible. I can see how your changes changed the initial load/open of the book from 1.3s to 0.4s, so the improvement is there.
But considering how often you open WI and want to edit/see all entries, this trade-off is not worth it, in my opinion.

### Staging - Expand all
image
### PR - Expand all
image

### Staging - Initial WI open
image
### PR - Initial WI open
image

**Comment by steve02081504** [comment]
> Like I already shared on Discord, this changed the time to expand all entries in a book I have, with page size 25, from ~2.0s to ~5.0s, over doubling that time.

@Wolfsblvt i pushed a fix of it: [`3123636` (#2607)](https://github.com/SillyTavern/SillyTavern/pull/2607/commits/3123636f5add51601d58af3a418c6587f7d4c1e6)
how about now?

**Comment by Cohee1207** [comment]
I think it's mostly superseded by #2615 which made WI editor much faster.

**Pull request closed without merging**
