### PR TITLE
add slash commands to crud QRs

### PR DESCRIPTION
**Pull request by LenAnderson**
Adds slash commands to create, update, and delete QRs.
Can set everything except context menus. I will have to think about how to best deal with those.

```
/qr-create (arguments, [message])
  arguments:
    label    - string - text on the button, e.g., label=MyButton
    set      - string - name of the QR set, e.g., set=PresetName1
    hidden   - bool   - whether the button should be hidden, e.g., hidden=true
    startup  - bool   - auto execute on app startup, e.g., startup=true
    user     - bool   - auto execute on user message, e.g., user=true
    bot      - bool   - auto execute on AI message, e.g., bot=true
    load     - bool   - auto execute on chat load, e.g., load=true
    title    - bool   - title / tooltip to be shown on button, e.g., title="My Fancy Button"
– creates a new Quick Reply, example: /qr-create set=MyPreset label=MyButton /echo 123

/qr-delete (set=string [label]) – deletes Quick Reply

/qr-update (arguments, [message])
  arguments:
    newlabel - string - new text fort the button, e.g. newlabel=MyRenamedButton
    label    - string - text on the button, e.g., label=MyButton
    set      - string - name of the QR set, e.g., set=PresetName1
    hidden   - bool   - whether the button should be hidden, e.g., hidden=true
    startup  - bool   - auto execute on app startup, e.g., startup=true
    user     - bool   - auto execute on user message, e.g., user=true
    bot      - bool   - auto execute on AI message, e.g., bot=true
    load     - bool   - auto execute on chat load, e.g., load=true
    title    - bool   - title / tooltip to be shown on button, e.g., title="My Fancy Button"
– updates Quick Reply, example: /qr-update set=MyPreset label=MyButton newlabel=MyRenamedButton /echo 123
```

### CODE REVIEW

**Comment by IkariDevGIT** [comment]
yea context menu's are important probably

**Comment by LenAnderson** [comment]
`|{}` can be escaped with backslash in the QR message / command.
```
/qr-create label=MyButton /getvar myvar \| /echo \{\{pipe\}\}
```
to create a QR that calls
```
/getvar myvar | /echo {{pipe}}
```

---

Added context menu commands.
```
/qr-contextadd (set=string label=string chain=bool [preset name])
– add context menu preset to a QR, example: /qr-contextadd set=MyPreset label=MyButton chain=true MyOtherPreset

/qr-contextclear (set=string [label])
– remove all context menu presets from a QR, example: /qr-contextclear set=MyPreset MyButton

/qr-contextdel (set=string label=string [preset name])
– remove context menu preset from a QR, example: /qr-contextdel set=MyPreset label=MyButton MyOtherPreset
```

**Comment by LenAnderson** [comment]
Presets can be created (overwritten if existing):
```
/qr-presetadd (arguments [label])
  arguments:
    enabled - bool - enable or disable the preset
    nosend  - bool - disable send / insert in user input (invalid for slash commands)
    before  - bool - place QR before user input
    slots   - int  - number of slots
    inject  - bool - inject user input automatically (if disabled use {{input}})
– create a new preset (overrides existing ones), example: /qr-presetadd slots=3 MyNewPreset
```

**Comment by LenAnderson** [comment]
`/qr-presetupdate` has the same arguments as `/qr-presetadd`

**Comment by IkariDevGIT** [comment]
Can you add a {{getQREntryNameByID::1::QRPresetName}}

**Comment by IkariDevGIT** [comment]
And a macro to check how much entries there are in a qr preset

**Comment by IkariDevGIT** [comment]
And a macro te get the name of the current(where the slash is getting executed) qr preset and the current id of the entry

**Pull request merged**
