### PR TITLE
Llama 3 Instruct context+instruct presets

### PR DESCRIPTION
**Pull request by WolframRavenwolf**
Hot off the press, here are the Llama 3 Instruct context and instruct presets. (I'm glad Meta finally dropped the abomination of a chat template that was Llama 2 Chat.)

### CODE REVIEW

**Comment by nyxkrage** [comment]
These presets just seem flat out wrong versus what Meta themselves have published https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

{{ system_prompt }}<|eot_id|><|start_header_id|>user<|end_header_id|>

{{ user_message_1 }}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{{ model_answer_1 }}<|eot_id|><|start_header_id|>user<|end_header_id|>

{{ user_message_2 }}<|eot_id|><|start_header_id|>assistant<|end_header_id|>
```
There shouldn't be any newlines after the `<|eot_id|>` or before the `<|start_header_id|>`

**Comment by WolframRavenwolf** [comment]
> There shouldn't be any newlines after the `<|eot_id|>` or before the `<|start_header_id|>`

You're right, thanks for pointing it out. I fixed it and removed the erroneous newlines.

**Comment by HiroseKoichi** [comment]
There's two newlines after the {{trim}} macro in the story string that shouldn't be there, and the stopping string is wrong; `<|eot_id|>` denotes the end of a turn while `<|end_of_text|>` is the actual stopping token.

From [Meta's docs](https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/):

`<|eot_id|>`: This signifies the end of the message in a turn.
`<|end_of_text|>`: This is equivalent to the EOS token. On generating this token, Llama 3 will cease to generate more tokens.

---

> Hot off the press, here are the Llama 3 Instruct context and instruct presets. (I'm glad Meta finally dropped the abomination of a chat template that was Llama 2 Chat.)

Same here; that format should never have been created. Unfortunately, though, they decided to make a new one that's just a more complex ChatML instead of just using ChatML.

**Comment by nalf3in** [comment]
You are right about the two new lines after the {{trim}} macro but actually from the meta docs <|eot_id|> is the right token to use. You can see it is immediately after the system prompt `{{ system_prompt }}<|eot_id|>.`

Another problem is the additional \n (newline) after the new chat 
`New Chat:<|eot_id|>\n<|begin_of_text|>` and I wasn't able to figure out quickly where it's coming from 

And another problem is the lack of <|begin_of_text|> token, it should be at the start of the story string:

```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

{{#if system}}{{system}}
{{/if}}{{#if wiBefore}}{{wiBefore}}
{{/if}}{{#if description}}{{description}}
{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}
{{/if}}{{#if scenario}}Scenario: {{scenario}}
{{/if}}{{#if wiAfter}}{{wiAfter}}
{{/if}}{{#if persona}}{{persona}}
{{/if}}{{trim}}<|eot_id|>
```

**Comment by HiroseKoichi** [comment]
> You are right about the two new lines after the {{trim}} macro but actually from the meta docs <|eot_id|> is the right token to use. You can see it is immediately after the system prompt `{{ system_prompt }}<|eot_id|>.`

Directly from Meta's docs, they state that the `<|end_of_text|>` token is the EOS token. Though, thinking about it more, you are correct; while the `<|end_of_text|>` token is technically the correct one, it would mean that the `<|eot_id|>` token would show up in the visible chat.

> Another problem is the additional \n (newline) after the new chat `New Chat:<|eot_id|>\n<|begin_of_text|>` and I wasn't able to figure out quickly where it's coming from

This is something that SillyTavern does to separate different sections from each other. It's not something that can be fixed in the template.

> And another problem is the lack of <|begin_of_text|> token, it should be at the start of the story string:

No, Meta states that the `<|begin_of_text|>` token is the BOS token. The model automatically adds this; it's not something you add to the template.

**Comment by WolframRavenwolf** [comment]
Hey guys, thanks for the input! So Meta stays true to formats that need further explanation, unfortunately...

You're right about the two newlines in the story string. I had overlooked them, and have now removed those.

Regarding the EOS token and stop sequence: `<|end_of_text|>` is the EOS token, but that should be caught by the backened to stop inference, so we shouldn't have to deal with that in the frontend. The stop sequence we need to intercept (and strip) in the frontend is `<|eot_id|>`, signifying the end of turn when the AI is done speaking.

And, yes, the BOS token is not something we've ever added manually in the templates. That should be done automatically and transparently by the software.

**Comment by WolframRavenwolf** [comment]
The "Chat Start" thing irks me a bit, too: Without examples, there's no point in the "Chat Start" system message. We could just drop that, and then the chat template would be completely correct when using character cards without examples.

So what's more important to most users: Better (perfect) support for a chat template – or better (good enough) support for character cards with examples?

The advantage of keeping the "Chat Start" as it is now is that it's easier to manually empty the "Chat Start" box if you want a perfect chat template, than manually entering the correct sequence yourself. It's probably what I'll be doing locally, as examples will still work, just lack a clear separation between examples and new chat, but that should still work in most cases. However, I don't want to force my personal preference on everyone so open to leave it in for the official presets – or remove it there as well if there's consensus on that?

**Comment by Cohee1207** [comment]
Chat and example headers generally shouldn't matter that much for a smart model. They are safe to be removed.

**Comment by WolframRavenwolf** [comment]
Alright, done: Chat and example headers removed. Now these presets should be exactly as prescribed by Meta.

**Comment by nalf3in** [comment]
Regarding the bos token, I should maybe open another issue but it looks like it will never be included with koboldcpp because of the system message... According to the readme of the server:
```
   `prompt`: Provide the prompt for this completion as a string or as an array of strings or numbers representing tokens. Internally, 
if `cache_prompt` is `true`, the prompt is compared to the previous completion and only the "unseen" suffix is evaluated. 
A `BOS` token is inserted at the start, if all of the following conditions are true:

      - The prompt is a string or an array with the first element given as a string
      - The model's `tokenizer.ggml.add_bos_token` metadata is `true`
      - The system prompt is empty
```

**Comment by WolframRavenwolf** [comment]
@nalf3in If that's true, it's definitely a koboldcpp issue – I don't see why an empty system prompt should ever be a condition for BOS token insertion. Would be best to submit that as an issue over there.

But if you're only using koboldcpp, you could of course manually insert `<|begin_of_text|>` at the top of the story string, or make a special kobold preset for that on your system. However, as with most things, a smart model should be flexible enough to work well enough with or without the BOS token.

**Comment by nalf3in** [comment]
Noted, one last thing: 

The last line ` <|start_header_id|>assistant<|end_header_id|>\n\n `includes two end of lines which doesn't fit with the meta guidelines. We could fix it with  `"last_output_sequence": "<|start_header_id|>assistant<|end_header_id|>",`

**Comment by WolframRavenwolf** [comment]
@nalf3in I'm sure it is correct. You're probably looking at the docs in HTML which trims whitespace, or maybe they messed up the docs, but I'm refering to the actual tokenizer config as my source:

> https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/tokenizer_config.json
> 
> `'<|start_header_id|>assistant<|end_header_id|>\n\n'`

There are definitely two newlines here, so that it follows the pattern.

**Comment by nalf3in** [comment]
Ah I see, I was indeed using the html docs. The jinja template does include the last two \n\n in the huggingface official repo. To be pedantic, I followed the link to the code mentioned in the html doc and found the class and function for the chat format [here](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py)  where you can see there is no double \n at the end 

```
    def encode_dialog_prompt(self, dialog: Dialog) -> List[int]:
        tokens = []
        tokens.append(self.tokenizer.special_tokens["<|begin_of_text|>"])
        for message in dialog:
            tokens.extend(self.encode_message(message))
        # Add the start of an assistant message for the model to complete.
        tokens.extend(self.encode_header({"role": "assistant", "content": ""}))
        return tokens
```

However to be honest it seems the model works pretty well with both so I would be fine to merging as is

**Comment by Cohee1207** [comment]
I replaced the system prompt post-merge, quoting @RossAscends :
>  I went for something other than “roleplay chat” because it affected responses. Made them more “fantastical”

**Comment by WolframRavenwolf** [comment]
> Ah I see, I was indeed using the html docs. The jinja template does include the last two \n\n in the huggingface official repo. To be pedantic, I followed the link to the code mentioned in the html doc and found the class and function for the chat format [here](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py) where you can see there is no double \n at the end
> 
> ```
>     def encode_dialog_prompt(self, dialog: Dialog) -> List[int]:
>         tokens = []
>         tokens.append(self.tokenizer.special_tokens["<|begin_of_text|>"])
>         for message in dialog:
>             tokens.extend(self.encode_message(message))
>         # Add the start of an assistant message for the model to complete.
>         tokens.extend(self.encode_header({"role": "assistant", "content": ""}))
>         return tokens
> ```
> 
> However to be honest it seems the model works pretty well with both so I would be fine to merging as is

There's no double \n in the code you quoted, but that second-to-last line calls the encode_header function which then adds the double \n:

```
    def encode_header(self, message: Message) -> List[int]:
        tokens = []
        tokens.append(self.tokenizer.special_tokens["<|start_header_id|>"])
        tokens.extend(self.tokenizer.encode(message["role"], bos=False, eos=False))
        tokens.append(self.tokenizer.special_tokens["<|end_header_id|>"])
        tokens.extend(self.tokenizer.encode("\n\n", bos=False, eos=False))
        return tokens
```

I agree that it probably wouldn't have made much of a difference, but hey, after this little investigation in the bowels of the tokenizer we can both rest assured that the template is correct. 😉

**Comment by WolframRavenwolf** [comment]
> I replaced the system prompt post-merge, quoting @RossAscends :
> 
> > I went for something other than “roleplay chat” because it affected responses. Made them more “fantastical”

OK, thanks. With everything else as it should be, and the system prompt being something that anyone can easily customize to their preferences, that's fine with me. And who knows, maybe it will be a new universal prompt that works well for both work and play. 👍

**Comment by Culpeo** [comment]
I played around with that template and NousResearch/Meta-Llama-3-8B-Instruct-GGUF and it's working _really_ well. I only had one issue with the /gen command:

> /gen Do not continue the story. Describe the feelings and thoughts of {{char}} about the current situation. Maximum three sentences.| /echo {{pipe}}

This would lead to a console output as follows.

```
<|start_header_id|>system<|end_header_id|>\n" +
    '\n' +
    'Do not continue the story. Describe the feelings and thoughts of Wolf about the current situation. Maximum three sentences.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n' +
    '\n' +
    'Wolf:'
```

However, the model always just repeated the last message that was said by the character:

image

After some more experimenting I checked the box "System same as User"
image

The output changes as follows:

```
<|start_header_id|>user<|end_header_id|>\n" +
    '\n' +
    'Do not continue the story. Describe the feelings and thoughts of Wolf about the current situation. Maximum three sentences.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n' +
    '\n',
```

And only _then_ I got the expected result. Could it be that the model doesn't complete assistant messages that follow a system message, or am I doing something wrong?

image

**Comment by Cohee1207** [comment]
@Culpeo 
This usually depends on a model but rarely can they complete the system message, and this often leads to hallucinations. You can override the behavior of neutral/background requests by setting the "System Instruction Prefix" sequence under advanced controls. Set that to User prefix and you'll override the instruction header for /gen, but "true" system messages will stay as before.

**Comment by nyxkrage** [comment]
> And only then I got the expected result. Could it be that the model doesn't complete assistant messages that follow a system message, or am I doing something wrong?

Llama3 has been trained with the system message appearing only as the first message in the context as is specified on the model card, and has only been trained with ending with a user message, this seems to me to be intended behavior of the model

> A prompt should contain **a single system message**, can contain multiple alternating user and assistant messages, **and always ends with the last user message followed by the assistant header.**

**Comment by Culpeo** [comment]
Good ideas! @Cohee1207, I tried this but it doesn't change the system message that needs to be changed, I'm afraid. It only puts that system instruction prefix in the end of the prompt, instead of _<|start_header_id|>assistant<|end_header_id|>\n_ (which doesn't make any sense to me)

System instruction prefix set:
image

System instruction prefix empty:
image

@nyxkrage, thanks, then it works as designed :-)

No idea how deep we should dig here and what other parts of the generation are affected when we set System same as User to TRUE or FALSE. I'll need to experiment more with this preset.

**Comment by Cohee1207** [comment]
Treating system messages as user would make sense then - there are no system messages besides the first one, that is preoccupied by the prompt + card.

**Comment by HiroseKoichi** [comment]
Models trained using ChatML, or any other format with a system prompt, are only trained with the system message appearing in the first message, but you can use multiple without issues.

I think Meta specifically trained their instruct models to ignore any additional system messages.

**Pull request merged**
