### PR TITLE
Change import character URL help text to reflect JanitorAI -> JannyAI change

### PR DESCRIPTION
**Pull request by ayancey**
Update help text to reflect change from JanitorAI to JannyAI (#2392)

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ayancey** [comment]
Worth mentioning this feature seems to be broken entirely. I'll look into it when I can.

**Comment by Wolfsblvt** [comment]
Are you talking about that scraper site that just re-hosts all Janitor cards?
Because the actual JanitorAI (janitorai.com) is still named like this. And importing characters from there via their link works flawlessly.

So that rename doesn't make much sense. If you ask if we should add the secondary site there as well, I am not sure we should.

**Comment by Cohee1207** [comment]
The feature works when it wanna. Since Janitor doesn't provide a way to export character, a third-party mirror is being used. But it accepts JanitorAI links so the UI text is correct.

**Comment by ayancey** [comment]
Hi, thank you for your responses. I'm very new to this world, so forgive me.

## Errors

> Are you talking about that scraper site that just re-hosts all Janitor cards? Because the actual JanitorAI (janitorai.com) is still named like this. And importing characters from there via their link works flawlessly.
> 
> So that rename doesn't make much sense. If you ask if we should add the secondary site there as well, I am not sure we should.

I was unable to import characters from JanitorAI.com into SillyTavern. I tested this with the full URL and with UID (ex: "https://janitorai.com/characters/e5d92cab-e128-4873-b5f9-363dea1ac96a_character-not-real", and "https://janitorai.com/characters/e5d92cab-e128-4873-b5f9-363dea1ac96a_character-not-real".

I also tested with characters that exist on both sites with the same UID, I tested this with both URLs, as well as with UID as stated above.

image


## Distinction between both sites

> The feature works when it wanna. Since Janitor doesn't provide a way to export character, a third-party mirror is being used. But it accepts JanitorAI links so the UI text is correct.

I think I understand what you're saying. The new endpoint is JannyAI (previously JanitorAI.me from what I understand). It seems they were scraping/collecting bot definition data from JanitorAI.com.

The text on JannyAI suggests that they may no longer able to scrape the bot definition from new characters on JanitorAI. However, I was able to find that everything on JanitorAI also existed on JannyAI.

>Due to JanitorAI structure change, we might not be able to get some new bot's definition now lol. Most old bots should still work fine.

Because of that, I think it's worth mentioning.

**Comment by ayancey** [comment]
After I looked into it, I get it now. My confusion was in thinking that JannyAI had unique characters in addition to those of JanitorAI, rather than only being a scraper/indexer for it.

As for the broken functionality, see #2611.

**Pull request closed without merging**
