### PR TITLE
Improve bulk edit and bug fixes to tags 

### PR DESCRIPTION
**Pull request by Wolfsblvt**
### Fixes
- [x] Fix tags not working on new character dialog
- [x] Fix display of tags for auto-loaded character on enabled auto load
- [x] Fix folder navigation (drilldown list, back block) being drawn even with folders disabled

### Improvements to bulk edit tag popup
- [x] Show avatars of all selected characters
- [x] Show mutual tags of selected characters
- [x] Add button to only remove all mutual tags
- [x] Moved close button to the right for better UI flow

### Improvements on general bulk edit
- [x] Show selected number
- [x] Extend tooltip to explain how bulk edit works
- [x] Add button for "select all"
- [x] Implement Shift + Click to select/deselect multiple characters
- [x] Refactor bulk edit delete context menu and button to use the same method
- [x] Show avatars of all selected characters in bulk delete popup

### Other small things
- [x] Improved and streamlined usage of `printTagList`, by providing a shared optional input args object `PrintTagListOptions` in all places
- [x] Reworked `printCharacters` to always redraw filters too, refactored most places to utilize a debounced `printCharactersDebounced` for drawing, so we only have one centralized and unified way of redrawing the list.
- [x] Improved/reworked the parameters options a bit, e.g. allowing a late function resolve to gather the tags to print
- [x] Add Filename to tooltip of avatar inside avatar list / inline avatars
- [x] Fix annoying appearing scrollbar in popups like the tag list when you drag/drop items
- [x] Fix endless loop/reprint on selected tags

## Some screenshots
image
image
image

Also why the heck aren't the popups consistent? That bothers my OCD tendencies again, aaaaaaaa.

### CODE REVIEW

**Comment by Cohee1207** [comment]
It's almost perfect, I just wish bulk edited tags could updated in the list live. That would require calling printCharacters if the bulk edit menu is currently visible, I suppose.

**Comment by Wolfsblvt** [comment]
I can do that. That should be possible.  
You mean that when you add/remove tags the char list in the background gets updated and reprinted on the fly?

I already have something very similar to that in use with the tag edit popup, so that shouldn't be too difficult.

Let me implement and test that later.

**Comment by Cohee1207** [comment]
Yea that's what I meant

**Comment by Wolfsblvt** [comment]
Did that implementation. I also couldn't help myself and made another big refactoring to streamline how the character list gets redrawn.

We now have two centralized functions: `printCharacters` if you need it blocking and want to see changes right away, and `printCharactersDebounced` for everything where redrawing the list is actually a side task. There is no need to redraw filters manually anymore, and because of the debounce it doesn't *hurt* if it might be called multiple times during some events or execution.  
Think this is much cleaner now.

I also did some more small changes, you can check the commit comment message for those.

**Comment by Cohee1207** [comment]
Very nice is that now you can come back to the characters list without losing the scroll position.

**Comment by Cohee1207** [comment]
@Wolfsblvt I just noticed that printing filters when you have a filter selected cause them to spaz out and loop the characters list rendering, specifically because toggleTagThreeState simulates a tag click.

**Comment by Cohee1207** [comment]
Easiest workaround: make selected filters persisted too, not only excluded

**Comment by Wolfsblvt** [comment]
Yeah, the scroll position thingy was a quick idea I had and I love it.

Man. Okay, I see what issue you mean, and I think your hunch might be right.  
I was actually already planning on making filters save state, but more like all of them... Maybe it's time to do this too and make this PR even bigger. Whoops.

I'll check this evening what I can do when I have time. I'll find a solution.

**Pull request merged**
