### PR TITLE
Add ChromaDB and RVC Model Persistence to Collab

### PR DESCRIPTION
**Pull request by GoAwayNow**
Adds persistence for ChromaDB and RVC models by connecting to Google Drive and storing the files there. This prevents the user from having to constantly export and import files from the UI at the tradeoff of cloud storage space.

Changes were made directly in Collab and saved to Github via the "Save a copy to Github" dialogue.

## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Cohee1207** [comment]
ChromaDB and extras in general are no longer maintained and not recommended to use. I'm considering removing the colab entirely

**Comment by GoAwayNow** [comment]
Oh... well, dang. Should I go ahead and close this? The fact that it was still given the "Under consideration" tag yesterday gives me some pause.

**Comment by Wolfsblvt** [comment]
Maybe I should rename the label. It's more meant as "this might be closed"

**Comment by GoAwayNow** [comment]
> Maybe I should rename the label. It's more meant as "this might be closed"

Ah, I see.

I had initially made these changes quite a while ago, but that was right around the time extras transitioned to Python 3.10, so my drive notebook became a bit of a mess with the workarounds for running 3.10 on Collab. I only just realized that Collab got updated to 3,10 and didn't even realize that Smart Context was deprecated in the interim.

Well, I'll go ahead and close this in that case. My fork will still be there in case anyone wants to use it for RVC, but in all honesty, RVC doesn't seem to gain much running on Collab vs local.

**Pull request closed without merging**
