### PR TITLE
Move character endpoints into their own module

### PR DESCRIPTION
**Pull request by valadaptive**
This PR renames the characters API's endpoints and moves them into their own module, as part of modularizing server.js.

The `characters/` route wasn't moved into the new module since it's mainly meant to serve static files--I think de-duplicating it with the `backgrounds/` route (since they both share the same logic) is better than moving it into its own module.

I've also not moved any of the stats endpoints into the characters module--since stats can be gathered for characters *and* chats, I think it makes more sense to put them into their own `stats` module later.

### CODE REVIEW

**Comment by Cohee1207** [comment]
Tested and fixed where needed. Ready to merge.
@RossAscends @artisticMink feel free to chime in.

**Review by Cohee1207 — APPROVED** [review]

**Comment by Cohee1207** [comment]
@city-unit this breaks at least one extension
https://github.com/city-unit/st-auto-tagger/blob/master/index.js#L436

**Comment by valadaptive** [comment]
Do you have a list of the various extensions somewhere? It might be good to have them all in one folder so I can search through usages of the various API URLs in all of them.

**Comment by Cohee1207** [comment]
Official extensions are hosted here: https://github.com/SillyTavern/SillyTavern-Content/blob/main/extensions.json
Unofficial/third-party are hard to track for obvious reasons, but I think the subset of them is posted in SillyTavern Discord, a 3rd-party-extensions forum.

**Comment by valadaptive** [comment]
Made a repository with all the extensions I could find included as submodules; it looks like the ChromaDB and timeline extensions will also need to be updated to replace the `getallchatsofcharacter` endpoint

**Comment by Cohee1207** [comment]
@valadaptive I propose to keep old API URL aliases for compatibility for one-two releases to let all external extensions migrate. And make endpoints write warnings to the console so that the users will nag the extension authors to update it.

**Comment by valadaptive** [comment]
I've added HTTP 308 redirects to the old API endpoints. Form submissions, `fetch`, and `$.ajax` all follow redirects automatically, so this should be completely transparent.

**Comment by Cohee1207** [comment]
Redirects work. Let's stick to them until everything migrates to avoid breaking changes.

**Pull request merged**
