### PR TITLE
impl `{{char_version}}`

### PR DESCRIPTION
**Pull request by steve02081504**
https://github.com/SillyTavern/SillyTavern/issues/2111

### CODE REVIEW

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
1. I feel it belongs to this category (same batch as other char.card fields): https://github.com/SillyTavern/SillyTavern/blob/release/public/script.js#L2291 
2. URL-encoded version is too specific. I believe it won't benefit the wider audience and requires a more generalist approach. Maybe when a new macro parser comes out, we might add a URL-encode transform modifier to it.
3. Update the macros help page https://github.com/SillyTavern/SillyTavern/blob/release/public/scripts/templates/macros.html

**Comment by steve02081504** [comment]
Sorry but I'm trying to reconstruct my card right now. So this PR related content may need to wait until tomorrow.

**Comment by steve02081504** [comment]
Personally, I think `{{char_version_url_encoded}}` will be useful when displaying badges, but it's up to you.
图片

**Comment by Cohee1207** [comment]
This is not nearly an expected use case for a wide audience, so giving only one macro a special version over the others doesn't sell it to me. Try specifying versions that would work without URL encoding.

**Pull request merged**
