### PR TITLE
Rewrite of Quick Reply extension

### PR DESCRIPTION
**Pull request by LenAnderson**
This should probably stay in staging for a while until it is tested so that bugs can be found and fixed.

### CODE REVIEW

**Comment by IkariDevGIT** [comment]
damn, good work. Can you post some screenshots in?

**Comment by LenAnderson** [comment]
@IkariDevGIT I've shared some screenshots on discord in code contribution, there haven't really been any visual changes since.

**Comment by LenAnderson** [comment]
Added `/qr-set-list [all|global|chat]` and `/qr-list setName` slash commands (and corresponding API methods) to get a list of existing (or globally enabled / chat-enabled) QR sets and QRs in a set.

**Comment by LenAnderson** [comment]
- removed the expand button for the QR message / command and replaced the additional options modal with a large editor for all QR properties.  
image
- added shortcut to edit a QR: ctrl-click on a button in the QR bar (or popout) to open the editor modal for that QR

**Comment by LenAnderson** [comment]
Added execute from editor.
image

**Comment by LenAnderson** [comment]
Added import and export of QR sets.
image

**Comment by LenAnderson** [comment]
Added option on each QR to prevent triggering other auto-execute QRs.
The tooltip is a bit of a mouthful.
image

**Comment by LenAnderson** [comment]
QR:
`/echo This is my QR and foo is {{arg::foo}}`

Run from chat input:
`/run foo=bar mySet.myQr`

Shows a toast saying `This is my QR and foo is bar`

**Comment by Cohee1207** [comment]
QR dead on first load
image

**Comment by LenAnderson** [comment]
@Cohee1207 Hold on a sec.

**Comment by LenAnderson** [comment]
@Cohee1207 That should do it.

**Comment by Cohee1207** [comment]
Several problems with settings migration: 
Enable Quick Replies - enabled, was disabled before pulling
Inject user input automatically - enabled, was disabled. And I want it to be disabled by default anyway for the sake of STscripts.
Also, make sure that the Default QR set is not overwritten for people who didn't save it to JSON before updating. There could be some data loss otherwise.

**Comment by LenAnderson** [comment]
@Cohee1207 Settings migration is updated. QR sets are only overwritten once the user makes changes to them. If they remain untouched they will be "translated" every time the page loads.

**Comment by Cohee1207** [comment]
List of bugs:
1. Auto-execute on opening chat doesn't work
2. Auto-execute on user message creates a duplicate user message with QR content appended
3. Auto-execute on AI message hangs the tab on sending

**Comment by LenAnderson** [comment]
@Cohee1207 
> List of bugs:
> 
> 1. Auto-execute on opening chat doesn't work
> 2. Auto-execute on user message creates a duplicate user message with QR content appended
> 3. Auto-execute on AI message hangs the tab on sending

Do you have examples QRs for 2 and 3? 1 is clear, but the other ones I cannot replicate.
There seem to be some timing issues between the `CHARACTER_MESSAGE_RENDERED` / `USER_MESSAGE_RENDERED` events and being able to interact with chat when using auto QRs with normal text instead of stscript, but nothing like what you experienced.

**Comment by Cohee1207** [comment]
Try sending user/AI messages with /send and /sendas respectively
https://gist.github.com/Cohee1207/b428de4552b240d5e5c36006c079d7f8

**Comment by LenAnderson** [comment]
@Cohee1207 
With that QR set I can replicate the behavior from 2 with both /send and /sendas. However, that is expected since inject is enabled in that set and the behavior is exactly what happened in the previous version of QR.

`/send test`with *inject* and without *place before* turns into `/send test /echo test4`
`/sendas name=Alice test` turns into `/sendas name=Alice test /echo test3`

No pipes, so everything after the /send is just text.


I still can't find a way to make ST hang.

**Comment by Cohee1207** [comment]
I think inject shouldn't be enabled on auto-execute at all. There are no useful cases for it

**Comment by LenAnderson** [comment]
@Cohee1207 
Fine with me. I just did not want to deviate too far from the old version.

**Comment by Cohee1207** [comment]
@LenAnderson minor issue: migrated QRs without title get a title `undefined` (as a string)

**Comment by Cohee1207** [comment]
Also zoomed QR editor is hard to use on narrow screens
image

**Comment by Cohee1207** [comment]
Maybe replace "Show buttons" with just "Buttons"? So that it stays on one line. If doesn't fit - can make the text `<small>`
image

**Comment by LenAnderson** [comment]
@Cohee1207 All three addressed.
- label, title, and message of old QRs coalesce to empty string
- show buttons -> buttons
- below 750px everything in modal editor is in column direction

**Pull request merged**
