### PR TITLE
Added quick Regenerate and Impersonate buttons

### PR DESCRIPTION
**Pull request by NearEDGE**
Additional buttons mimic the behavior of the continue button.

This will close:
[FEATURE_REQUEST] quick impersonate/regenerate and adding swipes to persona message [#2232](https://github.com/SillyTavern/SillyTavern/issues/2232)

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
The impersonate toggle is good. As long as it's optional - which is is, that's a good idea.
I don't think Regenerate makes much sense though in my opinion. Regenerate just exists still because... it was always there. I can't find any reason why you should do a Regenerate over a Swipe. If you know one, let me know.

**Comment by NearEDGE** [comment]
Ah, I just realized regenerate doesn't work in SillyTavern the same way it does with Kobold's lite frontend. The way Kobold does it, you can regenerate just the continued part of a message so the two naturally go hand in hand. I'm actually pretty much brand new to SillyTavern.

**Comment by Wolfsblvt** [comment]
No worries, happy to see new people trying to get their hands on contributing here!

There is no built-in functionality to just regenerate continues. There is the third-party extension [LenAnderson/SillyTavern-MoreFlexibleContinues](https://github.com/LenAnderson/SillyTavern-MoreFlexibleContinues) though, which might be one of the reasons why that functionality never really was added, and isn't really needed. If you want that, this got you covered.

I think we can just safely remove the "Regenerate" part of your code, and the impersonate might be handy for those who want it.

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
1. Quick "Impersonate" button - OK
2. Quick "Regenerate" button - not needed

**Review by Cohee1207 — APPROVED** [review]

**Pull request merged**
