### PR TITLE
Enable auto-select of input field on popups + Add "auto-select" utility class

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Always got a bit annoyed with this.
If a popup provides a default value for the input field, it's either a default that is supposed to be changed anyway (Rename Char/Chat, etc) and you wanna clean the existing value of of the text area, or you can simple hit enter to confirm the default value if you don't care. (Like the new WI custom sort order thingy popup)

So it was a bit tedious to manually press CTRL+A or double-click the input, to actually select the text to remove.
Think this is much more intuitive.

I did not provide an option to turn it off for the popup, on purpose. If there are use-cases where it would be really important do not auto-select the default input, then let me know.

Besides that, this PR also adds the general CSS utility class `auto-select`, which can be used for other <input> or <textarea> controls wherever it makes sense.

Note: It'll auto select the full text on every control focus.

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

**Comment by Cohee1207** [comment]
I'm sure this breaks muscle memory of users built over the year, so I require a toggle for that.

**Comment by Wolfsblvt** [comment]
I love me some more *schmoggles* - who doesn't like them.
Under "Miscellaneous"?

Can do that.

**Comment by Wolfsblvt** [comment]
There is your *schmoggle*. Disabled by default. People gonna miss it, but well.
I am happy not having to press CTRL+A for every single "Rename" or "Duplicate" Popup I am opening.

**Review by Cohee1207 — APPROVED** [review]

**Comment by Cohee1207** [comment]
> There is your schmoggle

Dankeschön. It's perfect now.

**Pull request merged**
