### PR TITLE
#1751 Add Quick Connect selector

### LINKED ISSUE #1738: [FEATURE_REQUEST] Separate connection info from chat presets/prompts into a "connection manager"
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Users often have different presets to see what works best for different scenarios.
They may also have access to multiple services, tokens, and reverse proxies.

Conceptually, those settings are orthogonal, so if one uses (for example) 10 different prompt settings and 10 different source/proxy/key combinations, it will result in 10x10=100 presets.

Moreover, if a prompt is updated, it needs to be changed in all the presets (10 in this example), which is extremely inconvenient.

### Describe the solution you'd like

I would like the proxy settings to be moved into API connections and have their own dropdown/import/export consisting of everything that is needed to connect:
- Connection name
- API
- Source
- Key / password
- Proxy / custom URL
- Optionally initial model selection

It is a much more logical organization.

### Priority

Medium (Would be very useful)

### PR DESCRIPTION
**Pull request by Cohee1207**
A different take on #1751 

Closes #1738

### CODE REVIEW

**Comment by cunnymessiah** [comment]
Not sure I really like this now that I've actually loaded all my presets. I just think it brings back the original problem of having too many duplicate presets for what is essentially a small change (proxy url/pass). Take my presets for example
image
If I want to make a "proxy" preset of these, they're going to have to be duplicated and it's going to be the same mess we had before.

It's more so a problem with the fact you're creating and migrating the old presets to new ones, and splitting them in a half half setup. You're sort of forced into this, true, because people are expecting presets to hold model data (what model is selected) but it feels like such a messy way of doing it.

Say we ignore the migration and the end user uses quick connect presets exclusively as a preset for proxies, it'll cut down the amount of presets sure, but that model data that users are expecting to have linked with their chat completion presets won't be linked anymore. Do you get what I mean? It's kind of either you accept having multiple duplicate quick connect presets for proxies (the original problem) or a significant part of the preset is going to end up missing and the user is going to be expected to set their own model. Not sure how well that would go with the people who make and share presets, but that's just my feedback.

**Comment by cunnymessiah** [comment]
> I don't want it to look like we condone the use of proxies by adding non-essential features related to proxy use

Then don't call them proxies, there's plenty of valid usecases for wanting to change the URL OpenAI requests are routed to. After all, most new and emerging model providers that offer an API are using prompt formatting/parameters that are either 1 to 1 or extremely similar to what OpenAI already expects (Mistral and Deepseek for example). Just something to think about. I'm pretty sure nobody would be complaining if "Reverse proxies" were changed into "Alternative Connections" under the pretense of offering some sort of support for model providers that haven't had an official adapter written into SillyTavern yet.

**Comment by Cohee1207** [comment]
> emerging model providers that offer an API are using prompt formatting/parameters that are either 1 to 1 or extremely similar to what OpenAI already expects

Just an unrelated comment, but in most of the cases that's an overstatement. Take Mistral for example and its ridiculous requirements to messages in the prompt. Or all of the "OpenAI-compatible" APIs that say "Don't pass logit_bias or I'll cry in Pydantic".

Back to SillyTavern, I myself consider reverse proxy a legacy option. There's a "Custom" API type that lets you do much more with all of these "OAI-compatible" endpoints, including any additional headers, body parameters, etc.  One might say that it only provides a secret key input that is not presetable, which is fair, but only partially - you can save the key to the "Authorization" custom header which IS totally presetable, but slightly less secure. The only reasons to continue using "reverse proxy" options are habits and outdated guides.

> Do you get what I mean? 

No, I don't quite get it. The way presets are handled right now is illogical. They include the things that are not even on the same UI plane as the fields they preset, and adding exclusively proxy presets is like a band-aid on an open wound. With this implementation, only the sampler settings and prompts are preset with the selection that is directly above those fields. API connection type and other connection options (including a selected model) go to Quick Connect which presets the fields only in the API connect pane.

A user would need to clean up their Quick Connects past migration, and that's better than losing access to saved data, lest manually scurrying through the JSON files.

As for the discontent with this proposed implementation, is there anything else apart from the migration conundrum that hinders it?

**Comment by Cohee1207** [comment]
@LurkerHub any opinion from you as the latest requestor? #1738

**Comment by cunnymessiah** [comment]
> Or all of the "OpenAI-compatible" APIs that say "Don't pass logit_bias or I'll cry in Pydantic

The example was in regards to appearance which is what your primary concern was, not functionality. You don't want to come off as "condoning" proxy use, fine, so I gave you an out that would frame the change as not a "illegal bad thing" but a perfectly valid and legal use case.  The whole argument is moot anyway when you have a big "Reverse Proxy" dropdown directly under one of the first things the user is going to see when they use the program. So I really don't get the logic here.

> I myself consider reverse proxy a legacy option

A large portion of your userbase (arguably the majority), doesn't share that sentiment.

> The way presets are handled right now is illogical

I would argue that this change is even worse than what we've had before, now that I've actually loaded it up and thought more than 5 seconds about it.

> No, I don't quite get it

Then I'll explain it to you as simple as I can. This change does not solve the original issue (duplicate presets) and introduces needless complexity on the users end. What this is doing is just moving the problem to a different dropdown. It is not at all solving it.

> A user would need to clean up their Quick Connects past migration

See above mention of needless complexity. Forcing a user to "clean up" there Quick Connect presets isn't a good thing. What would a "clean up" even entail? 

If you're insinuating that a user would "cleanup" and turn their migrated Quick Connect presets into something like
- GPT-4 (Normal)
- GPT-4 (Proxy 1)
- GPT-4 (Proxy 2)
- Claude 2.1 (Proxy 1)

Then can you not see the issue? How am I meant to know what model my chat completion preset uses lol?

Like I stated in my previous comment you either keep the duplicate presets that hold a different proxy URL (same problem), or you lose the link in name between a chat completion preset and a quick connect preset. With your implementation, you are forced to choose problem 1 or problem 2. They both suck, the user shouldn't be choosing any problem, and they wouldn't be with my implementation.

> They include the things that are not even on the same UI plane as the fields they preset

This is completely arbitrary, OpenAI's playground and many other frontends don't split up parameters and the model selector. In fact SillyTavern 8 months ago didn't either. If you want to go there I would argue they should be lumped together! If I give you a preset, I want the specific model for that preset to be included in what I'm sharing. That is what is expected by people and is just common sense. A Claude 2.0 preset will not work as well on Claude 2.1, so when I give someone my Claude 2.0 preset, I fully expect my frontend to choose Claude 2.0 for them, they shouldn't have to remember that. How is the user meant to know what model to use if they don't remember the specific details of the Chat Completion preset and it's no longer included in the Chat Completion preset file? No, Quick Connect presets is NOT the answer to this because now you're back at square 1 with the duplicate preset issue, and it's even a step back from that because now you're forcing the user to switch their currently selected preset in two different places instead of just one. One for the model settings, and one for the model/connection itself. Needless complexity.

> As for the discontent with this proposed implementation, is there anything else apart from the migration conundrum that hinders it?

The fact that users now essentially have to select their preset twice in different places and the fact that this change does nothing to solve the original issue at hand, I would think significantly hinders it. If you're that hellbent on your stance on proxies and don't want my changes, then please reconsider your changes and revert presets to how they used to be. Because this is honestly such a downgrade.

**Comment by Cohee1207** [comment]
What if we combine both and let select both proxy and quick connect presets? Both are not required to use.

**Comment by Cohee1207** [comment]
But even with having proxy presets, there are still duplicate presets and you have to choose both.

**Comment by cunnymessiah** [comment]
I'm not a big fan of having to select my presets twice and I imagine others wouldn't be either. I believe that the model and it's parameters should be put in the same preset in the same drop down. What were you even going for with the quick connect presets idea in the first place? It just doesn't seem to solve anything at all now I've thought about it.

**Comment by Cohee1207** [comment]
See the linked issue #1738

The described issue is somewhat orthogonal to what is being discussed as it directly suggests to have a set of connections that are disjointed from prompt settings, including proxy address/key, which is implemented here in this PR. It seemed logical enough that this would solve the proxy problem as well, but it seems the reality is harsher.

**Comment by cunnymessiah** [comment]
Alright well if we think about what the user will do, say he has a preset selected (some openai preset for example), he wants to switch connection to a proxy hosting claude. The most likely thing he'll do after switching proxy, is switch to a claude specific preset which will switch his selected model and settings etc. Yes it's still technically two different selections, but only in the case they want to switch proxy, not every time they want to switch preset like with the way you're suggesting. It's also more natural since they'll be in the same panel, and it will also solve the problem 1 problem 2 issues I mentioned before.

**Comment by cunnymessiah** [comment]
> suggests to have a set of connections that are disjointed from prompt settings

proxy address/key would be the only reason you would want to do this in the first place. What purpose would it serve for example in a scenario without them? None, you would just straight up choose the model and completion source from the respective dropdown. You wouldn't need to save presets for that.

**Comment by Cohee1207** [comment]
> What purpose would it serve for example in a scenario without them?

Here's an example: I have a set of prompts I've configured and saved, when using Scale at the time (synthetic example). If I switch my source to OpenRouter, I'd have to resave all of the presets that were using Scale, manually picking the same source for all of them, because it will auto-switch back to Scale on selecting the preset. Or when the preset is saved to one specific snapshot to GPT, but I'd decide to use another one - picking a preset will revert the selection either, and it is much more subtle change that could go unnoticed.

In any case, I don't underappreciate your work on this. If the feedback on my take on this problem is so underwhelmingly negative, we could continue with yours, there are no real  blockers for that. Probably before proceeding, I'd like to hear from the original reporter (@LurkerHub). They could try both implementations and suggest which one is more convenient to use.

**Comment by Cohee1207** [comment]
Maybe there's one thing I'd like to change - is to move the proxy block to the API connection pane as in this PR, as it rightfully belongs there all things considered from the UX standpoint, since it configures the connection.

**Comment by cunnymessiah** [comment]
> If I switch my source to OpenRouter, I'd have to resave all of the presets that were using Scale, manually picking the same source for all of them, because it will auto-switch back to Scale on selecting the preset

I can see this being an issue and it's unfortunate the fixes for each problem conflict with eachother. I think it just has to come down to what's more popular and what fundamentally gets switched more. I think proxies would be the answer to both questions though.

> as it rightfully belongs there all things considered from the UX standpoint

This is fine with me and I can agree makes sense

Anyway, we'll see what the original issuer thinks.

**Comment by LurkerHub** [comment]
> @LurkerHub any opinion from you as the latest requestor? #1738

Looks good!

Now I can have these in quick settings:
- Claude key 1
- Claude key 2
- Claude proxy 1
- Claude proxy 2
- GPT key 1
- GPT key 2
- GPT proxy 1
- GPT proxy 2

And these in presets:
- Preset for Claude 1
- Preset for Claude 2
- Preset for GPT 1
- Preset for GPT 2

And select a pair when I switch between different sources.

Yes, it requires 2 selections if I switch sources, which may pose an inconvenience to those that don't use multiple connection options and/or multiple presets, but it can be solved by adding an optional (may be blank) "default quick connect" option to presets, which will make them behave in a similar way to how they did before.

That said, I did try the new branch without making a backup, which was stupid.
Is it possible to easily revert to the staging branch or are my presets now hosed?


> Probably before proceeding, I'd like to hear from the original reporter (@LurkerHub). They could try both implementations and suggest which one is more convenient to use.

What is the second implementation and where do I find it?

**Comment by cunnymessiah** [comment]
I'm still concerned about Problem 2 I mentioned and the link between presets and the model that's selected in those presets being disconnected with how things are setup with Cohee's changes.

How do you propose dealing with that issue? @LurkerHub 
For someone who has 3-4 presets built for one version of a Claude/GPT model this may not be an issue but for people juggling multiple presets that span across different model versions I see this being a big problem, because under your setup this model data is NOT present anymore. Users will have to remember x preset used y version of model, not to mention how this will potentially affect preset sharing. Like I said before, if I am giving a user a preset I and many others want the model to be included and set as a part of that preset. This is a direct downgrade to what we had previously, solving a problem shouldn't introduce a new one.

> Now I can have these in quick settings:
> - Claude key 1
>- Claude key 2
>- Claude proxy 1
>- Claude proxy 2
>- GPT key 1
>- GPT key 2
>- GPT proxy 1
>- GPT proxy 2

This is already achievable with my changes and do not have the drawbacks of Problem 2 which I think are significant. Please use them both. It should be mentioned the problems Cohee was talking about (Switching between OR/Scale) do not seem to apply to you since you seem primarily concerned with proxy use, which is what my change aims to address.

> What is the second implementation and where do I find it?

Add my forked repo as a remote and then checkout to my branch
`git remote add fork https://github.com/kingbased/SillyTavern-fork.git`
`git fetch fork`
`git checkout fork/proxypreset`

To revert back to main staging
`git checkout origin/staging`

> Is it possible to easily revert to the staging branch or are my presets now hosed?

Good chance your presets are now hosed due to the model/chat completion source being stripped from them, you'd have to revert to staging and manually select those options and save them again

**Comment by LurkerHub** [comment]
Hi @kingbased ,

> Good chance your presets are now hosed due to the model/chat completion source being stripped from them, you'd have to revert to staging and manually select those options and save them again

They're not, I got lucky :)

> I'm still concerned about Problem 2 I mentioned and the link between presets and the model that's selected in those presets being disconnected with how things are setup with Cohee's changes.
> 
> How do you propose dealing with that issue?

As I suggested [above](https://github.com/SillyTavern/SillyTavern/pull/1753#issuecomment-1913806188):
> it can be solved by adding an optional (may be blank) "default quick connect" option to presets, which will make them behave in a similar way to how they did before.

Basically, backward compatibility, if @Cohee1207 adds this option.

> This is already achievable with my changes and do not have the drawbacks of Problem 2 which I think are significant. Please use them both. It should be mentioned the problems Cohee was talking about (Switching between OR/Scale) do not seem to apply to you since you seem primarily concerned with proxy use, which is what my change aims to address.

I switch back and forth between OAI, Anthropic, Mistral, and local models on Colab and Horde, sometimes within the same session to see how different models handle similar prompts.  Does that count?

I will check your implementation momentarily.

**Comment by LurkerHub** [comment]
I tried both options now, and here are my thoughts:
- Keeping the proxy options with the connections feels more logical.
- Allowing the the option to tie a proxy with the presets has merit for some workflows.

I believe that my suggestion above would be a good compromise between the two.
To reiterate:
- Use this PR as a base
- Add a field in the presets to indicate a default quick setting for that preset, to be automatically selected when switching to that preset.  But also allow it to be empty (or "none", or "current") to keep the active quick setting unchanged.
- I also think that the auto-migration was a good idea, as (if the addition above is implemented) it will keep the existing behaviour by default.

**Comment by xokol** [comment]
I want to weigh in on this because I think it effects me as someone who both shared presets and has a whole bunch of presets new and old. I have tried both implementation and I can see where @kingbased is coming from.

Removing the currently saved model from the preset does not seem logical IMO.

> Add a field in the presets to indicate a default quick setting for that preset, to be automatically selected when switching to that preset. But also allow it to be empty (or "none", or "current") to keep the active quick setting unchanged.

I have a lot of presets that aren't all created by me. This is going to be a hassle to first go through all of my presets and record what model they are all saved as, delete the migrated quick connect presets, create new quick connect presets based on the model and proxy link and then go back through all my presets again just to re-save them with the created quick connect presets I would have to make. This way of doing things is asking me to do a lot, while his implementation is basically plug and play, create a new proxy source and boom. My presets are the same, nothing is messed up and I can switch between a few proxies with ease.

I also want to know what will be the standard for uploading or sharing my presets now, will 
I be expected to rely on this migration function if I want to ensure my downloaders are using the right model? Or am I going to have to put in big red text on my rentry saying "SWITCH TO THIS MODEL AND SAVE A NEW QUICK SELECT PRESET yada yada". If so I don't like the idea of either, one pollutes an option menu that in my dream world would only be used for proxies, and the other is expecting all of the people downloading presets to have common sense. Most do not and I want to avoid false reports of my preset not working properly because someone failed to set an option and was using the wrong model.

I don't get it. This is like such an over engineered solution to a novel problem.

**Comment by Cohee1207** [comment]
Looks like we have an agreement to proceed with #1751 

If no one would like to speak against it, I'll arrange a merge tonight.
Closing this one, but not deleting the branch so it could be revived if needed.

**Comment by alexolog** [comment]
What happened?

The current implementation in staging is the worst of all worlds.

- Now I have to select **three (four if using different APIs)** different dropdowns:
	1. API/Source
	2. Proxy
	3. Preset
- There is no connection between preset and connection
- There was no migrating, everything needs to be set up from scratch

Both the quick-preset and the kingbased options were better!

**Comment by Cohee1207** [comment]
@alexolog the only thing that was changed from @kingbased implementation is the position of the UI element. Everything else is merged verbatim, so I can't see why it's better if it's exactly the same. The code that was proposed in #1751 had no migration procedures for existing presets.

**Comment by Cohee1207** [comment]
> There is no connection between preset and connection

By the way, this is not true. API type and selected model are still a part of Chat Completion presets. Nothing was changed in that regard in staging.

**Comment by alexolog** [comment]
The kingbased solution had a connection between the preset and the proxy.

**Comment by Cohee1207** [comment]
You can check the code and all of the commits. The selected proxy preset is not a part of the settings preset.

https://github.com/SillyTavern/SillyTavern/pull/1751/files

**Comment by alexolog** [comment]
> > There is no connection between preset and connection
> 
> By the way, this is not true. API type and selected model are still a part of Chat Completion presets. Nothing was changed in that regard in staging.

If that is the case, then it did not solve my issue at all

Here is the use-case:

I am testing multiple presets, including sliders, prompts, jailbreaks, etc.
I tweak them often, with multiple cards, to try to optimize them.
I try to make them work with several models on multiple APIs (GPT, Claude, Mistral, Gemini)
I use several reverse proxies for access and switch between them often

With this, I still have to maintain multiple copies of practically the same preset for different proxies/keys and sync between them, or jump through hoops every time I want to switch to a different proxy.

And the connection between the proxy and the preset, if still present, is no longer obvious.

Now, if you don't want to decouple presets from connections at this time, I can understand that.
But at least make the connections behave like the quick settings you proposed earlier, so that a proxy entry will automatically change the API/Source to the one that the proxy is compatible with.

Thank you!

**Comment by Cohee1207** [comment]
> Now, if you don't want to decouple presets from connections at this time, I can understand that.

You can see in this exact thread why this idea wasn't liked by those who voted against the decoupling.

**Comment by alexolog** [comment]
> > Now, if you don't want to decouple presets from connections at this time, I can understand that.
> 
> You can see in this exact thread why this idea wasn't liked by those who voted against the decoupling.

And I did say I understand that, and accepted it.

What I am asking to change is to couple the proxy with the API/Source.
A proxy for Anthropic will not work for OpenAI, so If I switch from a Claude-specific proxy to a GPT-specific one, it should change the source automatically (like your "quick connect" did).

Surely this is not controversial.

**Comment by Cohee1207** [comment]
I suspect that every little decision made around proxy use is controversial. I'm more than sure that if I make this change, someone will post an angry message telling that this broke everything. So overly cautious approach is preferred.

**Comment by cunnymessiah** [comment]
@alexolog can you show me your preset list because i'm not really sure i understand still. are you saying you have like a universal preset for all models or something and you don't want to be forced to switch the completion source everytime you want to change the proxy?

> A proxy for Anthropic will not work for OpenAI, so If I switch from a Claude-specific proxy to a GPT-specific one, it should change the source automatically

usually people have presets where the same will apply (gpt preset 1 won't perform on claude as well as claude preset 2 for example) so every time they switch proxy provider, they will go and switch preset too, which will switch the chat completions source and model automatically. now if you had a universal preset that wouldn't be the case because you're not switching preset, but i don't think it would require any extra work. you'd still be changing two dropdowns, only instead of preset it's chat completion source now. and with cohee's change those dropdowns are now right next to eachother in the same menu so i don't really get the problem.

**Comment by alexolog** [comment]
@kingbased let me ask you the opposite question: is there any reason for a proxy entry not to be associated with a source?

**Comment by alexolog** [comment]
> I suspect that every little decision made around proxy use is controversial. I'm more than sure that if I make this change, someone will post an angry message telling that this broke everything. So overly cautious approach is preferred.

That would be the case if proxies could work different completion sources from the same endpoint.  I am not aware of any that can do that.

**Comment by alexolog** [comment]
Another issue:

1. Select Preset1
2. Save the proxy info as Proxy1
3. Select Preset2
4. Save the proxy info as Proxy2
5. Select Preset1 again
6. The connections tab still shows the name of Proxy2 but with the data pf Proxy1, which is extremely misleading, and also problematic, because if the Proxy1 key changes (old key ran out of quota) and I enter and save it, it will overwrite the Proxy2 settings.

In effect, if I want to use multiple proxies with the same preset (same completion source), I don't know which proxy I am on.

**Comment by cunnymessiah** [comment]
> let me ask you the opposite question: is there any reason for a proxy entry not to be associated with a source?

not really, the reason why i and so many others disliked Cohee's changes so much is that the decoupling caused issues since chat presets no longer held a model which was a major problem, and the migration hack just caused more hassle and upkeep, it changed a simple addition into a preset rework.

if you want proxies to hold a completion source and model i don't really see an issue with that and it would be extremely simple to add. would you like me to do that now? i didn't do it in the first place because of the prior assumption, we have claude and gpt presets. if someone wants to change proxy endpoint to the opposite model, they would also change the preset for that model because their claude preset won't work as well on the opposing model and through that preset change the chat completion source and model would be switched to the right one. these are proxy presets after all, not proxy and model presets, and the current implementation solved the issue it was intending to solve.

> maintain multiple copies of practically the same preset for different proxies/keys

i also don't get this previous statement, proxies are completely removed from the preset now. there would be 0 point in keeping multiple copies of the preset because the proxy data wouldn't even be saved to the preset. you would be saving the same preset with 0 changes.

>Another issue:

>Select Preset1
>Save the proxy info as Proxy1
>Select Preset2
>Save the proxy info as Proxy2
>Select Preset1 again
>The connections tab still shows the name of Proxy2 but with the data pf Proxy1, which is extremely misleading, and also dangerous, because if the Proxy1 key changes (old key ran out of quota) and I enter and save it, it will overwrite the Proxy2 settings.

i don't think you understand that proxies are no longer associated with presets, they're two different things and should be treated as such. proxies have their own presets, you "saving" a chat completion preset will have no bearing on the currently selected proxy. proxies have their own unrelated presets that only hold the proxy url and password.

again i would like a list of your chat completion presets because i'm struggling to understand what is wrong. it sounds like you're using the feature under wrong assumptions.

i will expand on this and tell you how things have changed

before this change you had to have the following presets all under the chat completion presets
- gpt preset 1
- gpt preset 2
- gpt preset 3
- claude preset 1
- claude preset 2
- claude preset 3
- gpt preset 1 (proxy 1)
- gpt preset 2 (proxy 1)
- gpt preset 3 (proxy 1)
- claude preset 1 (proxy 1)
- claude preset 2 (proxy 1)
- claude preset 3 (proxy 1)
- gpt preset 1 (proxy 2)
- gpt preset 2 (proxy 2)
- gpt preset 3 (proxy 2)
- claude preset 1 (proxy 2)
- claude preset 2 (proxy 2)
- claude preset 3 (proxy 2)

now you have
- gpt preset 1
- gpt preset 2
- gpt preset 3
- claude preset 1
- claude preset 2
- claude preset 3

and under a SECOND dropdown you have
- proxy1
- proxy2
- None (no proxy)

if you want to switch proxy, you go to the appropriate dropdown and switch the proxy. if proxy 1 and proxy 2 have a different endpoint (/anthropic or /openai) then it would also make sense to switch from claude preset x to gpt preset x because they are presets for different models, and then your completion source would be changed. the only issue I can tell is that you're using a universal preset for both models and thus skipping the preset selection step which would change your model over. if so, then just change the completion source manually? like the dropdown is right above your proxy settings. it's no extra work compared to people who don't have a universal preset.

> In effect, if I want to use multiple proxies with the same preset (same completion source), I don't know which proxy I am on.

you're on the proxy you selected last??? again there is 0 bearing on the current proxy based on what chat completion preset you select.

EDIT: hold on just a minute, i think i see what the issue is.

**Comment by cunnymessiah** [comment]
@alexolog try pulling the proxypreset branch on my fork. it should fix the bug where the proxy url/pass wasn't actually decoupled from the chat completion preset and was causing the issue where you didn't know what proxy was selected. that was unintentional, thanks for pointing that out and making me look. if you're still having issues we can further discuss saving model/completion source details to the proxy preset.

**Comment by alexolog** [comment]
The content of my presets is irrelevant to the discussion.

> i don't think you understand that proxies are no longer associated with presets, they're two different things and should be treated as such.

When I switch from one chat chat completion preset to another, the URL and password of the proxy changes as well (like it did before the change, but on a different page).  How is it not "association"?

> the reason why i and so many others disliked Cohee's changes so much is that the decoupling caused issues [...]
> proxies are no longer associated with presets, they're two different things

These two statements are in direct opposition to each other.
If two things are coupled, then they are associated by definition.

> i will expand on this and tell you how things have changed

I will annotate in brackets

> now you have
>     * gpt preset 1 [=gpt1]
>     * gpt preset 2 [=gpt2]
>     * gpt preset 3 [=gpt3]
> 
> and under a SECOND dropdown you have
>     * proxy1 [url1, key1]
>     * proxy2 [url2, key2]

1. I'm on **gpt1**
2. I select **proxy1**
3. I tweak **gpt1** and save it (it gets coupled with **proxy1**)
4. I switch to **gpt2** to see how it works
5. I switch **proxy2** (because proxy1 got slow)
6. I decide that gpt2 is not working well with this chat and switch back to **gpt1**

> you're on the proxy you selected last???

You'd think so.

When I open the "connections" tab, under "reverse proxy" it will show:
Proxy Presets: **proxy2** (last selected, did not change)
Proxy Name: **proxy2** (last selected, did not change)
Proxy Server URL: **url1** (belonging to proxy1, changed because of coupling)
Proxy Password: **key1** (belonging to proxy1, changed because of coupling)

Do you see the problem?

And yes, that sequence of steps is something that perform very often

**Comment by Spacellary** [comment]
I'd never expect the proxy discussion to get so intense and for these reasons 😅

**Comment by alexolog** [comment]
> @alexolog try pulling the proxypreset branch on my fork. it should fix the bug where the proxy url/pass wasn't actually decoupled from the chat completion preset and was causing the issue where you didn't know what proxy was selected. that was unintentional, thanks for pointing that out and making me look.

Ah, timing :)
Ignore the long-winded post above.

Can it be merged into staging?

> if you're still having issues we can further discuss saving model/completion source details to the proxy preset.

It's a separate, unrelated issue.

I'd like the proxy preset to also save:
* API/Source - because proxies are single-souce
* Model - because the OpenAI source always pre-selects gpt-3.5-turbo even when the proxy does not support it

Thank you!

**Comment by cunnymessiah** [comment]
> I'd never expect the proxy discussion to get so intense and for these reasons 😅

yeah i don't know what happened haha, this was initially just meant to be a simple change, not sure how it garnered so much attention.

@Cohee1207 you should probably pull that latest commit in.

**Comment by alexolog** [comment]
@kingbased, I edited my post above.

This discussion was a positive thing, as it helped discover a bug.
(One that I thought was an intentional feature)

**Comment by alexolog** [comment]
Another misfeature found:
Please trim spaces from proxy names.
I had [`proxy 1`] and [`proxy 1 `] by mistake

**Comment by alexolog** [comment]
Actually, it's worse.
I got two entries with exactly the same name:

image

But when I tried to remove one, it removed both!

**Comment by alexolog** [comment]
Oh, and one more thing, please sort the entries alphabetically

**Comment by cunnymessiah** [comment]
Alright give me one hour, I'll clear this all up in a way that hopefully appeases everybody

**Comment by alexolog** [comment]
One more thing:
Some models and/or proxies use a "Custom (OpenAI-compatible) endpoints, but there is no way to save them since the proxy settings are not implemented for that option.
Previously, when the proxies were coupled to the settings, they could be saved, but how can it work now?

**Comment by cunnymessiah** [comment]
see if what is pushed to my fork works for you now. obviously try and test for bugs because i only did minimal.

> Some models and/or proxies use a "Custom (OpenAI-compatible) endpoints, but there is no way to save them since the proxy settings are not implemented for that option.

are you saying that the reverse proxy drawer for that completion source is straight up missing now but was there before? odd, i could have sworn the condition for rendering the proxy div was having the source be either mistral, openai or anthropic so it should have never shown up. either way i didn't touch that, Cohee was responsible for moving it around.

**Comment by Cohee1207** [comment]
> Some models and/or proxies use a "Custom (OpenAI-compatible) endpoints, but there is no way to save them since the proxy settings are not implemented for that option.

It was never implemented for that source, because this wouldn't make much sense. This API type has a straight input for the endpoint URL on its own, without the proxy paradigm being present.

**Comment by cunnymessiah** [comment]
agreed with cohee

anyway @Cohee1207 i think what i've got now should make everybody happy, for people who had no problem with the way things were nothing should change for them since this is just an addition, and for those that want to save a source with their proxy they now have the option to. thoughts?

**Comment by Cohee1207** [comment]
Just to be clear, what are the changes:

1. Alphabetical sorting and space trimming - that's just UX, will be fine in any case.
2. Removing proxy and password from chat completion presets? As in not loaded and saved anymore, and not auto-migrated to the new dropdown?

**Comment by cunnymessiah** [comment]
>Removing proxy and password from chat completion presets

no no, nothing is removed. like i said this is just an addition. the user will now have the option to save their current source and model to the proxy settings if they have the checkbox ticked. the model and source is still in the same dropdown and still saved to the chat completion preset. proxies in the config now look like this
```
{
            "name": "Local",
            "url": "http://127.0.0.1:7100/proxy/openai",
            "password": "...",
            "model": "",
            "source": "",
            "save_source": false
        },
```
if save_source is true then their selected model and completion source will be saved and applied when they select that proxy. kind of like an override

**Comment by Cohee1207** [comment]
Okay, if that's an option, it should be fine.

**Comment by alexolog** [comment]
> > Removing proxy and password from chat completion presets
> 
> no no, nothing is removed. like i said this is just an addition. the user will now have the option to save their current source and model to the proxy settings if they have the checkbox ticked. the model and source is still in the same dropdown and still saved to the chat completion preset. 

Now I'm confused.

I was under the impression that changing a completion preset would no longer change the proxy setting (decoupling).  Is it not the case?

**Comment by alexolog** [comment]
> > Some models and/or proxies use a "Custom (OpenAI-compatible) endpoints, but there is no way to save them since the proxy settings are not implemented for that option.
> 
> It was never implemented for that source, because this wouldn't make much sense. This API type has a straight input for the endpoint URL on its own, without the proxy paradigm being present.

If I have several different connections that use that source with different urls/keys, how do I save them?

**Comment by Cohee1207** [comment]
> If I have several different connections that use that source with different urls/keys, how do I save them?

Already mentioned here, but all of the custom endpoint settings go to setting presets. However, this topic derails the thread.

**Comment by cunnymessiah** [comment]
@alexolog 
> I was under the impression that changing a completion preset would no longer change the proxy setting (decoupling). Is it not the case?

it doesn't and it never did or will. my latest change addresses your complaint

> I'd like the proxy preset to also save:
> - API/Source - because proxies are single-souce
> - Model - because the OpenAI source always pre-selects gpt-3.5-turbo even when the proxy does not support it

now it does do the above if you select the appropriate checkbox when saving your proxy preset (completely optional). give it a try and tell me what you think.

**Comment by alexolog** [comment]
> > If I have several different connections that use that source with different urls/keys, how do I save them?
> 
> Already mentioned here, but all of the custom endpoint settings go to setting presets. However, this topic derails the thread.

@Cohee1207, my understanding is that @kingbased is removing the association between setting presets and connections, as stated [here](https://github.com/SillyTavern/SillyTavern/pull/1753#issuecomment-1920562476) and [here](https://github.com/SillyTavern/SillyTavern/pull/1753#issuecomment-1921804707).

Or are the connections (API/Source) saved with the setting presets, just not the proxies?  I may be a little confused.

In case the connections are not saved with the presets, then it is a problem as custom endpoint settings will not be saved anywhere.  If they are, then I apologize for misunderstanding.

In any case, I believe that discussing the change and its effects is very much on topic.

**Comment by Cohee1207** [comment]
This topic affects proxies alone, not the custom endpoint type. This one wasn't affected by any of the changes. What is proposed to add is to save model and API type to proxy presets, which custom API type does not support.

**Comment by cunnymessiah** [comment]
if you're fine with the changes then i'm happy with the state it's in currently @Cohee1207 

would you like to merge the two commits just so we can wrap up this whole discussion?

**Comment by alexolog** [comment]
I'll play with it over the weekend and if I see anything I'll open another issue

**Comment by Cohee1207** [comment]
I've created an additional PR for these changes. One question, once again, there is no migration, this is not going to load proxies from the Chat Completion setting presets that were already saved before that change. People are going to be angry about it, someone will lose their saved data and will come with complaints.

**Comment by cunnymessiah** [comment]
> One question, once again, there is no migration

there never was intended to be an automatic migration with my changes, i always intended it for it to be a manual process. it sort of has to be because we're asking the user to name their new proxy presets. we can't do that automatically for them without it being generic (proxy1 proxy2 etc) or just basing it off of the URL, which isn't ideal because of some people deciding to host their proxy through a cloudflare tunnel where the URL isn't constant. it was only due to an oversight on my part that the proxy would still be set upon choosing a chat completion preset, that was never intentional.

however you are right, there might be the small minority that doesn't have access to their user token anymore for whatever reason. perhaps it will be better to keep the proxy url/password field in the chat preset file, but do nothing with it? just for archival purpose so those people can be pointed to opening their chat completion preset in a text editor to retrieve their lost details.

**Comment by alexolog** [comment]
> perhaps it will be better to keep the proxy url/password field in the chat preset file, but do nothing with it? just for archival purpose so those people can be pointed to opening their chat completion preset in a text editor to retrieve their lost details.

It will also allow them to revert to an older version.

**Comment by LurkerHub** [comment]
> I'd like the proxy preset to also save:
>     * API/Source - because proxies are single-souce
>     * Model - because the OpenAI source always pre-selects gpt-3.5-turbo even when the proxy does not support it

I think you're looking at it from the wrong viewpoint.

Instead of the proxy saving/changing the source, the drop-down should only list proxies compatible with the currently selected source.

**Comment by underscorex86** [comment]
Wouldn't the simplest implementation that makes everyone happy be:

- Build on the existing Staging setup where a user can save a reverse proxy link to the chat completions in the API menu.

- Have an additional dropdown in AI response configuration menu that reflects the same reverse proxies that are configured in AI response config menu. I don't think it's a design blasphemy to have the same dropdown in multiple locations.

- Have ai response config presets save the state of the drop down for reverse proxies selected.

This allows users to keep their prompting presets distinct from proxy settings, and also mix and match from the same menu.

Ofcourse the most modular approach would be just give users a Slash Command for /proxy or whatever, so they can create their own batched commands for /api | /preset | /proxy and save them as Quick Reply buttons. No more UI discussions, let the users figure their own shit out.

**Comment by LurkerHub** [comment]
I used to connect to AI21 via a proxy, but that option does not seem to be available anymore.
Can it be brought back?

**Comment by Cohee1207** [comment]
It was never an option. Also let's stop posting in a dead thread.

**Pull request closed without merging**
