### PR TITLE
Allow mobile swipes with open panels if focused

### LINKED ISSUE #2753: [BUG] Mobile Swipe Broken with Token Probibilities Modal Open
### Environment

🪟 Windows

### System

Andorid/firefox

### Version

1.12.5

### Desktop Information

Hosting via pc, st on local network. 

### Describe the problem

When Token Probabilities page is enabled and the box is on screen, swiping on mobile doesn't do anything. On PC, arrows and clicking both work, but on mobile only clicking the arrow works.

### Additional info

_No response_

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) important

### PR DESCRIPTION
**Pull request by Wolfsblvt**
This is a bugfix in reference to #2753.
Before, swipe gestures were disabled when any relevant panel was open, any popup was open, or a floating prompt was open.
A few panels might be small enough, especially the floating prompts like Token Probabilities, so now swiping will work even with those open, as long as the focus is **inside** the sheld.

Note: If you just opened Token Probabilities and try to swipe, it doesn't work. Swipe gesture doesn't set focus, you have to *tap* inside the sheld at least once. That is exactly how I'd expect it though.

- Allow mobile swipe gestures when sheld is focused, ignoring open panels or floating prompts present now
- Fixes #2753

## Checklist:

- [x] I have read the [Contributing guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

### CODE REVIEW

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
Kinda janky. For me it disables swipe gestures entirely until I'm focused into the chat input textarea. iOS 18 beta in PWA mode.

**Comment by Wolfsblvt** [comment]
Try again. I was just too dumb to google how the event works (which we have added as a lib) and that it has the element already.

Not gonna setup mobile to test myself though. I am very happy to not have ST on my phone.

**Review by Cohee1207 — APPROVED** [review]
Appears to be working now.

**Comment by Vibecoder9000** [comment]
> Try again. I was just too dumb to google how the event works (which we have added as a lib) and that it has the element already.
> 
> Not gonna setup mobile to test myself though. I am very happy to not have ST on my phone.

You don't need terminux, it's fairly simple to use remote-link or just visit your pc's url. Thanks for the fix btw

**Comment by Wolfsblvt** [comment]
> You don't need terminux, it's fairly simple to use remote-link or just visit your pc's url.

I know. I explicitly **don't** want this. Like I said, I am **happy** that ST is not on my phone. I don't want to use it there, and I don't like using anything complex on a phone screen size and phone keyboard.

**Comment by Vibecoder9000** [comment]
> > You don't need terminux, it's fairly simple to use remote-link or just visit your pc's url.
> 
> I know. I explicitly **don't** want this. Like I said, I am **happy** that ST is not on my phone. I don't want to use it there, and I don't like using anything complex on a phone screen size and phone keyboard.

In that case, very inpressive developing for a platform that you don't actually test for. Wow.

**Pull request merged**
