### PR TITLE
Personas facelift

### PR DESCRIPTION
**Pull request by Cohee1207**
image

### CODE REVIEW

**Comment by Spacellary** [comment]
Honestly, looks great! 👏

**Comment by ContinuumOperand** [comment]
@Cohee1207 Is that custom CSS you're using for your UI BTW? Curious if that's available anywhere, if you don't mind sharing.

**Comment by Cohee1207** [comment]
The screenshot is not mine. You can find the "Discord theme" in (sic) SillyTavern Discord.

**Comment by Cohee1207** [comment]
@ContinuumOperand https://github.com/nyxkrage/st-discord-inspired
Nevermind, here's a GitHub repo

**Pull request merged**
