### PR TITLE
Use names in place of roles for ChatML and LLama-3-Instruct

### PR DESCRIPTION
**Pull request by HiroseKoichi**
I have found a way to incorporate names into the base ChatML template. Previously, I thought that the base roles, user and assistant, were required since the model was trained exclusively with those, but that's not actually the case. The system, tool, or any other role trained for a specific purpose cannot be changed, but the user and assistant roles are not special in any way and can be changed without issue.

The problem was actually that if the name contained spaces, it would give poor-quality output. The solution is to wrap the name in something, whether it's parenthesis (), brackets [], or curly brackets {}, and it will work perfectly fine. This is not exclusive to ChatML either; I have tested it with LLama-3-Instruct, which uses the same role system, and it also works the same way.

In addition, I have disabled the "Include Names" options as well as "Force for Group Chats and Personas." For the actual templates, the changes are as follows:

ChatML

`<|im_start|>user` --> `<|im_start|>[{{user}}]`
`<|im_start|>assistant` --> `<|im_start|>[{{char}}]`

LLama-3-Instruct

`<|start_header_id|>user<|end_header_id|>` --> `<|start_header_id|>[{{user}}]<|end_header_id|>`
`<|start_header_id|>assistant<|end_header_id|>` --> `<|start_header_id|>[{{char}}]<|end_header_id|>`

I have personally been using it this way for a few months now, and I can say with certainty that it's significantly better than the "Include Names" option. The only reason I haven't made this pull request until now is because I couldn't do proper tests because ChatML was broken until recently. I don't even have to give an example of a before and after output because, in my experience, the difference is just that obvious.

---

With all of that said, I did discover an issue with group chats and personas that should probably be fixed before this gets merged: the output of macros in the instruct template are not saved to each message. This means that, if you're using group chats or personas, all previous messages will be attributed to the current speaker.

Here is what I mean:

```
<|im_start|>[Persona Two]            <-- Past message is attributed to the wrong person
{Persona One's message}<|im_end|>
<|im_start|>[Character Two]          <-- Past message is attributed to the wrong person
{Character One's message}<|im_end|>
<|im_start|>[Character Two]          <-- Current Speaker
{Character Two's message}<|im_end|>
<|im_start|>[Persona Two]            <-- Current Speaker
{Persona Two's message}<|im_end|>
```

The "Include Names" option already has the desired behavior, so it could probably be adapted for this use case; maybe changing its behavior so that when the `{{user}}` and `{{char}}` macros are present in the instruct template, it moves the persona and character names to their respective locations.

For example, if I replaced `user` with `{{user}}`, `<|im_start|>user` --> `<|im_start|>{{user}}`, and `assistant` with `{{char}}`, `<|im_start|>assistant` --> `<|im_start|>{{char}}`

It would look like this
```
<|im_start|>Hirose Koichi
{Prompt}<|im_end|>

<|im_start|>Character Name
{Prompt}<|im_end|>
```

Instead of this
```
<|im_start|>user
Hirose Koichi: {Prompt}<|im_end|>

<|im_start|>assistant
Character Name: {Prompt}<|im_end|>
```

### CODE REVIEW

**Review by Cohee1207 — CHANGES_REQUESTED** [review]
1. Don't change the base template. Make a variant of it under a different name. Don't forget to update content index file. 
2. Don't use `{{user}}` and `{{char}}`, they don't work well with personas and groups. Use `{{name}}` instead.

**Comment by HiroseKoichi** [comment]
> 1. Don't change the base template. Make a variant of it under a different name. Don't forget to update content index file.

Didn't even think to keep the originals. Done.

>     2. Don't use `{{user}}` and `{{char}}`, they don't work well with personas and groups. Use `{{name}}` instead.

I thought I had searched through the docs, but i guess not well enough; I didn't even know `{{name}}` was a macro. I'll have to see what else I missed.

**Comment by Cohee1207** [comment]
>I'll have to see what else I missed.

File extensions are missing.

**Comment by HiroseKoichi** [comment]
> > I'll have to see what else I missed.
> 
> File extensions are missing.

Fixed.

**Review by Cohee1207 — APPROVED** [review]

**Pull request merged**
