### PR TITLE
improved instruct mode sequences and UI

### PR DESCRIPTION
**Pull request by WolframRavenwolf**
Llama 2 Chat's output sequence having a space at the beginning of the line kept bugging me, so I revised the whole thing:

- I've added a First Output Sequence so we can specify a different string from the normal Output Sequence for the first (character's) message.
- Additionally, I split the System Sequence into a Prefix and Suffix field, reverting the unique {{sys}} replacement handling I added yesterday.
- Now it's a simple System Sequence Prefix + System Prompt + System Sequence Suffix logic without obscure replacement strings.

~~**This PR is still WIP, so please don't merge yet!** I'm just putting it up here so you can check it early before I finish it...~~

**TODOs:**

- ✅ Properly naming inputs and i18n (e. g. system_sequence -> system_sequence_prefix)
- ✅ Renaming "forceLastOutputSequence" since it also applies to the first, maybe "forceFirstOrLastOutputSequence", "forceSecondaryOutputSequence", or something like that
- ✅ Update all presets and default config with newly added/renamed settings
- ✅ IDEA: Can we automatically expand the textareas to show full contents instead of single-line (had to shrinkt them for layout reasons)?

### CODE REVIEW

**Comment by Cohee1207** [comment]
> IDEA: Can we automatically expand the textareas to show full contents instead of single-line (had to shrinkt them for layout reasons)?

Yes, we have some script functions that do that on page init - basically need to set the height to match the scroll height. It is not very reliable, but should try applying this. 
https://github.com/SillyTavern/SillyTavern/blob/staging/public/scripts/utils.js#L383

**Comment by WolframRavenwolf** [comment]
**Improved Advanced Formatting UI**

Implemented the idea and assorted changes for a better organized and user-friendlier UI:

- Auto Set Height: Automatically set height of Context Template, Instruct Mode, and Instruct Mode Sequences textareas to show their full contents.
- Instruct Mode Sequences: Organize sequences inside an "Instruct Mode Sequences" drawer.
- Empty Sequence Placeholder: Added placeholder em-dash to make it easier to differentiate empty textareas from those with only whitespace.

Now back to the original TODOs... ;)

**Comment by WolframRavenwolf** [comment]
**Force Output Sequence (First or Last)**

- Changed "forceLastOutputSequence" to allow first or last sequence to be forced.

**Comment by WolframRavenwolf** [comment]
**first_output_sequence and system_sequence_prefix**

- Updated UI and all instruct mode presets with first_output_sequence and system_sequence_prefix.

**Comment by WolframRavenwolf** [comment]
**Updated i18n for new and changed strings**

- Added translations for the new and changed strings: Instruct Mode Sequences, First Output Sequence, Last Output Sequence, System Sequence Prefix, and System Sequence Suffix.

That's the last TODO done. WIP status is now resolved from my point of view.

Pretty happy with it now! 🥳 Hope you like the little Instruct Mode improvements, @Cohee1207 !

**Comment by Cohee1207** [comment]
Looking into it.

Also I got some feedback regarding resetting context templates to default. It was confusing why it always resets to a default.

**Comment by Cohee1207** [comment]
Maybe I'll add the same function to set a default context template as for instruct preset

**Comment by WolframRavenwolf** [comment]
Yes, the context template could benefit from the same controls as the instruct mode presets: Favoriting, saving/updating, adding, exporting, importing, maybe even deleting. And with a template favorited, it should switch to that instead of Default when switching presets.

**Comment by Cohee1207** [comment]
Eventually, it will be done. You've got to start small.
I tested some cases in this PR, works fine. Can merge now.

**Comment by WolframRavenwolf** [comment]
[context template preset manager by StefanDanielSchwarz · Pull Request #1023 · SillyTavern/SillyTavern](https://github.com/SillyTavern/SillyTavern/pull/1023)

**Pull request merged**
