### PR TITLE
Call processHotkeys debounced (RossAscends-mods)

### PR DESCRIPTION
**Pull request by LenAnderson**
Huge performance boost when typing fast (or holding down a key) in the message input box.

### CODE REVIEW

**Comment by Cohee1207** [comment]
This makes sending with Enter laggy visually. You might want to make a key process immediately if it's an Enter, or debounce otherwise.

**Comment by LenAnderson** [comment]
> This makes sending with Enter laggy visually. You might want to make a key process immediately if it's an Enter, or debounce otherwise.

Yes, that was annoying.

Made some tweaks. `processHotkeys` is no longer debounced, which also takes care of the send with enter thing. Instead I added early returns to each activated hotkey and replaced some of the dom-queries and jQuery checks in the conditions with variables and vanilla JS. That helped a lot.

The second big offender was the other input-listener that resizes the textarea and saves the value to localStorage.
The UI redraw from shrinking the textarea to its min-height and then re-expanding it on every input was killing performance. And the constant localStorage operations did not help.
Now input saving is done debounced.
And the autofit has been changed to only grow immediately (since that only requires a single resize, and is now limited to happen only when necessary), while shrinking happens debounced. Of course that means that if you hold down the delete or backspace key to delete a lot of text the textarea will stay at its full size until you let go of the key. But I think that is a happy compromise.

**Comment by Cohee1207** [comment]
Now the input doesn't shrink after a long message is being sent.

**Comment by LenAnderson** [comment]
Looks like the input event after sending is fired in a way that only jQuery catches it... Should be fixed.

**Comment by Cohee1207** [comment]
I tried to visually delag it on sending by autofitting if the input is empty, but there's still an unfixed bug with removing text from the textarea: it won't shrink the last removed line until you erase the penultimate line good enough. This happens in staging as well so I don't think it's an effect of the refactoring.

**Comment by Cohee1207** [comment]
Disregard the last message. Seems to be a quirk of using ST at 90% scaling permanently.

**Pull request merged**
