### PR TITLE
Better input inject Quick Reply

### PR DESCRIPTION
**Pull request by IkariDevGIT**
You can now do {{input}} to inject the user input into everywhere in the message, this could be really useful for something like this:
grafik

### CODE REVIEW

**Comment by Cohee1207** [comment]
Could you explain how exactly it works?

**Comment by IkariDevGIT** [comment]
> Could you explain how exactly it works?

Of course, previously the input(where you type your message you wanna send to a char) was automatically pre/appended(changable with "Place Quick-reply before the Prompt" checkbox). Now you can disable it being added intirely with the new checkbox "AutoInputInject", and you can place it where you want like seen in the picture above.

**Comment by Cohee1207** [comment]
I still don't get it.

**Comment by IkariDevGIT** [comment]
> I still don't get it.

Now i dont get why you dont get it lol

**Comment by IkariDevGIT** [comment]
> I still don't get it.

Previously, the input field where you type your message to send to a character would automatically be added before or after the message prompt, depending on your preference (adjustable with the "Place Quick-reply before the Prompt" checkbox). Now, with the introduction of the "AutoInputInject" checkbox, you have the option to entirely disable this automatic placement and manually position it as desired with {{input}}, or as shown in the image above.

**Comment by Cohee1207** [comment]
I don't think it should be a global setting. Maybe add it as a per-command option instead?

**Comment by IkariDevGIT** [comment]
> I don't think it should be a global setting. Maybe add it as a per-command option instead?

i personally think it would just clutter up the UI, and if we did make it a per-command option we would need to do the same with "Place Quick-reply before the Prompt" which would clutter it even more.. so i dont think its that important

**Pull request merged**
