### PR TITLE
Feature - /desc command

### PR DESCRIPTION
**Pull request by vbdev537**
This modification includes the /desc command in the code allowing the user to ask the AI to describe something in the scenario.

Currently there is already the /sys command that allows the user to send a message as if he were the system, but this command does not work very well to ask the AI to describe things as it is completely ignored because the Character Note appears right after the system message. With the changes I made, the user will have a command called /desc that will allow him to ask the AI to describe something in the scene, such as an object, the appearance of a person, etc...
Below I will show an example of the difference between using /sys and /desc by asking the AI to describe to me what an object looks like.

Here I sent the command "/sys Describe what the orb looks like?" so that it describes the Orb that was found by the user.

image

As you can see, the command was almost completely ignored and the AI responded to the message as if it were the char continuing the chat instead of telling what the orb looks like.

In this other image I sent the command "/desc What the orb looks like?" with the same objective, (The word Describe was not placed because it is already included automatically)

image

As it was possible to see with the use of the /desc command the AI explained exactly what was requested, perfectly describing how the orb looked like.

Unfortunately I don't have access to any other api besides Poe, and because of that I couldn't do it for others apis, so at the moment it's only available for Poe.

### CODE REVIEW

**Comment by vbdev537** [comment]
Unfortunately, the tests I did here didn't turn out very well, the AI ignores what I asked for as in the image below

```/sysgen [Describe what the orb looks like]```
image

**Comment by vbdev537** [comment]
> Try something like [OOC: prompt] or [System note: prompt]


Unfortunately I tested the two you asked me on 3 different characters and the same thing happened, the AI continues as if it were the character and does not describe anything.

However, I discovered some things that may be causing this is because at the end of the prompt sent to the AI, "{{char}}:" is included at the end of the message, and another reason for this is the lack of a prompt type what is used no impersonation and character note. When making these 2 changes he does what was asked.

image

**Comment by vbdev537** [comment]
It's working perfectly now.

I think it would be interesting to add a new option in the regex for this new command.

**Comment by bdashore3** [comment]
A new option isn't required as Regex formatting already occurs on this command. Just use the `/sys command` checkbox.

**Comment by vbdev537** [comment]
> A new option isn't required as Regex formatting already occurs on this command. Just use the `/sys command` checkbox.

Yes, the regex is running in the command but only in the response received by the AI and not in the text that is sent by the command.

**Pull request closed without merging**
