### PR TITLE
Create update-i18n.yaml

### PR DESCRIPTION
**Pull request by steve02081504**

### CODE REVIEW

**Comment by Cohee1207** [comment]
A pipeline is not a bad idea, but I'd rather run it once per release than after every staging commit. Or perhaps manually per request

**Comment by steve02081504** [comment]
Can you check https://github.com/SillyTavern/SillyTavern-i18n/pull/3 first when you have time? I need the changes in there to make sure changes is in order and doesn't update the `en.json`

As for my reasons for choosing to check and update at every commit:
1. this CI will only commit new content when there are i18n related changes, only the initial change will be huge
2. following up on mechanical translations as early as possible can expose problems early enough for the translators to fix them.

What do you think?

**Comment by Cohee1207** [comment]
I'm voting against immediate updates since localizable texts can change rapidly during the development of new features. So i18n contributors may submit texts that are already outdated.

**Comment by steve02081504** [comment]
got it!
fixed in [`e6b7135` (#2342)](https://github.com/SillyTavern/SillyTavern/pull/2342/commits/e6b713500ace143ce1669ac34468d422fa74e78d)

**Pull request merged**
