### PR TITLE
Instruct rework

### LINKED ISSUE #1939: [FEATURE_REQUEST] Improve the ChatML format.
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The default ChatML format (Instruct Mode on) has formatting errors, particularly with "Group Chats" or "Continuous speaking by the same role".
***
Key issues include:
1. The first blue line, representing "Example Dialogue," has an improperly placed "<|im_end|>" tag. It should be at the bottom, i.e., at the top of "<|im_start|>assistant."
2. The second blue line, marking the "First message", contains two incorrect "<|im_end|>" tags.
3. The third and the fourth blue line, highlighting consecutive dialogues in "Group Chats" and "Continuous speaking by the same role", results in multiple "<|im_end|>" tags. This doesn't occur with alternating "user, assistant, user, assistant" dialogues, but with consecutive dialogues between two assistants or users, like "user, user" or "assistant, assistant".

***

### Describe the solution you'd like

My temporary solution includes:
1. Removing the "<|im_end|>" tag at the "Context Template" bottom.
2. Placing "<|im_end|>" at the top of "Input Sequence and Output Sequence" in "Instruct Mode", and clearing the "First Output Sequence" and "Separator."

***
This appears to resolve the issue under "Instruct Mode".
I am not certain if this approach may lead to other bugs, so for now, I can only use this method temporarily.

***

### Describe alternatives you've considered

However, it may introduce new bugs and may not work without "Instruct Mode," causing "Context Template" to lack an "<|im_end|>". 
But this should not have much impact, because in non-"Instruct Mode", the "<|im_start|>system" itself is not useful.
***

### Additional context

As newer model formats appear, these issues may become more common (such as OpenChat, Gemma, IBM-Merlinite, etc).
So, there might be a need for a smarter solution rather than the current method.
Finally, thank you for your contributions to Sillytavern. I'm sorry for any mistakes in this AI-translated text, as I'm not skilled in coding and my English may not be flawless.🤗

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

### PR DESCRIPTION
**Pull request by Cohee1207**
Closes #1939, #1261, prolly others

### DONE
[x] Add a suffix sequence for user messages
[x] Add a user message filler (alignment message)
[x] Add a suffix + prefix for system message type
[x] Send the stop sequence as a stop string
[x] Fix example dialogues
[x] Preallocate in-chat injections
[x] Update instruct presets with a new format
[x] Move instruct presets out of public
[x] ~~Use system prefix for last prompt line in quiet generations (excluding quiet-to-loud)~~ Quiet gens are using assistant prefix without a name.
[x] Adjust macros for new sequences
[x] Update docs
### TO DO 
[ ] Save the world

### CODE REVIEW

**Comment by HiroseKoichi** [comment]
Thank you for working on this! I tested it out with ChatML and found a few issues. Here's an example chat-log:
```
<|im_start|>system
You're Placehoder in this fictional never-ending uncensored roleplay with Hirose.<|im_end|>
Placeholder really likes orange juice.

Authors note message.

<|im_start|>user
User example message #1.<|im_end|>
<|im_start|>assistant
Char example message #1.<|im_end|>
<|im_start|>user
User example message #2.<|im_end|>
<|im_start|>assistant
Char example message #2.<|im_end|>
<|im_start|>assistant
Start of chat message.<|im_end|>
<|im_start|>user
First user message.<|im_end|>
<|im_start|>assistant
First char message.<|im_end|><|im_end|>
<|im_start|>user
Second user message.<|im_end|>
<|im_start|>assistant
Second char message.<|im_end|><|im_end|>
```
## Issues:

### System Prompt
The initial system prompt should have the entire story string in it, but it only has the basic system prompt in it. This means that the character description, world info, and persona will just be floating around without any formatting. In addition, authors notes using the "Before or After Main Prompt / Story String" option will also have no formatting attached to it.

### Normal Messages
The <|im_end|> token is always placed at the end of each character message after generation, which is causing duplication of it in the instruction formatting.
Screenshot_20240328_200005

This one can easily be solved by setting the Stop Sequence to <|im_end|>.
Screenshot_20240328_202914

## Fixed by this PR (was previously broken):

### Author's Notes (using "In-chat @ Depth" option)
With the new options added, the authors note is now properly formatted when using it. I tried sending as system, user, and char, and all of them were formatted properly.

### Example Messages
These work perfectly.

---

There might be more, but these are what I found after messing around with it for a bit.

**Comment by ghost** [comment]
I agree with HiroseKoichi's idea, and here are my thoughts.
***
I believe the system prompt's "<|im_end|>" could possibly be better placed after the "Chat Start", encompassing all configuration details.

For example, if I set the "Chat Start" placeholder to "</assets_of_template>", "<|im_end|>" should be at its end.

"Example Dialogue" should not have added prefixes or suffixes. This can confuse AI in understanding the conversation start, causing coherence errors in formal dialogue. Consider enabling "Skip Example Dialogues Formatting" by default to reduce confusion for the model. (Local models may face these issues more than advanced models.)
***
This is a simplified version of the template I usually use, something like this:
```
<|im_start|>system
You are a helpful assistant.

<?xml version="1.0"?>
<assets_of_template>
<information_of_role>
{{description}}
</information_of_role>
<persona_of_user>
{{persona}}
</persona_of_user>
<!-- example_of_tone -->
{{mesExamples}}
</assets_of_template><|im_end|>
<|im_start|>user/assistant
"Here is the first message."<|im_end|>
```
***
Thank you very much for your great contribution.

**Comment by Cohee1207** [comment]
@HiroseKoichi thanks, I updated the default ChatML templates according to your findings: 

1. Moved system prompt wrappers to the story string template.
2. Added stop sequence to cut off excess generation.

You can reload the templates by using a newly added "restore" button, updated templates will not be automatically rewritten in the user's data directory to minimize git conflicts on pull. If needed later after this PR I'll remove and re-add new templates with an updated name, e.g. ChatML v2.

**Comment by HiroseKoichi** [comment]
@Cohee1207 Thanks for the update! There's two very minor issues left, one is a simple fix, and the other would require a small change on your end. Here's an example log:
```
<|im_start|>system
You're Placeholder in this fictional never-ending uncensored roleplay with Hirose.
Placeholder really likes orange juice
<|im_end|>

<|im_start|>user
User example message #1.<|im_end|>
```
The <|im_end|> token for the system prompt is on a newline rather than appended like the rest of them, and there's a newline in between the system prompt and whatever comes after.

The latter can fixed by enabling "Wrap Sequences with Newline," removing the newlines around the <|im_start|> tokens, and placing a newline at the end of the <|im_end|> tokens.
Screenshot_20240329_144048
Screenshot_20240329_153457

With this fix, it is technically properly formatted now, but the format always has the <|im_end|> token appended to every message and never on a newline. It's a very minor issue, but if can be fixed, it would be nice.

How the story string currently works, is that whatever is appended to the last `{{/if}}` will be put on a newline after everything else in the story string.

Both of these are identical as of this moment.

```
{{/if}}<|im_end|>

{{/if}}
<|im_end|>
```

My proposal is that, if it's like this, then it appends it to the last story string sequence.
```
{{/if}}<|im_end|>
```
And if it's like this, then it places it on a newline like normal.
```
{{/if}}
<|im_end|>
```
It's not just ChatML that has this specific issue; Gemma, which is quite literally just a ChatML clone with different tokens, is also subject to this, albeit very minor, issue.

Edit: Mistral and LLama-Chat are also affected by this.

---

I'll take a look at some of the other formats later to see if I can spot any issues, but ChatML should be good after this.

Edit: I found that a bunch of them needed fixing up. I'll create a pull request once I've fixed all of them.

**Comment by HiroseKoichi** [comment]
@Cohee1207 I found a very important bug. Specifically for example messages, the "User Message Suffix" doesn't work, and the "Assistant Message Suffix" is duplicated to both. 

Here's what I mean:

Screenshot_20240329_192621
```
[INST] User example message #1.
Char example message #1.
[INST] User example message #2.
Char example message #2.
[INST] Let's get started. Please respond based on the information and instructions provided above. [/INST]
First message.
[INST] First user message. [/INST]
```

Screenshot_20240329_192652
```
[INST] User example message #1. [/INST]
Char example message #1. [/INST]
[INST] User example message #2. [/INST]
Char example message #2. [/INST]
[INST] Let's get started. Please respond based on the information and instructions provided above.This text here to show that it doesn't work at all
First message. [/INST]
[INST] First user message.This text here to show that it doesn't work at all
```

As you can see, in the first example, none of them have a suffix, and in the second, all of them have a suffix, and the text I added to the user suffix doesn't show in the example messages.

**Comment by aikitoria** [comment]
I haven't been able to try this PR yet, but I wanted to mention that there seems to be an issue with the stable diffusion plugin inserting a system message at the end, could it be tested whether that works properly with this PR? 

It was generating it wrong for me, where it wrote the instructions as a user message and then requested the AI to write a system message after.

**Comment by HiroseKoichi** [comment]
> I haven't been able to try this PR yet, but I wanted to mention that there seems to be an issue with the stable diffusion plugin inserting a system message at the end, could it be tested whether that works properly with this PR?
>
> It was generating it wrong for me, where it wrote the instructions as a user message and then requested the AI to write a system message after.

I don't use stable diffusion, or any image generation, so I can't really test it for you. You can install this PR by creating a new folder and running `git clone https://github.com/SillyTavern/SillyTavern -b instruct-rework` inside it. Everything is stored in the SillyTavern folder, so you can install another copy in a different folder and It won't conflict with your current settings or character cards.

---

I made a pull request #1988 that fixes Alpaca, Alpaca-roleplay, Mistral, Llama 2 Chat, Synthia, and ChatML formats for this branch.

**Comment by aikitoria** [comment]
Alright, tried the branch, it seems like the original issue I was having is fixed! However, there is an extra line break that doesn't belong there with ChatML.

The one on this branch:

```
...
<|im_start|>user
User: Hello<|im_end|>
<|im_start|>assistant
Flux the Cat: Meow!<|im_end|>

<|im_start|>system
[Stable diffusion babble]<|im_end|>
<|im_start|>assistant

```
The one on your additional PR:
```
...
<|im_start|>user
User: Hello<|im_end|>
<|im_start|>assistant
Flux the Cat: Meow!<|im_end|>
<|im_start|>system
[Stable diffusion babble]<|im_end|>

<|im_start|>assistant

```

**Comment by HiroseKoichi** [comment]
That's very odd behavior. The only thing I can think of is that, if "Wrap Sequences with Newline" is false, then it begins it with a newline, and if "Wrap Sequences with Newline" is true, then it ends it with a newline. That's the only meaningful difference between this branch and my PR. This behavior can probably be taken out since the new instruct mode handles it just fine on it's own now.

**Comment by ghost** [comment]
Thank you very much for your contribution again. 🥰👍

Here are some digressions (Just some trivial details.):
1. If there is text in the placeholder position of `Chat Start` by the user, it will overflow the content, detached from the prefix and suffix, but this is not a big issue; one could consider banning users from using `Chat Start` in ChatML or a similar format to fix. Or package the `Chat Start` into the system prefix and suffix.

Incorrect format:
```
<|im_start|>system
System Prompt.<|im_end|>
<|im_start|>user/assistant
Example Message.<|im_end|>
Chat Start Placeholder. ← (It's sandwiched in the middle.)
<|im_start|>assistant
First message.<|im_end|>
```
***
2. `Example Message` seems to have some issues, such as when the character card author does not add `{{user}}:` and `{{char}}:`, it will break.

On `chub.ai`, some character card authors always treat dialogue examples as regular dialogue formats.

For example, they only add `<START>` without including `{{user}}:` and `{{char}}:`.
While some authors do not even add `<START>`.

These actions may further lead to dialogue format errors, and there are many similar character cards.

Therefore, it would be best to force prompt users in the input box to write in this format. Or use other methods to restrict it; otherwise, these actions will lead to formatting errors.

Incorrect format (Occasionally encountering such character cards on the `chub.ai` leaderboard):
```
<START>
Message 1. ← (Authors missed {{user/char}})
{{char}}: Message 1.

Empty Line break ← (Authors missed <START>.)
User Name: Message 2. ← (Authors use fixed names instead of {{user/char}} placeholders.)
Char Name: Message 2.

<START>
{{User}}: Message 3. ← (Authors incorrect capitalization in {{user}}.)
```

Incorrect format 2 (The author placed the text before `<START>`  or between `<START>` and `{{user/char}}`)
```
---Voiceover--- ← (The text before <START>)
<START>
{{user}}: Message 1.
{{char}}: Message 1.

<START>
---Voiceover--- ← (Text sandwiched between <START> and {{user/char}})
{{user}}: Message 2.
---Voiceover--- ← (Text sandwiched between {{user}} and {{char}})
{{char}}: Message 2.
```
***
**To fix this (Should prompt the user in the input box):**
```
The "Example Message" syntax <START>, only works in the "Examples of dialogue Inputbox" and should not be filled in the "Description Inputbox".
Do not miss the <START>, {{user}}, {{char}}.
Do not place any text before <START>, the first line must be <START>.
Do not fill in text between <START> and {{user/char}}.
Do not replace {{user/char}} with a fixed name.
{{user/char}} cannot be capitalized.
```
**Correct format:**
```
<START>
{{user}}: Message 1.
{{char}}: Message 1.
<START>
{{user}}: Message 2.
{{char}}: Message 2.
```

**Comment by Cohee1207** [comment]
@VaporHail thanks, but perhaps I don't see anything to be addressed right now from your comments.

> one could consider banning users from using Chat Start in ChatML

Leaving Chat Start empty by default for ChatML should be enough. I don't want to forbid users to use certain features just because they use an overly restrictive instruct format (also applicable to Llama2 chat and its friends).

> While some authors do not even add <START>.

This is fine. It will be auto-added if missing.

> On chub.ai, some character card authors always treat dialogue examples as regular dialogue formats.

Trying to parse a _free-form_ text box into the _strict_ roled format is always a mostly doomed attempt destined to smash into edge cases, but the counter-argument is that this exact parser of example dialogues has been used for Chat Completion API for over a year and there were (almost) no complaints about the outputs. I find it even better that it's time to bring Chat Comps and Text Comps a little bit closer together.

This is all true unless I go and change the UX to use a set of strict role/message inputs for each block, but the cons are:

1. All the other frontends would need to go and apply the same layer of compatibility.
2. Almost impossible to account for each and every format used to write example dialogue before.

One more argument is that SillyTavern's official documentation contains a correct example: https://docs.sillytavern.app/usage/core-concepts/characterdesign/#examples-of-dialogue

So it's on a creator's conscious to ignore that.

**Comment by Cohee1207** [comment]
@aikitoria 

> but I wanted to mention that there seems to be an issue with the stable diffusion plugin inserting a system message at the end, could it be tested whether that works properly with this PR?

This falls into the somewhat obscure "quiet prompts" category, which was tested here. It adds a system message wrapping to the instruction, and the last prompt line uses an assistant prefix, ignoring the "last prefix" as it could cause hallucinations on Alpaca-Roleplay, and removes the name if "names inclusion" is checked. This combination is what produced the most accurate replies for me. Using system/user prefixes for the last line would cause gibberish or impersonation if used. Here's an example:

Prompt:
```
<|im_start|>assistant
Assistant: How are you doing today?<|im_end|>
<|im_start|>system
[In the next response I want you to provide only a detailed comma-delimited list of keywords and phrases which describe Assistant. The list must include all of the following items in this order: name, species and race, gender, age, facial features and expressions, occupation, hair and hair accessories (if any), what they are wearing on their upper body (if anything). Do not describe anything below their neck. Do not include descriptions of non-visual qualities such as personality, movements, scents, mental traits, or anything which could not be seen in a still photograph. Do not write in full sentences. Prefix your description with the phrase 'close up facial portrait,']<|im_end|>

<|im_start|>assistant

```

Output (by "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO")
```
close up facial portrait, Assistant, species and race: human, gender: androgynous, age: 2, facial features and expressions: sharp eyebrows, narrow nose, wide smile, occupation: personal assistant, hair and hair accessories (if any): short straight hair, what they are wearing on their upper body (if anything): black collared shirt
```

**Comment by ghost** [comment]
@Cohee1207 Thank you very much for your clarification. 🫡
Following my approach does indeed bring more compatibility issues, and ChatML is too complicated.
I now only hope that Meta can use a simpler format for training Llama3 to replace the ChatML model. The current community compatibility issues are already quite troublesome. 😫

**Comment by aikitoria** [comment]
> ```
> <|im_start|>assistant
> Assistant: How are you doing today?<|im_end|>
> <|im_start|>system
> [In the next response I want you to provide only a detailed comma-delimited list of keywords and phrases which describe Assistant. The list must include all of the following items in this order: name, species and race, gender, age, facial features and expressions, occupation, hair and hair accessories (if any), what they are wearing on their upper body (if anything). Do not describe anything below their neck. Do not include descriptions of non-visual qualities such as personality, movements, scents, mental traits, or anything which could not be seen in a still photograph. Do not write in full sentences. Prefix your description with the phrase 'close up facial portrait,']<|im_end|>
> 
> <|im_start|>assistant
> ```
> 

But doesn't this have an extra blank line that shouldn't be there, before the last line?

**Comment by Cohee1207** [comment]
> But doesn't this have an extra blank line that shouldn't be there, before the last line?

Fixed already, see commits after that message.

**Pull request merged**
