### PR TITLE
Update world-info.js for fix `#2213`

### PR DESCRIPTION
**Pull request by steve02081504**
Maybe not pretty code, but it worked.

### CODE REVIEW

**Comment by Cohee1207** [comment]
@Bronya-Rand @Wolfsblvt please review.

**Comment by Wolfsblvt** [comment]
No. Recursion will not remove already triggered entries, and it shouldn't. Ever. I explained this in long detail on discord and the reasons why. You'd run into circular references, endless loops and all that stuff so so fast.

WI entries on the same sweep (first sweep over context, first recursive run, second, etc) should not really have impact on each other either.
They get checked against the current context, and optionally against already fully triggered WIs on a sweep before. They will not check against each other.

The bug is not a bug either, it's just a behavior that we should explain in the docs. And I am planning to, once I am done with the other WI features.

Besides that, there are obvious other issues with this code, as it'll check items against each other that aren't really activated yet anyway. They might not be added because of trigger% rolls, because of inclusion groups, or any of the other options that are checked later.

**Comment by Cohee1207** [comment]
I think if you don't want an entry to trigger the others - you just disable recursion for it, ain't it?

**Comment by Cohee1207** [comment]
image

**Comment by Wolfsblvt** [comment]
Yes. exactly this. And if you want to delay a WI from being checked until the first sweep is done, add an always on WI entry with some hidden HTML or something, and make that a required key of all the ones that should only be checked in the second sweep.

If you just want two entries from not being possible being triggered together, you can also utilize the inclusion group setting.

**Comment by steve02081504** [comment]
图片
图片
图片
I guess I might need to shed some light on my situation: I really needed some complex logic to help me refine my character cards.

**Comment by Wolfsblvt** [comment]
Use variables for that. You can use `{{setvar}}` in the body to set when a specific entry is triggered, and then use that to check against other entries. Like I said, just delay their execution until the first recursion sweep, or they won't check against the other triggered WIs.

Also try to read up about how Inclusion Groups work. It's very likely that they already provide all the tools that you need for your case: https://docs.sillytavern.app/usage/core-concepts/worldinfo/#inclusion-group

**Comment by steve02081504** [comment]
Okay, I'll try to got it.
Thanks for all your helps

**Comment by steve02081504** [comment]
@Wolfsblvt I just realized that there is no way for me to use if in world info or to specify multiple Groups for an entry at once.
The logic I'm looking for seems hard to write.....

**Comment by Wolfsblvt** [comment]
Multiple inclusion groups is actually a good idea. I'll write that down and do that soon.

What you can also do is like I said, add something like
```
<!-- ##MY_HIDDEN_ACTIVATOR## -->
```
in the first entry, and use that as a trigger key in the second entry, or something.

**Pull request closed without merging**
