### PR TITLE
Add support for serving the application via HTTPS

### PR DESCRIPTION
**Pull request by artisticMink**
**Purpose**

This pull request enables users to securely communicate with their chosen waifu by encrypting their pillow talk. This feature is particularly useful when using SillyTavern on a remote machine.

**Changes**

-  Added the yargs library to handle command line arguments.
-  Introduced the --ssl flag, which launches the server using HTTPS instead of HTTP.
-  Refactored server launch code for cohesion.

**Usage**

Start SillyTavern with HTTP (default):
`node server.js`
There are no changes to the existing usage.

Start SillyTavern with HTTPS:
`node server.js --ssl`
In this case, the private key and certificate will be loaded from the cert/ directory.

Start SillyTavern with HTTPS and custom key/certificate paths:
`node server.js --ssl --keyPath /home/user/certbot/mydomain/privkey.pem --certPath /home/user/certbot/mydomain/cert.pem`

**Discussion**

The choice of serving the application via HTTP or HTTPS is made explicit through command line arguments. However, there is a valid case for moving the protocol selection and path configuration into a configuration file. This approach would eliminate the need for the yargs dependency and align better with existing conventions. It would be less explicit however.

### CODE REVIEW

**Comment by aios-ai** [comment]
Is this also possible when using SillyTavern in a docker container which is setup with the [docker compose](https://github.com/SillyTavern/SillyTavern/blob/release/docker/docker-compose.yml)?

Is there support for --ssl --keyPath and --certPath flags as well?

**Comment by artisticMink** [comment]
> Is this also possible when using SillyTavern in a docker container which is setup with the [docker compose](https://github.com/SillyTavern/SillyTavern/blob/release/docker/docker-compose.yml)?
> 
> Is there support for --ssl --keyPath and --certPath flags as well?

It should work the same way. However if you run certbot outside of the container you will have to mount a volume including the certificates.

**Comment by aios-ai** [comment]
Thanks for the fast response. I added a volume, so that part should be no problem:

```
version: "3"
services:
  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    ports:
      - "8000:8000"
    volumes:
      - /volume1/docker/sillytavern/config:/home/node/app/config
      - /volume1/docker/sillytavern/user:/home/node/app/public/user
      - /volume1/docker/sillytavern/certs:/home/node/app/certs
    restart: unless-stopped
```

But I do not know where in the compose template I can add the three flags. I'm using portainer/container manager on my NAS and can't modify the startup parameters like that: "node server.js --ssl --keyPath /home/user/certificates/privkey.pem --certPath /home/user/certificates/cert.pem" or at least I don't know how or if that is even possible.

I was hoping for something like that:

```
    environment:
      - cliArguments="--ssl --keyPath /certs/privkey.pem --certPath /certs/cert.pem"
```
or

```
    environment:
      ssl: true
      keyPath: /certs/privkey.pem 
      certPath: /certs/cert.pem
```

**Comment by artisticMink** [comment]
@Sascha353 

You'll have to modify the docker-entrypoint.sh and either add the command line arguments there (at the very bottom where node server.js is called) or introduce some sort of placeholder.

**Comment by aios-ai** [comment]
Thanks again for the answer. So I understand it's not possible via docker-compose. What do you mean with "introduce some sort of placeholder"? Im a user, not a developer. I can create a feature request but I can't implement it. Should I do that?

By the way: The docker-entrypoint.sh is part of the docker image and modifications are lost when I update the container. There is also no easy access to this file if I only have those persistent volume mounts:
```
      - /volume1/docker/sillytavern/config:/home/node/app/config
      - /volume1/docker/sillytavern/user:/home/node/app/public/user
      - /volume1/docker/sillytavern/certs:/home/node/app/certs
```

Preferably the docker image should be controllable via the compose script and persistent even when updated. (At least in regards of basic configuration, like SSL.)

Same for the installed extensions in "/home/node/app/public/scripts/extensions" btw. You also have to reinstall all extensions which each image update.

So besides the config & user folder everything else is lost when updating the image. It's a good start with the current available docker image but I feel like there is room for improvement.

**Comment by artisticMink** [comment]
@Sascha353 

I'm not that familiar with the Docker image, but looking at the Dockerfile and docker-entrypoint.sh, it seems like a pretty simple setup that does some provisioning, sets up the configuration files, and starts the server. If you need the features you describe, you'll either need to extend the existing image or submit a PR.

As for the other issues, extensions being inside the application container seems like an oversight.

**Comment by aios-ai** [comment]
@artisticMink 

You are right about the simple nature of the docker setup and that's not uncommon but at least from my point of view being able to enable SSL is as basic and important as setting the machine name, ports and volumes and thus should be built in. From my experience that's usually available directly via docker-compose, so it's persistent with updates and such. By the way, I was looking for similar questions some weeks ago and didn't find any but just recently there has been something new: https://github.com/SillyTavern/SillyTavern/issues/1672. From what I can tell, that's exactly what we were talking about and the missing part to complete the HTTPS support feature.

I'm not super familiar with ST yet and can't tell if there are more folders relevant to the "update persistency" topic but for extensions, it should be enough to be able to add a volume like that to the docker-compose:

`- /volume1/docker/sillytavern/extensions:/home/node/app/public/scripts/extensions`

**Pull request merged**
