### PR TITLE
Add SD character-specific prompt prefix options to free-mode

### PR DESCRIPTION
**Pull request by Deathspike**
This PR adds the `char` subcommand and `{{charPrefix}}` pseudo-macro to the *Stable Diffusion* extension script. This enables a mode similar to free-mode, except that the prompt is prefixed with the *Character-specific prompt prefix* from the *Image Generation* settings. The idea behind this character-specific free-mode is to enable the creation of images without relying on the LLM to describe the scene, but avoid having to prompt common character appearance each time you want an image.

image

## Subcommand Example

If I have a *Character-specific prompt prefix* set to this:

```
1girl, brown hair, short hair, red eyes,
```

And enter the `char` subcommand like this:

```
/sd char red dress, living room
```

Then the prompt will become this:

```
1girl, brown hair, short hair, red eyes, red dress, living room
```

## Pseudo-macro Example

If I have a *Character-specific prompt prefix* set to this:

```
1girl, brown hair, short hair, red eyes
```

And enter the pseudo-macro like this:

```
/sd red dress, {{charPrefix}}, living room
```

Then the prompt will become this:

```
red dress, 1girl, brown hair, short hair, red eyes, living room
```

## Regression

The code is written to have as little influence on other commands as possible, but writing `/sd char` will add the character-specific prompt prefix. It is no longer possible to use `/sd char something else` without having `char` replaced with the prompt prefix, but I doubt that was a reasonable prompt to begin with. Who begins a free-mode prompt with `char`?

## Behavior

* Supports regular conversations.
* Supports group conversations. Last character to speak is used for *Character-specific prompt prefix*.
* If there is no *Character-specific prompt prefix*, the `char` subcommand removes `char` and the following whitespace.
* If there is no *Character-specific prompt prefix*, the `{{charPrefix}}` pseudo-macro is removed.

### CODE REVIEW

**Comment by Cohee1207** [comment]
Have you considered pseudo-macro like `{{charPrefix}}` for it to be more explicit?

**Comment by Cohee1207** [comment]
Also it will allow it to be anywhere in the prompt string, not just the first part.

**Comment by Deathspike** [comment]
> Have you considered pseudo-macro like `{{charPrefix}}` for it to be more explicit?

I hadn't considered a pseudo-macro since the field is labeled a prefix in the UI, but it certainly makes sense to have more options. I reworked the implementation to support this pseudo-macro: you can now do `/sd red dress, {{charPrefix}}, living room` to have it appear anywhere in the prompt instead of just supporting `/sd char red dress, living room` for a prompt prefix.

Do note that the implementation still supports `/sd char <your additional prompt here>` because I feel that is more convenient if you wish to use the character-specific prompt prefix as, well, a prefix. It's easier to remember and quicker to write than the pseudo-macro. Unless the behavior of interpreting `^char\s` as a prefix is really undesirable, I'd rather keep it in for this PR.

Is there anything else I should do or add for this feature PR?

**Comment by Cohee1207** [comment]
No, looks fine as it is. I'll start testing and merge if it works as described

**Comment by Cohee1207** [comment]
Looks okay, I'll only allow a comma after char to make use of prefixes that don't with comma
So `/sd char, riding a bike` will be equal to `/sd char riding a bike`

**Pull request merged**
