### PR TITLE
Add more macros

### PR DESCRIPTION
**Pull request by steve02081504**
|name|des|
|-|-|
|baseware_name|the name of the baseware, always "SillyTavern"|
|baseware_version|the version number of the baseware, e.g. "1.12.0-preview"|
|char_stat_total_gen_time|the total generation time for the currently selected character|
|char_stat_user_msg_count|the number of user messages for the currently selected character|
|char_stat_non_user_msg_count|the number of non-user messages for the currently selected character|
|char_stat_user_word_count|the number of words used by the user for the currently selected character|
|char_stat_non_user_word_count|the number of words used by the non-user for the currently selected character|
|char_stat_total_swipe_count|the total swipe count for the currently selected character|
|char_stat_date_last_chat|the timestamp of the last chat for the currently selected character|
|char_stat_date_first_chat|the timestamp of the first chat for the currently selected character|

### CODE REVIEW

**Comment by Cohee1207** [comment]
Wait until the macro rewrite so you could add those with extensions.

**Comment by Wolfsblvt** [comment]
All macros we add now have to be supported until all eternity.... 
Macro rewrite is coming. Give me a month tops. I already scoped this out.

Also, those stats, they are fucking borked. #2173 is coming. Just not a big priority right now. And it'll make much more sense, I promise.

**Comment by Cohee1207** [comment]
Yeah, don't rely on existing stats. I didn't even see they're pulled from it.

**Comment by steve02081504** [comment]
Roger that

**Pull request closed without merging**
