### PR TITLE
add possibility for extensions to register new macros

### PR DESCRIPTION
**Pull request by LenAnderson**
Example:

```javascript
import { registerMacro } from '../../../../script.js';
registerMacro(
  /{{list::((?:(?!(?:::)).)+)}}/gi,
  (fullMatch, firstCapture) => {
    return firstCapture.split(/\s*,\s*/).map(it => `- ${it}`).join('\n');
  },
  'list::item1,item2,item3',
  'replaced with a markdown list of the comma separated values'
);
```

### CODE REVIEW

**Comment by valadaptive** [comment]
This doesn't seem like a way to register macros so much as a way to register any arbitrary regex. I'm worried about the effect this could have on macro syntax (and third parties implementing their own bespoke versions of it), as I want to eventually try and unify macros and STScript functions. Is there a way to limit this in scope?

**Comment by Cohee1207** [comment]
Perhaps I have to agree with @valadaptive on that. Macro being all regex already creates some limitations, such as not having the ability to have them arbitrarily nested. The previous iteration of custom macro using handlebars didn't pay off since the syntax was too clunky. So the priority would be:
1. A proper non-regex parser of macros.
2. This thing.
3. (optional) Grammar/lexer for STscript

This is what Agnai uses to define grammar, by the way: https://peggyjs.org/online.html

**Comment by LenAnderson** [comment]
Yes, effectively this means it is up to whoever adds a macro to follow the handlebar syntax. Could of course add some kind of check in the register call or surround whatever matcher is provided with handlebars afterwards, or just give the list of leftover / unresolved macros *without* the handlebars to the third party macro callbacks (although that would prevent something like  {{if}} macros to be made)...

I am not a fan of unnecessarily restricting *third party* extension development. Stifles creativity. Let them do what they want. Why railroad them? If an extension breaks in a future ST update because that extension did not adhere to established guidelines / best practice, that's up to the extension to fix.
The whole `substituteParams` is just a bunch of regex. And without a proper parser, you're going to have to allow the matcher to be regex to allow anything more than simple {{user}} macros.

**Comment by valadaptive** [comment]
> If an extension breaks in a future ST update because that extension did not adhere to established guidelines / best practice, that's up to the extension to fix.

But what constitutes "best practice"? If a public API for registering macros is exposed for the express purpose of allowing extension developers to use it, it seems like that API is part of the "best practices". What happens if afterwards, we realize that API makes it impossible to extend the macro parser with useful features (like nested macros) and we need to remove it? Do we just shrug and say "welp, rewrite your addons, too bad"?

If an extension breaks because of an update, its users aren't going to go to the extension author and say "this new update demonstrates that your extension doesn't follow best practices; please update it". They're going to blame SillyTavern's devs and say "your update broke my extension, make it work again please". In my eyes, it's impossible for an extension dev to take 100% responsibility for using undocumented APIs or reaching too far into ST's internals, because some portion of their userbase will always blame ST regardless.

**Comment by LenAnderson** [comment]
ST isn't corpo software. It's ok if every now and then a major update breaks backwards compatibility. Especially if that comes with a leap in whatever feature needed a rewrite.

Users blame ST for bad character cards they download somewhere, for their proxies not working, for their LLM software not being configured correctly... If you want to avoid the disgruntled user you need to pull an Apple and lock everything down, provide a "complete" experience out of the box without any dependence on third parties and constrict the users to this tiny walled garden. But then it wouldn't really be for power users anymore...

Let's update the jsdoc on the register function to advise the dev to make all macros surrounded by handlebars, put it in the docs as well. Maybe a note advising that macro implementation is subject to change? And if you're confident you're going to tackle the parser some time soon, why not add a comment saying that the whole macro feature is likely to change entirely in the near future.

**Comment by valadaptive** [comment]
> It's ok if every now and then a major update breaks backwards compatibility. Especially if that comes with a leap in whatever feature needed a rewrite.

Can you clarify what you mean by "major update"? AFAIK, SillyTavern does rolling releases. Features are released as soon as they're merged in. For something like e.g. video game mods, it's fine if a new update breaks all the mods, because those updates typically happen every several months at their fastest. SillyTavern releases every 2 weeks.

> Users blame ST for bad character cards they download somewhere, for their proxies not working, for their LLM software not being configured correctly... If you want to avoid the disgruntled user you need to pull an Apple and lock everything down, provide a "complete" experience out of the box without any dependence on third parties and constrict the users to this tiny walled garden. But then it wouldn't really be for power users anymore...

And many of these complaints *do* result in more and more corner cases and workarounds being added into the codebase and left to be untangled later. They're not just ignored. Here are two examples I ran into:
- When I refactored the parsing of server-sent events, the PR was blocked because [one proxy designed specifically for SillyTavern misimplemented server-sent events](https://github.com/SillyTavern/SillyTavern/pull/1482#issuecomment-1845804139), and I had to dig that down and prove that they fixed it 7 months ago and we no longer needed the workaround.
- When I split up the server code into separate modules and changed the API routes, [I had to insert redirects for all of them](https://github.com/SillyTavern/SillyTavern/blob/7104daf7f092735331d17f5d2e62e211c110c0c0/server.js#L440-L487) because of concerns that extensions directly called the old routes.

I can't speak for Cohee, but I think they care about backwards compatibility more than you do, and it'll be on them to maintain this code if it gets merged in, and to handle any backlash from ensuing extension breakage.

**Comment by Cohee1207** [comment]
As for release strategy, SillyTavern has "stable" releases [read as "sync with a trunk"] on irregular cadence (usually 2 to 3 weeks), and a rolling release staging branch that gets all the new and experimental features and can (and sometimes does) break stuff like add-ons, but we have some time to iron this out before the next release push.

This feature right here can be designed with further refactoring in mind if we abstract from using regex and replacer functions, but define some sort of "API" for macros, so it could be merged and used by extension authors and then transparently migrated to a new under-the-hood engine without breaking backward compatibility.

Of course, we have no contractual obligations with extension authors, but once something is exposed, it should be treated lightly, or there could be cases like removing extensionHandlebars export half an hour before an extension using it was posted, or anything like already described above.

**Comment by LenAnderson** [comment]
I meant "major" as in "something big", not necessarily in terms of versioning and release cycles. I would categorize a complete rewrite of a feature like macros or stscript to make it more robust and flexible a major change. And I would expect it to lead to some breakage in third-party stuff that relies on it, if only because there are lots of weird / unintuitive corner-cases currently introduced by the regex-parsing and stringification going on.

I think it would be a shame to block opening up a useful part of ST to third party development based on the fear of a potential future rewrite that might break something. Slap a warning on it. Hell, if you're sure you're going to tackle the macro rewrite, let's mark it deprecated from the get go.

An easy way to restrict its potential scope and make sure all extension macros are limited to `{{...}}` would be to only feed the contents of unresolved handlebar-enclosed text to the registered extension macros. But as I said before, that would severely hamper its potential.

How do you intend to abstract away regex and functions (in macro's current state) without neutering its use? Regex allows flexible matching (and is something most developers should be familiar with), and functions allow using logic in the construction of the replace-value.
I'm open to suggestions if you have any concrete ideas.
I just feel it would be a waste of time if it ends up being a glorified plaintext search-and-replace. Too much railroading will hurt a feature as much as breaking changes some time later down the line.

**Comment by Cohee1207** [comment]
> I just feel it would be a waste of time if it ends up being a glorified plaintext search-and-replace.

Well, by exposing raw regex you're literally just doing that. I propose the following API.

```js
/**
 * @param {string} name
 * @param {(args: string[]) => string} replaceFn
 * @param {string} docString
 */
registerMacro(name, replaceFn, docString) {
   ...
}

registerMacro('demo', (args) => args.join(', '), 'returns comma-separated arguments');
substituteParams(`{{demo::1::2::3}}`) // 1, 2, 3
```

**Pull request closed without merging**
