### PR TITLE
Deleting the current chat when creating a new one

### PR DESCRIPTION
**Pull request by berbant**
Added an optional checkbox to the new chat creation modal for deleting the current chat. (after finding hundreds of old unnecessary chats with tests and more in my /chats folder...)
Screenshot 2024-02-25 at 11 39 00

### CODE REVIEW

**Comment by Cohee1207** [comment]
Thanks, but what is the intended use case, besides using a whole lot of test chats? This seems very specific and not entirely sure about it.

**Comment by berbant** [comment]
> Thanks, but what is the intended use case, besides using a whole lot of test chats? This seems very specific and not entirely sure about it.

In ST, chats are stored in plain text without encryption. Plus, It also doesn't have a batch delete chat function. feature. Keeping hundreds of files with your personal chats with neural networks in open form can be risky. Especially when a new user doesn't know about the /public/chats folder, they're gonna be surprised to find hundreds of old chats that need to be deleted manually. I figured it'd be better to quickly get rid of what you don't need right off the bat, rather than remembering to clean your archive months later.

**Comment by Cohee1207** [comment]
> Plus, It also doesn't have a batch delete chat function

Maybe it's better to add that instead?

> Keeping hundreds of files with your personal chats with neural networks in open form can be risky

What's the difference between keeping just the latest file vs all the files? And if auto-saved backups are enabled, they are not automatically deleted.

**Comment by berbant** [comment]
> Maybe it's better to add that instead?

This will be helpful. I can put this feature on my todo list.

> And if auto-saved backups are enabled, they are not automatically deleted.

I made a mention of it in the 'title' of the new checkbox 

> What's the difference between keeping just the latest file vs all the files? And if auto-saved backups are enabled, they are not automatically deleted.

The difference is that at the moment when the user creates a new chat, they decide whether to save the current one or not, rather than at the hypothetical moment when they need to delete all the chats or just some of them without deleting the character entirely (which is exactly my case). Anyway, Cohee, it's just an optional extra. What's not to like about it? ;)

**Comment by Cohee1207** [comment]
I'm not saying that I don't like it, I'm trying to understand the use case as it seems to be very specific to a not-very-common use pattern and that there can be other (better) ways around it.

**Pull request merged**
