### PR TITLE
Adjust style/position for search in character list, make favs scrollable

### PR DESCRIPTION
**Pull request by Dakraid**
image

### CODE REVIEW

**Comment by Wolfsblvt** [comment]
Hotswap shouldn't be a general change linke this. People might have a lot of favorites.  
And it's a simple CSS edit if you need it for you.

Search I am not sure. The other places in the UI (World Info, Persona) follow the same order of buttons, search bar, then sort order dropdown. Why switch that up?  
Making it flex and set sensible grow values and min lengths would be better I think.

**Comment by Spacellary** [comment]
**About the scrollable favorites:** <br>
Honestly I really like this. If this isn't merged/reworked into the project I'd like to get the CSS import for this, I believe if able to incorporate this would be a big quality of life improvement. I can't be the only one that hates having such a limited number of characters available for hot-swap.

**Search bar location:** <br>
This I don't see much need for.

**Comment by Wolfsblvt** [comment]
Should be an easy snippet to share, with just a few lines needed.

But if you have so many favorites needed, why don't you just use the character list? It's not like hotswaps are visible without the list being displayed.  
And currently, the content of the hotswap already scales with space. So if you have wider side panels, more will be visible. And with small avatars a lot more would fit too. You could just reduce their size with a small CSS edit, or allow multiple rows. I have made a snipped like this on Discord already.

**Comment by Spacellary** [comment]
@Wolfsblvt
> And currently, the content of the hotswap already scales with space.

"Doesn't scale enough", but seriously I think it's pretty valid and useful, on mobile it's more convenient to scroll the favorites list at the top than to go all the way back to the full list of characters, even with the amazing Folder Tag enhancements, and I mean it, they are amazing.

I vouch for expanded hot-swap capacity or functionality in line with what's reasonable, or well, the CSS snippet works, but I actually think this would help more people.

Personally I do a lot of character testing and that's a pretty easy improvement to benefit from.

**Comment by Dakraid** [comment]
> Should be an easy snippet to share, with just a few lines needed.
> 
> But if you have so many favorites needed, why don't you just use the character list? It's not like hotswaps are visible without the list being displayed. And currently, the content of the hotswap already scales with space. So if you have wider side panels, more will be visible. And with small avatars a lot more would fit too. You could just reduce their size with a small CSS edit, or allow multiple rows. I have made a snipped like this on Discord already.

I have about 500 characters (I often download multiple of the same character but by different authors), so even 10 favorites are still more usable to me than the list + search :)

**Comment by Wolfsblvt** [comment]
Go and sort through your characters man.  
Not gonna judge, but seriously. Enable „Tags as Folders“, create some hidden/closed folders, and go sort/classify your characters in a sensible way so you can use and find them better.
That‘s much more effective than have another big list you can scroll through. Because you know that you can click the „filter favs“ filter icon and then just have the char list be a…. scrollable list of your few dozen chars? Why need another list that you can scroll exactly that way?

I think that‘s much more of a „don‘t be a messy“ issue than a UI issue of ST that should be changed. But I might have gotten brainwashed too much from Cohee.

Edit: „Hotswap“, as the name already says, is a panel to very quickly switch between a few chars, fast. Not another list/folder for characters to sort them into.

**Comment by Spacellary** [comment]
> Edit: „Hotswap“, as the name already says, is a panel to very quickly switch between a few chars, fast. Not another list/folder for characters to sort them into.

I strongly disagree on this aspect. There's no reason to not enhance that feature my making it more versatile.

Even with the enhanced Folder Tags having more hot-swap capacity is amazing. Just because your usage doesn't revolve around as many characters, trust me, there are many freaks who can use every feature expansion.

On another note, I mentioned that considering Mobile usage, hot-swap slots are much easier to access than to go back all the way to the Folder list, as menu navigation isn't as seamless as the Desktop screen real estate provides.

Hot swaps can contain a variety of useful cards across many different folders in a convenient location. As such, I still echo that this is a great idea.

*The only thing better than this was eventually integrating Folder Tags directly into hot-swap slots, imagine the possibilities...*

**Comment by Wolfsblvt** [comment]
You can still very easily make a CSS edit if you need more favs in the hotswap.  
If you want hotswap to just be another huge folder/list, then that's on you. That wasn't how that feature was designed. It *can* be used like this, if you modify it, but it shouldn't be by default. That goes against the general meaning for "favorites" imho.

> _The only thing better than this was eventually integrating Folder Tags directly into hot-swap slots, imagine the possibilities..._

Please elaborate? I am slightly intrigued.

**Comment by Cohee1207** [comment]
I'm not planning to include horizontal scroll as an anticipated default state.

Scrollability could be added with several lines of CSS:
```css
#HotSwapWrapper {
    justify-content: space-evenly;
    overflow-x: auto;
    flex-wrap: nowrap;
}

#HotSwapWrapper > .hotswap {
    overflow-x: scroll;
    flex-wrap: nowrap;
    max-height: max-content;
}
```

Putting search on a separate line might be good, since with extensions adding buttons there, it's getting pretty crowded, but space is very precious in the top bar of the characters list, so I'm not sure that introducing a third line won't result in negative feedback.

**Comment by Wolfsblvt** [comment]
I already shared other CSS edits for hotswap, where you can even specify how many favorites by number.

For the bars and buttons, forcing a new line is not really good. Making it flex is okay, but that's already the case right now. What the best order is depends on what your screen size and chosen chat size is, so for some the search bar before is much better, for some another like this is better.

So we either make the order configurable/draggable and save it, or keep the order consistent to all the other settings windows, like I have explained above.

Though a different order is also easily achievable with custom css if you need.

**Pull request closed without merging**
