### PR TITLE
Added English texts in `en.json`

### PR DESCRIPTION
**Pull request by Zhongyi-Lu**
Related to https://github.com/SillyTavern/SillyTavern/issues/2074

Could anybody check if there are any typos?

### CODE REVIEW

**Comment by Touch-Night** [comment]
They're not original text and does not fit all the text shown in the webpage.  
Better if you extract all the elements with `<data-i18n="">` tag and put them all in `en.json`.

**Comment by Zhongyi-Lu** [comment]
@Touch-Night Good idea!

**Comment by Touch-Night** [comment]
Note: not all `<data-i18n>` tag takes effects and there are some values like `<data-i18n="[title]xxxx">`, then in json file the key should be `xxxx`, not `[title]xxxx`.  
And incorrect order of keys in json file may break ST. I discovered that when I tried to extract all the `<data-i18n> `

**Comment by Cohee1207** [comment]
"en" is intentionally left empty. Having to update texts both in HTML and JSON is going to make development more cumbersome and directly impact a delivery of new features.

**Comment by Cohee1207** [comment]
Instead of making it affect the localization files - make it able to find missing key placeholders to already existing localization files.

**Comment by Touch-Night** [comment]
But translators can be more cumbersome if there's no a full list of key: "original text" because we have to go through every page to find out which one are not translated and what's its key. Can't you make ST read original text from en.json, or just give us a need_to_be_translated.json file only for reference so we can translate ST 100%?

**Comment by Zhongyi-Lu** [comment]
> And incorrect order of keys in json file may break ST

@Touch-Night Do you mean the order in the translation JSON file matters? It's a bit strange.

**Comment by Zhongyi-Lu** [comment]
I find there are 3 cases for the `data-i18n`:

1. values are in the block
Example:`<li><button id="character_context_menu_favorite" data-i18n="Favorite">Favorite</button></li>`
2. values are in the attributes
Example: `<i data-newbie-hidden title="Import preset" id="import_oai_preset" class="menu_button fa-solid fa-file-import" data-i18n="[title]Import preset"></i>`
3. values in the JS files
Example:
```js
const footerHtml = `
                <div class="${this.configuration.prefix}prompt_manager_footer">
                    <select id="${this.configuration.prefix}prompt_manager_footer_append_prompt" class="text_pole" name="append-prompt">
                        ${promptsHtml}
                    </select>
                    <a class="menu_button fa-chain fa-solid" title="Insert prompt" data-i18n="[title]Insert prompt"></a>
                    <a class="caution menu_button fa-x fa-solid" title="Delete prompt" data-i18n="[title]Delete prompt"></a>
                    <a class="menu_button fa-file-import fa-solid" id="prompt-manager-import" title="Import a prompt list" data-i18n="[title]Import a prompt list"></a>
                    <a class="menu_button fa-file-export fa-solid" id="prompt-manager-export" title="Export this prompt list" data-i18n="[title]Export this prompt list"></a>
                    <a class="menu_button fa-undo fa-solid" id="prompt-manager-reset-character" title="Reset current character" data-i18n="[title]Reset current character"></a>
                    <a class="menu_button fa-plus-square fa-solid" title="New prompt" data-i18n="[title]New prompt"></a>
                </div>
            `;
```

For the first and second cases, it is easy to extract English texts by parsing HTML using `BeautifulSoup` in Python.
The third case is harder. I try to extract them using Regex but I didn't manage to do it.

Fortunately, we only have about 20 key-value pairs in the 3rd case and it is okay to manually copy them to the JSON file.

I would like to mention my current progress here. If we think adding `en.json` is necessary, I can keep moving forward. Otherwise, I will pause my work and wait for the consensus. Thank you!

**Comment by Cohee1207** [comment]
en.json was present in the past but was emptied as it was annoying to work with - you have to go and change the text if you change it in the HTML, it is not convenient for developers and contributors who are working on new features. A script that will fill out the localization JSON files with the string keys to translate will be nice. But I'm actually thinking about an alternative to JSON that supports files - `.js` files that declare a key-value object in its exports and provide comments with the original text.

```js
export const i18n = {
    // original value
   "key text": "翻译",
   // ...etc
};
```

This would require a slight rework of the i18n loader, however.

**Comment by PasserDreamer** [comment]
I think it would be better to create a template.js that won't be used directly. This way, managing translations in the future will be easier and it won't interfere with the English interface.

**Comment by Cohee1207** [comment]
> I think it would be better to create a template.js that won't be used directly. 

This still raises the question of who would be responsible for maintaining this template in an up-to-date state.

**Comment by Cohee1207** [comment]
This is superseded by the following project: https://github.com/SillyTavern/SillyTavern-i18n

The script will parse and auto-add missing keys from HTML files which is perfect and doesn't require a lot of developers attention. I'm closing this by now. If you got any questions - move it the i18n repo issues/discussions.

**Pull request closed without merging**
