### PR TITLE
Quad sample and DynaTemp Exponent

### PR DESCRIPTION
**Pull request by AAbushady**
UI elements for Kalomaze's Quadratic Sampling, and the DynaTemp Exponent field.

### CODE REVIEW

**Comment by frammiie** [comment]
Thank you for your efforts, would love to see this merged!

**Comment by Cohee1207** [comment]
At least quadratic sampling still isn't ready to be merged as it's not in the backends.

https://github.com/oobabooga/text-generation-webui/pull/5403
https://github.com/LostRuins/koboldcpp/pull/652

**Comment by AlpinDale** [comment]
Added to aphrodite @ PygmalionAI/aphrodite-engine#233

**Comment by LostRuins** [comment]
So smoothing factor is another modification to temperature scaling? Is it actually useful and worth adding? Mildly concerned that we eventually end up with a huge clutter of unused configurations.

**Comment by frammiie** [comment]
@LostRuins it's been tested with great results my various different people at this point. 

Though it's likely understandable to wait with this PR until official merged API support in backends.

**Comment by AAbushady** [comment]
> So smoothing factor is another modification to temperature scaling? Is it actually useful and worth adding? Mildly concerned that we eventually end up with a huge clutter of unused configurations.

@LostRuins Yes it is definitely worth it. As @frammiie mentioned it has been tested by quite a few folks at this point with positive results. It allows for coherence at higher temperatures but without sacrificing creativity, or uniqueness of reply per generation, if configured correctly. My experience it's a more powerful min p.

@kalomaze can probably speak to it in a more technical way than I can though.

**Comment by AAbushady** [comment]
https://github.com/theroyallab/tabbyAPI/pull/56

Tabby implementation for those interested

**Comment by AAbushady** [comment]
@Cohee1207 I think we're stable on the implementation specifics. So setting this to Open.

Turboderp merged it into exllamav2

**Comment by LostRuins** [comment]
Personally the math for the sampler does not really make sense to me, but if people want it, then i'll add it as an option.

**Pull request merged**
