### PR TITLE
Add Gemma 2 9b to available Groq models

### PR DESCRIPTION
**Pull request by fizzAI**
pretty self-explanatory, i hope? :)

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by fizzAI** [comment]
ah dammit how did mixtral get in the list twice

**Comment by Wolfsblvt** [comment]
> ah dammit how did mixtral get in the list twice

Wasn't meeeeeeeeeeeeeeeee

Looks good. Should be an easy merge.

**Comment by fizzAI** [comment]
works from my testing (tho it won't work well with the default chat completion templates, because they use system roles which gemma doesn't support, but that's another problem :P)

**Comment by Cohee1207** [comment]
Wouldn't use a Gemma tokenizer since we don't provide a copy of it (lame!) but otherwise it should be good to go as-is.

**Pull request merged**
