### PR TITLE
Add DreamGen llama 3 templates

### PR DESCRIPTION
**Pull request by DreamGenX**

### CODE REVIEW

**Comment by Cohee1207** [comment]
I think you forgot to add the templates.

**Comment by DreamGenX** [comment]
Indeed, apologies @Cohee1207

**Comment by Cohee1207** [comment]
Don't forget to update the context index, otherwise the files won't be copied
https://github.com/SillyTavern/SillyTavern/blob/release/default/content/index.json

**Comment by DreamGenX** [comment]
Oh, sorry, looks like I did not rebase, hopefully things are in order now.

**Pull request merged**
