### PR TITLE
Update constants.js

### PR DESCRIPTION
**Pull request by zhongerxll**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Cohee1207** [comment]
Mind sharing the source for this?

**Comment by zhongerxll** [comment]
> Mind sharing the source for this?

```
Google AI Studio API returned error: 400 Bad Request {
  "error": {
    "code": 400,
    "message": "* GenerateContentRequest.safety_settings[4]: element predicate failed: $.category in (HarmCategory.HARM_CATEGORY_HATE_SPEECH, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, HarmCategory.HARM_CATEGORY_HARASSMENT, HarmCategory.HARM_CATEGORY_CIVIC_INTEGRITY)\n* GenerateContentRequest.safety_settings[5]: element predicate failed: $.category in (HarmCategory.HARM_CATEGORY_HATE_SPEECH, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, HarmCategory.HARM_CATEGORY_HARASSMENT, HarmCategory.HARM_CATEGORY_CIVIC_INTEGRITY)\n* GenerateContentRequest.safety_settings[6]: element predicate failed: $.category in (HarmCategory.HARM_CATEGORY_HATE_SPEECH, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, HarmCategory.HARM_CATEGORY_HARASSMENT, HarmCategory.HARM_CATEGORY_CIVIC_INTEGRITY)\n",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by Cohee1207** [comment]
What model?

**Comment by zhongerxll** [comment]
> What model?

gemini-1.5-pro-exp-0827

**Comment by zhongerxll** [comment]
"I first saw this document: https://ai.google.dev/api/generate-content#v1beta.HarmCategory, and then I tried adding some other harm categories. However, it returned an error, and I realized that only these five can be used."

**Comment by Cohee1207** [comment]
Let's hold it off. I can't find this documented anywhere, and I don't receive an error when this is not provided.
Judging by the name, it could be something related to upcoming US elections.

**Comment by zhongerxll** [comment]
> Let's hold it off. I can't find this documented anywhere, and I don't receive an error when this is not provided. Judging by the name, it could be something related to upcoming US elections.

"The parameter can prevent Gemini from refusing output in certain situations, which I believe is beneficial and harmless."

**Pull request merged**
