### PR TITLE
Try to support using multiple API keys simultaneously, separated by commas, and switch the API key with each message sent.

### PR DESCRIPTION
**Pull request by zhongerxll**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by steve02081504** [comment]
哥们 用英文提交pr和commit被接受的概率大点 建议改改

**Comment by Cohee1207** [comment]
What's the use case? Can you do it as an extension/server plugin instead?

**Comment by zhongerxll** [comment]
> What's the use case? Can you do it as an extension/server plugin instead?

"Um, I'm quite poor. Google's Gemini has a free API but with a usage limit. However, you can apply for multiple API keys at the same time, which allows me to avoid frequently changing the API keys." --Translate by ChatGPT

**Comment by zhongerxll** [comment]
"I will try the extension/server plugin."

**Comment by Cohee1207** [comment]
Here's an example of a server plugin. You can manipulate user secrets from it.

https://github.com/SillyTavern/Plugin-WebpackTemplate

**Comment by Cohee1207** [comment]
I made a working plugin for you. Download and drop in your /plugins directory. Don't forget to enable plugins with config.yaml

https://gist.github.com/Cohee1207/6d70d0b89fe55ac7149151688e73ba44

**Comment by Cohee1207** [comment]
UI extension part would require you to listen to event_types.GENERATION_STARTED event and perform an API call to the plugin: 
`POST /api/plugins/switch-secrets/switch`

**Comment by zhongerxll** [comment]
> UI extension part would require you to listen to event_types.GENERATION_STARTED event and perform an API call to the plugin: `POST /api/plugins/switch-secrets/switch`

"Thank you. Once I finish my work today, I will start trying."

**Comment by Cohee1207** [comment]
Please don't push the extension and plugin in this repo. Make separate repositories for them.

**Comment by zhongerxll** [comment]
> Please don't push the extension and plugin in this repo. Make separate repositories for them.

Okay, they are now here
https://github.com/zhongerxll/st-plugin-multiple-secrets
https://github.com/zhongerxll/st-extension-multiple-secrets

**Pull request closed without merging**
