### PR TITLE
Update extensions.js to match https://github.com/SillyTavern/SillyTav…

### PR DESCRIPTION
**Pull request by Dalethium**
see: https://github.com/SillyTavern/SillyTavern-Extras/pull/164 https://github.com/SillyTavern/SillyTavern-Extras/issues/162

### CODE REVIEW

**Comment by Cohee1207** [comment]
This shouldn't matter as these headers need to be in response, not in request

**Comment by Cohee1207** [comment]
Bypass-Tunnel-Reminder is only needed for hosting via localtunnel, which we no longer use or recommend, so I can remove that header altogether

**Comment by Dalethium** [comment]
Ah, alright!

**Comment by Cohee1207** [comment]
I removed the header, you can update and it will no longer be a requirement

**Pull request closed without merging**
