### PR TITLE
Add Cohere command-r7b-12-2024

### PR DESCRIPTION
**Pull request by cloak1505**
Also slightly reorder model list. Babby's first PR.

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Cohee1207** [comment]
Does it set a valid context size when chosen?

**Comment by cloak1505** [comment]
> Does it set a valid context size when chosen?

Yes, matches 'command-r' in openai.js. Caught incorrect sizes for other models.

Looks good now. I tested them.

**Comment by cloak1505** [comment]
I'm not even sure if `c4ai-aya-23` & `c4ai-aya-expanse-32b`, and `c4ai-aya-23-8b` & `c4ai-aya-expanse-8b` are different models. With deterministic settings, they output the same thing.

Shouldn't we just remove the aya-23 models, considering they aren't even in the docs?

**Comment by Cohee1207** [comment]
Those are likely aliases of the latest version to the concrete snapshot. I'd say leave the list as-is as long as it allows making a request. Don't remove a model until it returns 400/404 from the API.

**Pull request merged**
