### PR TITLE
TTS API for the GPT-SoVITS-V2 model zero-shot

### PR DESCRIPTION
**Pull request by v3ucn**
## Checklist:

- [x] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

GPT-SoVITS-V2 model TTS Project :  https://github.com/v3ucn/GPT-SoVITS-V2

PixPin_2024-09-08_18-33-04

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
Better than fish speech?

**Comment by Wolfsblvt** [comment]
Man, she really is ripped.

**Comment by v3ucn** [comment]
> Better than fish speech?

more or less

**Comment by v3ucn** [comment]
> Man, she really is ripped.

hope ur pillow is cold tonight

**Comment by Ph0rk0z** [comment]
fish-speech went to msgpack in the API it serves, but the 1.4 version is now decent and the compile works. goes really fast.

**Comment by Runo888** [comment]
@v3ucn Do you have any instructions for running SoVITS and connecting it to SillyTavern? I don't know how connect it via the SoVITS WebUI.

**Pull request merged**
