### PR TITLE
Tabby models list

### PR DESCRIPTION
**Pull request by Cohee1207**
1. Adds a dropdown with all available Tabby models.
2. Adds ability to switch models with generation requests (if the setting is enabled on Tabby's end).
3. Fixes Tabby streaming errors being silently discarded. 

## Checklist:

- [X] I have read the [Contributing guidelines](https://github.com/SillyTavern/SillyTavern/blob/release/CONTRIBUTING.md).

### CODE REVIEW

**Review by Wolfsblvt — APPROVED** [review]
Looks oki. Haven't tested though.

**Comment by RossAscends** [comment]
tested it. works well but finnicky. partially tabby's issue related to conflicts between tabby's config.yml, and model's config.json. have advised him on how to fix it, and he's working on it. 

suggested changes on our end: 
- switch over to `/v1/model/load` as it allows providing parameters as per the loader extension
- following from above, port the extension 'editor' params (and draft loader?) inputs into the connection manager code.
- make model switch happen after selection (and probably a 'load' button click), not on 'first gen' (as is the case with the current inline model loding)

**Comment by Cohee1207** [comment]
> tested it. works well but finnicky. partially tabby's issue related to conflicts between tabby's config.yml, and model's config.json. have advised him on how to fix it, and he's working on it.

I hope it will be covered by #1938... one day... perhaps.

**Comment by kingbri1** [comment]
Agreed. In this case, using the "model" parameter in `/v1/completions` is moreso a workaround for frontends that do model switching on generation like OpenWebUI and is **not** meant for pure loading. Instead, the `/v1/model/load` endpoint is used for cases like SillyTavern's.

**Pull request merged**
